### ISSUE TITLE
Segfault on dead keys

### ISSUE THREAD

**Issue by stephancb** [alacritty/alacritty#1038]
Alacritty just disappears (probably segfaults) when typing a character with a dead key. Keyboards with dead keys are for example "US alt intl". or "US intl. with dead keys". To get for example  quotation marks ", you type first " followed by space. " followed by a gives ä. The terminal vanishes after typing the key after a dead key. In case of ä, ö, ... I can see the ä, ö, ... briefly appearing before the terminal vanishes.

Which operating system does the issue occur on?

On Fedora 27. I built Alacritty myself following the instructions.

`$ rustc --version
rustc 1.23.0 (766bd11c8 2018-01-01)`

If on linux, are you using X11 or Wayland?

X11

**Comment by chrisduerr** [comment]
Could you provide more information please? If you launch alacritty from a different terminal instance, you should be able to see a reason for the crash.

**Comment by stephancb** [comment]
Ah, now I see: it crashes actually only when I use the discrete GPU (nvidia) via bumblebee:
`$ optirun alacritty`

When launched (using integrated GPU) with
`$ alacritty`

everything is fine. So it is probably a problem with bumblebee, sorry for the false alarm.

Just in case, the output with

`$ RUST_BACKTRACE=1 optirun alacritty `

is

```
thread 'pty reader' panicked at 'Failed to call XSendEvent after wakeup: XError { description: "BadValue (integer parameter out of range for operation)", error_code: 2, request_code: 101, minor_code: 0 }', /checkout/src/libcore/result.rs:906:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:397
             at /checkout/src/libstd/panicking.rs:577
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   4: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   5: core::panicking::panic_fmt
             at /checkout/src/libstd/panicking.rs:498
   6: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
   7: winit::EventsLoopProxy::wakeup
             at /checkout/src/libcore/result.rs:799
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/platform/linux/x11/mod.rs:828
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/platform/linux/mod.rs:430
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/lib.rs:256
   8: <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}
             at src/window.rs:445
             at ./code/src/alacritty/src/event_loop.rs:398
thread 'main' panicked at 'Error sending shutdown to event loop: Disconnected', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:397
             at /checkout/src/libstd/panicking.rs:577
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   4: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   5: core::panicking::panic_fmt
             at /checkout/src/libstd/panicking.rs:498
   6: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
   7: alacritty::run
             at /checkout/src/libcore/result.rs:799
             at src/main.rs:212
   8: alacritty::main
             at src/main.rs:62
   9: main
  10: __libc_start_main
  11: _start
```

**Comment by kchibisov** [comment]
Closing. If you still can repro, please open a new issue.
