### ISSUE TITLE
Mouse click positions are not accurate until after the mouse moves in the focused window

### ISSUE THREAD

**Issue by nshahan** [alacritty/alacritty#2475]
Mac OS 10.14.4
Alacritty v0.3.2

Repro:
This is easiest to reproduce (and happens pretty commonly) when using a trackpad because that makes it easier to send a click without any tiny movements of the pointer.

1) Open a file in an editor with mouse support (for example vim with mouse enabled).
2) Position the mouse pointer over some line in that file and click.
  The cursor should move the that location.
3) Switch focus to some other applicaiton (not alacritty) on your computer.
4) Move the mouse to a position over the alacritty window when it **_does not_** have focus.
5) Click without moving the mouse.
  The alacritty window should now have focus.
6) Click again without moving the mouse.
  The click is triggered where the mouse was positioned before the alacritty window lost focus.

As soon as you move the mouse with the alacritty window focused the clicks will now appear in the correct position.

This is easy to observe in text editors. For example, double clicks typically highlight the entire symbol your mouse is currently over. You can see the symbol under the old location where your mouse was get highlighted. 

I have recreated the same scenarios with other utilities as well. tmux with mouse mode on will show the same problem when switching focus away and back to the alacritty window and clicking without moving the mouse. Pane selection will not be accurate until you move the mouse over a focused alacritty window.

**Comment by chrisduerr** [comment]
Can this be reproduced without any application running inside of Alacritty and without mouse mode enabled? So just by starting a selection?

**Comment by nshahan** [comment]
Yes, it can be reproduced with a double click that selects text. Mouse clicks are triggered at the position where the pointer was before the alacritty window loses and regains focus.

**Comment by chrisduerr** [comment]
Just to make sure, when running `alacritty --print-events`, are new events actually printed when moving the mouse over the window while it is not focused?

**Comment by nshahan** [comment]
No events are printed while the alacritty window does not have focus. Below is a sample of the output. I was moving the mouse over the window between the entries for the `Focused(false)` and `Focused(true)` events.

```
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: CursorMoved { device_id: DeviceId(DeviceId), position: LogicalPosition { x: 665.3828125, y: 117.5546875 }, modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } }
[2019-05-24 14:41] [INFO] glutin event: DeviceEvent { device_id: DeviceId(DeviceId), event: MouseMotion { delta: (-1.0, 0.0) } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: CursorMoved { device_id: DeviceId(DeviceId), position: LogicalPosition { x: 665.10546875, y: 117.5546875 }, modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: CursorMoved { device_id: DeviceId(DeviceId), position: LogicalPosition { x: 664.828125, y: 117.5546875 }, modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 55, state: Pressed, virtual_keycode: Some(LWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 55, state: Released, virtual_keycode: Some(LWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: Focused(false) }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: Focused(true) }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: MouseInput { device_id: DeviceId(DeviceId), state: Pressed, button: Left, modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: TouchpadPressure { device_id: DeviceId(DeviceId), pressure: 0.0, stage: 1 } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: TouchpadPressure { device_id: DeviceId(DeviceId), pressure: 0.00093078613, stage: 1 } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: TouchpadPressure { device_id: DeviceId(DeviceId), pressure: 0.0021362305, stage: 1 } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: TouchpadPressure { device_id: DeviceId(DeviceId), pressure: 0.0033569336, stage: 1 } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: TouchpadPressure { device_id: DeviceId(DeviceId), pressure: 0.0068206787, stage: 1 } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: TouchpadPressure { device_id: DeviceId(DeviceId), pressure: 0.014907837, stage: 1 } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: TouchpadPressure { device_id: DeviceId(DeviceId), pressure: 0.02456665, stage: 1 } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: TouchpadPressure { device_id: DeviceId(DeviceId), pressure: 0.034194946, stage: 1 } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: TouchpadPressure { device_id: DeviceId(DeviceId), pressure: 0.043533325, stage: 1 } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: TouchpadPressure { device_id: DeviceId(DeviceId), pressure: 0.049545288, stage: 1 } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: TouchpadPressure { device_id: DeviceId(DeviceId), pressure: 0.04786682, stage: 1 } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: TouchpadPressure { device_id: DeviceId(DeviceId), pressure: 0.046188354, stage: 1 } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: TouchpadPressure { device_id: DeviceId(DeviceId), pressure: 0.044570923, stage: 1 } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: TouchpadPressure { device_id: DeviceId(DeviceId), pressure: 0.043014526, stage: 1 } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: MouseInput { device_id: DeviceId(DeviceId), state: Released, button: Left, modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } }
[2019-05-24 14:41] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: TouchpadPressure { device_id: DeviceId(DeviceId), pressure: 0.0, stage: 0 } }
[2019-05-24 14:42] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 55, state: Pressed, virtual_keycode: Some(LWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
[2019-05-24 14:42] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 12, state: Pressed, virtual_keycode: Some(Q), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
[2019-05-24 14:42] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140212696022592)), event: ReceivedCharacter('q') }
[2019-05-24 14:42] [INFO] Goodbye

```

**Comment by chrisduerr** [comment]
Thanks for testing, that sounds like it's because of our dependency winit not handling this correctly on macOS. Which should also mean that it works on other platforms (I'm not able to reproduce on Linux).

Could you confirm that this is the case by running `cargo run --example window` in the https://github.com/rust-windowing/glutin example? That should also not show any events while the window is not focused, if it really is because of our dependency.

**Comment by nshahan** [comment]
Sorry, I don't currently have a rust development environment setup on this computer. If you know someone else that does and could test they might be able to get you an answer faster.

**Comment by bendem** [comment]
Tried it but I'm getting this when running it:

```
➜  glutin git:(master) RUST_BACKTRACE=1 cargo run --example window
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/examples/window`
Pixel format of the window's GL context: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, double_buffer: true, multisampling: None, srgb: true }
thread 'main' panicked at 'gles2 function was not loaded', /Users/benjamin/projects/github/glutin/target/debug/build/glutin_examples-8be42f69616651ad/out/gl_bindings.rs:1158:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: core::alloc::Layout::repeat
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:408
   6: window::support::gl::missing_fn_panic
             at ./target/debug/build/glutin_examples-8be42f69616651ad/out/gl_bindings.rs:1158
   7: window::support::gl::Gles2::DebugMessageCallback
             at ./target/debug/build/glutin_examples-8be42f69616651ad/out/gl_bindings.rs:2269
   8: window::support::load
             at glutin_examples/examples/support/mod.rs:40
   9: window::main
             at glutin_examples/examples/window.rs:22
  10: std::rt::lang_start::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  12: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:87
  13: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  14: std::rt::lang_start
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
  15: window::main
```

**Comment by chrisduerr** [comment]
Reported upstream in https://github.com/rust-windowing/winit/issues/942.
