### ISSUE TITLE
Freeze and Crash on pasting

### ISSUE THREAD

**Issue by physkets** [alacritty/alacritty#2577]
I am using Archlinux, with Wayland.

I am using Firefox 67.0.4 , with the environment variable: `GDK_BACKEND=wayland`.
Copying from Alacritty and pasting in FF works, but upon copying from FF and pasting in Alacritty, it freezes, and eventually crashes.

```
$ RUST_BACKTRACE=1 alacritty
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: EventsLoopClosed', src/libcore/result.rs:997:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: start_thread
  12: __GI___clone
```

Also, the following is the output when run with `WAYLAND_DEBUG=1`:
```
[1655504.274] wl_keyboard@38.key(14815, 7698312, 47, 1)
[1655504.578] wl_display@1.delete_id(56)
[1655504.654] wl_callback@56.done(14815)
[1655504.768]  -> wl_data_offer@4278190080.receive("text/plain;charset=utf-8", fd 20)
[1655504.830]  -> wl_display@1.sync(new id wl_callback@56)
[1655505.588] wl_display@1.delete_id(56)
[1655505.655] wl_callback@56.done(14815)
[1656089.095]  -> wl_display@1.sync(new id wl_callback@56)
[1656129.494]  -> wl_display@1.sync(new id wl_callback@57)
[1656169.727]  -> wl_display@1.sync(new id wl_callback@58)
[1656209.970]  -> wl_display@1.sync(new id wl_callback@59)
[1656250.303]  -> wl_display@1.sync(new id wl_callback@60)
[1656290.708]  -> wl_display@1.sync(new id wl_callback@61)
[1656331.070]  -> wl_display@1.sync(new id wl_callback@62)
[1656371.356]  -> wl_display@1.sync(new id wl_callback@63)
[1656411.807]  -> wl_display@1.sync(new id wl_callback@64)
[1656452.177]  -> wl_display@1.sync(new id wl_callback@65)
.
.
.
[1669310.421]  -> wl_display@1.sync(new id wl_callback@384)
[1669350.791]  -> wl_display@1.sync(new id wl_callback@385)
[1669391.205]  -> wl_display@1.sync(new id wl_callback@386)
[1669431.559]  -> wl_display@1.sync(new id wl_callback@387)
[1669471.852]  -> wl_display@1.sync(new id wl_callback@388)
[1669512.151]  -> wl_display@1.sync(new id wl_callback@389)
[1669552.399]  -> wl_display@1.sync(new id wl_callback@390)
[1669592.617]  -> wl_display@1.sync(new id wl_callback@391)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: EventsLoopClosed', src/libcore/result.rs:997:5
```
This was first reported in #2453

**Comment by chrisduerr** [comment]
Ping @trimental.

**Comment by trimental** [comment]
@physkets If you could test branch https://github.com/Smithay/smithay-clipboard/tree/roundtrip-before-n-after with
```Diff
diff --git a/Cargo.lock b/Cargo.lock
index 7bdd574..1f7c53e 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -352,7 +352,7 @@ dependencies = [
  "objc-foundation 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)",
  "objc_id 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)",
  "smithay-client-toolkit 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)",
- "smithay-clipboard 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)",
+ "smithay-clipboard 0.3.3 (git+https://github.com/smithay/smithay-clipboard?branch=roundtrip-before-n-after)",
  "wayland-client 0.23.5 (registry+https://github.com/rust-lang/crates.io-index)",
  "x11-clipboard 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)",
 ]
@@ -1924,7 +1924,7 @@ dependencies = [
 [[package]]
 name = "smithay-clipboard"
 version = "0.3.3"
-source = "registry+https://github.com/rust-lang/crates.io-index"
+source = "git+https://github.com/smithay/smithay-clipboard?branch=roundtrip-before-n-after#551624a11c11fb008ad37b29155ae1c3e5af4c1a"
 dependencies = [
  "nix 0.14.1 (registry+https://github.com/rust-lang/crates.io-index)",
  "smithay-client-toolkit 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)",
@@ -2685,7 +2685,7 @@ dependencies = [
 "checksum smallvec 0.6.10 (registry+https://github.com/rust-lang/crates.io-index)" = "ab606a9c5e214920bb66c458cd7be8ef094f813f20fe77a54cc7dbfff220d4b7"
 "checksum smithay-client-toolkit 0.4.6 (registry+https://github.com/rust-lang/crates.io-index)" = "2ccb8c57049b2a34d2cc2b203fa785020ba0129d31920ef0d317430adaf748fa"
 "checksum smithay-client-toolkit 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = "697e927f0315b9505421098a08336a2d46d89d10134b1375b853c6a8ffa95a86"
-"checksum smithay-clipboard 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)" = "d8e61f8a9ef7a15bd38c29b4a39d423776b2d6092723dc7df3f0545ce7a4751e"
+"checksum smithay-clipboard 0.3.3 (git+https://github.com/smithay/smithay-clipboard?branch=roundtrip-before-n-after)" = "<none>"
 "checksum socket2 0.3.9 (registry+https://github.com/rust-lang/crates.io-index)" = "4e626972d3593207547f14bf5fc9efa4d0e7283deb73fef1dff313dae9ab8878"
 "checksum spsc-buffer 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = "be6c3f39c37a4283ee4b43d1311c828f2e1fb0541e76ea0cb1a2abd9ef2f5b3b"
 "checksum stable_deref_trait 1.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = "dba1a27d3efae4351c8051072d619e3ade2820635c3958d826bfea39d59b54c8"
diff --git a/Cargo.toml b/Cargo.toml
index 2e8fd4d..8d1289c 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -14,3 +14,4 @@ incremental = false
 
 [patch.crates-io]
 servo-freetype-sys = { path = "servo-freetype-proxy" }
+smithay-clipboard = { git = "https://github.com/smithay/smithay-clipboard", branch = "roundtrip-before-n-after" }
```
it would be appreciated :)

**Comment by physkets** [comment]
@trimental Do I need to install this in-place of `wl-clipboard`, or alongside it?

**Comment by trimental** [comment]
@physkets smithay-clipboard is a static rust library not a sys lib. You should be able to apply the above git patch to the alacrity source and compile. Although this patch has been tested by someone else and didn’t seem to work.

**Comment by kchibisov** [comment]
Closing due to inability of our clipboard to crash anymore.
