### ISSUE TITLE
Unable to launch alacritty with Fullscreen startup mode on Wayland

### ISSUE THREAD

**Issue by sjug** [alacritty/alacritty#2714]
Which operating system does the issue occur on?
Arch Linux

If on linux, are you using X11 or Wayland?
Wayland

Logs?
```
[sjug@host ~]$ alacritty --version
alacritty 0.3.3
[sjug@host ~]$ alacritty
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[sjug@host ~]$ RUST_BACKTRACE=1 alacritty
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: __libc_start_main
  13: <unknown>
```

**Comment by chrisduerr** [comment]
Are you using an nvidia GPU? To get a useful backtrace it would probably be nice to compile Alacritty from source if possible.

**Comment by sjug** [comment]
I'm using an AMD Vega 64 GPU, do I need to set and debug flags on compile?

**Comment by chrisduerr** [comment]
No, just run it using `RUST_BACKTRACE=1 cargo run` and see if it crashes. That should print all the debug info necessary.

**Comment by sjug** [comment]
That looks better
```
    Finished dev [unoptimized + debuginfo] target(s) in 41.24s
     Running `target/debug/alacritty`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: core::option::Option<T>::unwrap
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:12
  10: winit::platform::platform::wayland::window::Window::get_current_monitor
             at /home/jugs/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.2/src/platform/linux/wayland/window.rs:289
  11: winit::platform::platform::Window::get_current_monitor
             at /home/jugs/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.2/src/platform/linux/mod.rs:357
  12: winit::window::<impl winit::Window>::get_current_monitor
             at /home/jugs/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.2/src/window.rs:412
  13: alacritty_terminal::window::Window::set_fullscreen
             at alacritty_terminal/src/window.rs:388
  14: alacritty_terminal::display::Display::new
             at alacritty_terminal/src/display.rs:245
  15: alacritty::run
             at alacritty/src/main.rs:138
  16: alacritty::main
             at alacritty/src/main.rs:110
  17: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  18: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  20: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  21: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  22: main
  23: __libc_start_main
  24: _start
```

**Comment by kchibisov** [comment]
Would you mind providing some info about your setup, like multiple monitors or smthing like that, and are you running alacritty with default config?

**Comment by chrisduerr** [comment]
Yeah, looking at the error, it seems like you don't have any output connected? It would also be nice if you could test if the examlpes of https://github.com/rust-windowing/glutin crash too. You can run them using `cargo run --example window`.

**Comment by sjug** [comment]
> Would you mind providing some info about your setup, like multiple monitors or smthing like that, and are you running alacritty with default config?
I just have the one monitor connected via HDMI, I'm not running the default config, but it does work fine in xorg. I deleted my custom config and ran it again and it worked fine, it looks like a configuration handling issue.


> Yeah, looking at the error, it seems like you don't have any output connected? It would also be nice if you could test if the examlpes of https://github.com/rust-windowing/glutin crash too. You can run them using `cargo run --example window`.
glutin works fine.

**Comment by chrisduerr** [comment]
That sounds like it was recently fixed upstream. I'd assume that the #2438 also works then?

**Comment by sjug** [comment]
That PR does actually show an error with the config, but it still dies.

```
    Finished dev [unoptimized + debuginfo] target(s) in 1m 02s
     Running `target/debug/alacritty`
Created log file at "/tmp/Alacritty-11913.log"
[2019-08-10 21:53] [ERROR] Problem with config: invalid type: map, expected a string; using default value
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: core::option::Option<T>::unwrap
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:12
  10: winit::platform_impl::platform::wayland::window::Window::current_monitor
             at /home/jugs/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha1/src/platform_impl/linux/wayland/window.rs:344
  11: winit::platform_impl::platform::Window::current_monitor
             at /home/jugs/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha1/src/platform_impl/linux/mod.rs:384
  12: winit::window::Window::current_monitor
             at /home/jugs/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha1/src/window.rs:673
  13: alacritty::window::Window::set_fullscreen
             at alacritty/src/window.rs:375
  14: alacritty::display::Display<glutin::context::PossiblyCurrent>::new
             at alacritty/src/display.rs:265
  15: alacritty::run
             at alacritty/src/main.rs:158
  16: alacritty::main
             at alacritty/src/main.rs:125
  17: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  18: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  20: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  21: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  22: main
  23: __libc_start_main
  24: _start
```

**Comment by kchibisov** [comment]
@sjug What's your `sturtup_mode` in a config, It's `Fullscreen`, right? So try setting it to `Windowed`.

**Comment by chrisduerr** [comment]
Oh yeah, this only seems to crash when executing `current_monitor` which is not done by the examples by default. You'll have to run `cargo run --example fullscreen` in the glutin examples and then press `F` to toggle it to fullscreen. That should crash it, right?

**Comment by sjug** [comment]
> @sjug What's your `sturtup_mode` in a config, It's `Fullscreen`, right? So try setting it to `Windowed` and then toggling fullscreen.

@kchibisov Yes you're right, changing it to windowed allows it to start (and not panic). Then toggling fullscreen works fine.

> Oh yeah, this only seems to crash when executing `current_monitor` which is not done by the examples by default. You'll have to run `cargo run --example fullscreen` in the glutin examples and then press `F` to toggle it to fullscreen. That should crash it, right?

When I run that command it asks me to select a monitor, so I select my only monitor `0`. Then it starts the example in full screen and I can toggle it with `F` back and forth no issue.

**Comment by chrisduerr** [comment]
> @kchibisov Yes you're right, changing it to windowed allows it to start (and not panic). Then toggling fullscreen works fine.

This seems to explain why the example works. Apparently when calling `current_monitor` *too early* it seems to return no outputs for you. But if we call it later it seems to work fine.

If you apply the following diff to glutin master, it might be possible to reproduce the crash:

```diff
diff --git a/glutin_examples/examples/window.rs b/glutin_examples/examples/window.rs
index f7da6c4..cf7beed 100644
--- a/glutin_examples/examples/window.rs
+++ b/glutin_examples/examples/window.rs
@@ -21,6 +21,9 @@ fn main() {
 
     let gl = support::load(&windowed_context.context());
 
+    let current_monitor = windowed_context.window().current_monitor();
+    windowed_context.window().set_fullscreen(Some(current_monitor));
+
     el.run(move |event, _, control_flow| {
         println!("{:?}", event);
         *control_flow = ControlFlow::Wait;
```

You can test after running `git apply <patch_file>` with the `cargo run --example window` command.

**Comment by sjug** [comment]
@chrisduerr Right on

```
     Running `target/debug/examples/window`
Pixel format of the window's GL context: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, double_buffer: true, multisampling: None, srgb: false }
OpenGL version 4.5 (Core Profile) Mesa 19.1.4
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[jugs@trip glutin]$ RUST_BACKTRACE=1 cargo run --example window
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/examples/window`
Pixel format of the window's GL context: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, double_buffer: true, multisampling: None, srgb: false }
OpenGL version 4.5 (Core Profile) Mesa 19.1.4
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: core::option::Option<T>::unwrap
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:12
  10: winit::platform_impl::platform::wayland::window::Window::current_monitor
             at /home/jugs/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha2/src/platform_impl/linux/wayland/window.rs:310
  11: winit::platform_impl::platform::Window::current_monitor
             at /home/jugs/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha2/src/platform_impl/linux/mod.rs:377
  12: winit::window::Window::current_monitor
             at /home/jugs/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha2/src/window.rs:662
  13: window::main
             at glutin_examples/examples/window.rs:24
  14: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  15: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  17: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  18: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  19: main
  20: __libc_start_main
  21: _start
```

**Comment by chrisduerr** [comment]
See https://github.com/rust-windowing/winit/issues/793.

**Comment by kchibisov** [comment]
Just to make it clear, the same issue is relevant under sway. So I guess it's just a general issue here, rather than GNOME specific.

**Comment by shengdichen** [comment]
> Just to make it clear, the same issue is relevant under sway. So I guess it's just a general issue here, rather than GNOME specific.

Can confirm this on Sway `1:1.4-9` (from official Arch Linux repo, running `5.6.13-arch1-1`): launching on any other settings for |`startup_mode`| apart from "`Fullscreen`", i.e., "`Windowed`" OR "`Maximzed`" works just fine.
