### ISSUE TITLE
thread 'main' panicked at 'Failed to call `XGetVisualInfo`

### ISSUE THREAD

**Issue by fox0** [alacritty/alacritty#3298]
Terminal does not start on remote X screen.

### System
OS: Linux Ubuntu 18.04.4 LTS 
Version: alacritty 0.4.1
Linux/BSD: X11
declare -x DISPLAY="192.168.1.1:0"

### Logs
Crashes: STDERR, STDOUT
```
$ RUST_BACKTRACE=full alacritty 
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
thread 'main' panicked at 'Failed to call `XGetVisualInfo`: XError { description: "BadRequest (invalid request code or no such operation)", error_code: 1, request_code: 155, minor_code: 1 }', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x55a6c08aa0bc - <unknown>
   1:     0x55a6c075162d - <unknown>
   2:     0x55a6c08a8c41 - <unknown>
   3:     0x55a6c0895040 - <unknown>
   4:     0x55a6c0894c28 - <unknown>
   5:     0x55a6c089524f - <unknown>
   6:     0x55a6c08956d6 - <unknown>
   7:     0x55a6c074c9c9 - <unknown>
   8:     0x55a6c0750a36 - <unknown>
   9:     0x55a6c077d337 - <unknown>
  10:     0x55a6c055c0ba - <unknown>
  11:     0x55a6c0577cf0 - <unknown>
  12:     0x55a6c0574e31 - <unknown>
  13:     0x55a6c065bae9 - <unknown>
  14:     0x55a6c069a8ed - <unknown>
  15:     0x55a6c0697a9e - <unknown>
  16:     0x55a6c063e3dd - <unknown>
  17:     0x55a6c05f1dbd - <unknown>
  18:     0x55a6c0692583 - <unknown>
  19:     0x55a6c05ed012 - <unknown>
  20:     0x7faeb3673b97 - __libc_start_main
  21:     0x55a6c051f12a - <unknown>
  22:                0x0 - <unknown>
```
Font/Terminal size: 
```
$ alacritty -vv
Created log file at "/tmp/Alacritty-21526.log"
[2020-02-06 12:13] [INFO] Welcome to Alacritty
[2020-02-06 12:13] [DEBUG] Estimated DPR: 1
[2020-02-06 12:13] [DEBUG] Estimated Cell Size: 9 x 17
[2020-02-06 12:13] [DEBUG] Estimated Dimensions: None
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
thread 'main' panicked at 'Failed to call `XGetVisualInfo`: XError { description: "BadRequest (invalid request code or no such operation)", error_code: 1, request_code: 155, minor_code: 1 }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
Keyboard and bindings:
```
$ alacritty --print-events
Created log file at "/tmp/Alacritty-21531.log"
[2020-02-06 12:14] [INFO] Welcome to Alacritty
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
thread 'main' panicked at 'Failed to call `XGetVisualInfo`: XError { description: "BadRequest (invalid request code or no such operation)", error_code: 1, request_code: 155, minor_code: 1 }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by chrisduerr** [comment]
Does this work when starting Alacritty on the remote system and then later connecting to it?

I'm pretty sure we've had an issue about this before, but I can't seem to find it.

**Comment by fox0** [comment]
Sorry, I did not understand your question. The application tries to start on the local machine, just the display is remote.

```DISPLAY=:0 alacritty```
All ok.

```DISPLAY=192.168.1.1:0 alacritty```
Crash.

**Comment by fox0** [comment]
Remote display exists, other applications work. For example:
```DISPLAY=192.168.1.1:0 xfce4-terminal```

**Comment by chrisduerr** [comment]
I'm asking if the problem is just with launching on a remote display, or if there also are problems when you connect to an existing remote X session which already has Alacritty running.

**Comment by fox0** [comment]
I'm afraid this is not the remote X session. Window is displayed on remote X display. See https://askubuntu.com/a/207189 (Variant A - Shooting X Windows to another DISPLAY).

A running application cannot change the display. Therefore, the application on the local display works (`DISPLAY=:0 alacritty`).

**Comment by chrisduerr** [comment]
Can you run `glxgears` over a remote X session?

**Comment by kchibisov** [comment]
You need DRI to make it work, we’re OpenGL 3.3 app, so it could be tricky to make things work with your setup. You should compare us to other OpenGL 3.0+ apps here, and not to software rendering softwate.

It could be permission issue according to your log. 

>libEGL warning: DRI2: failed to authenticate

**Comment by fox0** [comment]
```
$ DISPLAY=192.168.1.1:0 glxgears 
Error: couldn't get an RGB, Double-buffered visual
```
