### ISSUE TITLE
Index out of bounds panic when highlighting.

### ISSUE THREAD

**Issue by tjnitram** [alacritty/alacritty#3446]
It seems like a regression of #3233. Reproduce it by clicking and dragging inside the window and releasing outside the window, but only if the cursor is above and to the right of the starting position.

After bisecting, it looks like 6832b86aa7a9adb386394e1caaf373e65297be4e is the culprit.

### System
OS: Linux
Version: alacritty 0.4.2-dev (bb0a214)
Linux/BSD: Wayland/Sway

### Logs

```
thread 'main' panicked at 'index out of bounds: the len is 105 but the index is 105', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/slice/mod.rs:2806:10
stack backtrace:
   0:     0x5583769f74d4 - backtrace::backtrace::libunwind::trace::he25250f78ba1020d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x5583769f74d4 - backtrace::backtrace::trace_unsynchronized::hd7e25f35da233a1e
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x5583769f74d4 - std::sys_common::backtrace::_print_fmt::h5578a566a4c2ae4e
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x5583769f74d4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4f87054ec86e936
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x558376a1e88c - core::fmt::write::h393d55821fa8e2cb
                               at src/libcore/fmt/mod.rs:1025
   5:     0x5583769f40c7 - std::io::Write::write_fmt::hc6645302c23e4504
                               at src/libstd/io/mod.rs:1426
   6:     0x5583769f97ce - std::sys_common::backtrace::_print::he8a0a3ebec70e1d6
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x5583769f97ce - std::sys_common::backtrace::print::hc2635fd6c7743ade
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x5583769f97ce - std::panicking::default_hook::{{closure}}::h9849388798b72b2b
                               at src/libstd/panicking.rs:193
   9:     0x5583769f94c1 - std::panicking::default_hook::h66e3afff11b02e47
                               at src/libstd/panicking.rs:210
  10:     0x5583769f9eab - std::panicking::rust_panic_with_hook::hf6d05969fcffff03
                               at src/libstd/panicking.rs:471
  11:     0x5583769f9a5e - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x558376a1ac3e - core::panicking::panic_fmt::he794217b0df3f806
                               at src/libcore/panicking.rs:84
  13:     0x558376a1ac05 - core::panicking::panic_bounds_check::ha320684dc0fd21e4
                               at src/libcore/panicking.rs:62
  14:     0x558376422d37 - <usize as core::slice::SliceIndex<[T]>>::index::h9a418357440600f2
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/slice/mod.rs:2806
  15:     0x55837641bbc8 - core::slice::<impl core::ops::index::Index<I> for [T]>::index::h009d01a722862def
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/slice/mod.rs:2657
  16:     0x55837642936b - <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index::h9efae8ea21296d55
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/liballoc/vec.rs:1871
  17:     0x55837640f841 - <alacritty_terminal::grid::row::Row<T> as core::ops::index::Index<alacritty_terminal::index::Column>>::index::h56b7f751864926eb
                               at alacritty_terminal/src/grid/row.rs:184
  18:     0x558375e68418 - alacritty_terminal::term::Term<T>::line_to_string::hcd1799424544a60e
                               at /home/tom/src/alacritty/alacritty_terminal/src/term/mod.rs:1017
  19:     0x558375e69062 - alacritty_terminal::term::Term<T>::bounds_to_string::hf2d722a1a22b15a8
                               at /home/tom/src/alacritty/alacritty_terminal/src/term/mod.rs:998
  20:     0x558375e697ee - alacritty_terminal::term::Term<T>::selection_to_string::ha8f0c43654ae4f2e
                               at /home/tom/src/alacritty/alacritty_terminal/src/term/mod.rs:984
  21:     0x558375ed5550 - <alacritty::event::ActionContext<N,T> as alacritty::input::ActionContext<T>>::copy_selection::h348713f4efc7c375
                               at alacritty/src/event.rs:98
  22:     0x558375e45541 - alacritty::input::Processor<T,A>::copy_selection::h14d534540ea508e5
                               at alacritty/src/input.rs:722
  23:     0x558375e4301a - alacritty::input::Processor<T,A>::on_mouse_release::hcf1054f6c97d4950
                               at alacritty/src/input.rs:446
  24:     0x558375e446bc - alacritty::input::Processor<T,A>::mouse_input::h51f20d6c25ab3a3f
                               at alacritty/src/input.rs:586
  25:     0x558375ed865a - alacritty::event::Processor<N>::handle_event::h035ed1f8ff095582
                               at alacritty/src/event.rs:553
  26:     0x558375ed7b29 - alacritty::event::Processor<N>::run::{{closure}}::h2ec86c80b7485994
                               at alacritty/src/event.rs:423
  27:     0x558375d3d88d - winit::platform_impl::platform::sticky_exit_callback::he781859785474044
                               at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/mod.rs:697
  28:     0x558375cf3991 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return::h1537d289b108de40
                               at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/wayland/event_loop.rs:527
  29:     0x558375d3c82d - winit::platform_impl::platform::EventLoop<T>::run_return::h339f35ded9981b53
                               at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/mod.rs:633
  30:     0x558375cb2e05 - <winit::event_loop::EventLoop<T> as winit::platform::desktop::EventLoopExtDesktop>::run_return::he39b9718045b2846
                               at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform/desktop.rs:51
  31:     0x558375ed6b9b - alacritty::event::Processor<N>::run::ha5d100ccbfe7d8b6
                               at alacritty/src/event.rs:356
  32:     0x558375cf1f55 - alacritty::run::h6895cfcbce406cd8
                               at alacritty/src/main.rs:206
  33:     0x558375cf090b - alacritty::main::h3464407a4b55797c
                               at alacritty/src/main.rs:112
  34:     0x558375ebef20 - std::rt::lang_start::{{closure}}::ha5f115a6c0114bd5
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  35:     0x5583769f98f3 - std::rt::lang_start_internal::{{closure}}::h4aedff5d9863b36b
                               at src/libstd/rt.rs:52
  36:     0x5583769f98f3 - std::panicking::try::do_call::h0630fe3da32a089b
                               at src/libstd/panicking.rs:292
  37:     0x558376a0290a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  38:     0x5583769fa340 - std::panicking::try::hdfbe2fd873ac646c
                               at src/libstd/panicking.rs:270
  39:     0x5583769fa340 - std::panic::catch_unwind::hd7a9c10fa2bee1bc
                               at src/libstd/panic.rs:394
  40:     0x5583769fa340 - std::rt::lang_start_internal::hb8081e0e7e42ac0d
                               at src/libstd/rt.rs:51
  41:     0x558375ebeef9 - std::rt::lang_start::h8ffbbc372f2f8095
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  42:     0x558375cf251a - main
  43:     0x7f2029819023 - __libc_start_main
  44:     0x558375c8919e - _start
  45:                0x0 - <unknown>
```

**Comment by tjnitram** [comment]
Thank you!
