### ISSUE TITLE
Wayland/Ubuntu 20.04 - thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', 

### ISSUE THREAD

**Issue by tomscytale** [alacritty/alacritty#3683]
Issue does not appear with X11

### System

alacritty 0.5.0-dev (04f0bca)
Ubuntu 20.04 / Wayland / Gnome

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

```
19:38 $ RUST_BACKTRACE=full target/release/alacritty
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.1/src/platform_impl/linux/wayland/window.rs:393:22
stack backtrace:
   0:     0x557ecce20a9d - backtrace::backtrace::libunwind::trace::h5ae3454ebe40b621
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x557ecce20a9d - backtrace::backtrace::trace_unsynchronized::hbf6f267a483fb2c0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x557ecce20a9d - std::sys_common::backtrace::_print_fmt::h37755015d94b9085
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x557ecce20a9d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0561c8cd3569b40d
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x557eccced05c - core::fmt::write::h86a597a35d48a212
                               at src/libcore/fmt/mod.rs:1063
   5:     0x557ecce201f1 - std::io::Write::write_fmt::h73d9dc0f29eefe48
                               at src/libstd/io/mod.rs:1426
   6:     0x557ecce1fd55 - std::sys_common::backtrace::_print::h6c60c5ee09af0233
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x557ecce1fd55 - std::sys_common::backtrace::print::hf9d1db01634f9b2a
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x557ecce1fd55 - std::panicking::default_hook::{{closure}}::h1db9298dd213ae95
                               at src/libstd/panicking.rs:204
   9:     0x557ecce1f2ea - std::panicking::default_hook::h3272faf6cc91fd2e
                               at src/libstd/panicking.rs:224
  10:     0x557ecce1f2ea - std::panicking::rust_panic_with_hook::hb976084785e50594
                               at src/libstd/panicking.rs:470
  11:     0x557ecce1ee88 - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:     0x557eccceab60 - core::panicking::panic_fmt::h45f7d6868edb5678
                               at src/libcore/panicking.rs:85
  13:     0x557ecccea97c - core::panicking::panic::h0fd4184f909d9498
                               at src/libcore/panicking.rs:52
  14:     0x557ecceb6711 - core::option::Option<T>::unwrap::h880575213c9ade7f
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/macros/mod.rs:10
  15:     0x557ecceb6711 - winit::platform_impl::platform::wayland::window::Window::current_monitor::h88b689c0d3fbfe7c
                               at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.1/src/platform_impl/linux/wayland/window.rs:393
  16:     0x557eccbdc0dd - winit::platform_impl::platform::Window::current_monitor::h52b1080c78c40fe3
                               at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.1/src/platform_impl/linux/mod.rs:441
  17:     0x557eccbdc0dd - winit::window::Window::current_monitor::h982916ccb061712c
                               at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.1/src/window.rs:756
  18:     0x557eccbdc0dd - alacritty::window::Window::set_fullscreen::hf3ba196456c224b7
                               at alacritty/src/window.rs:393
  19:     0x557eccbbf7e7 - alacritty::display::Display::new::h1d9226e093409b23
                               at alacritty/src/display.rs:255
  20:     0x557eccc71f30 - alacritty::run::h8a18d83454ed2863
                               at alacritty/src/main.rs:148
  21:     0x557eccc71f30 - alacritty::main::h48a68241a29fcbc6
                               at alacritty/src/main.rs:115
  22:     0x557eccc11eb3 - std::rt::lang_start::{{closure}}::hfb1dddfe65729e9d
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  23:     0x557eccc6daf3 - main
  24:     0x7f83156000b3 - __libc_start_main
  25:     0x557eccac819e - _start
  26:                0x0 - <unknown>

19:39 $ git log -1
commit 04f0bcaf54ed373128ca0f84ee8fcdd8e52bce23 (HEAD -> master, origin/master, origin/HEAD)
Author: Kirill Chibisov <contact@kchibisov.com>
Date:   Mon May 4 02:29:11 2020 +0300
    Use frame callbacks instead of vsync on Wayland


19:40 $ ./target/release/alacritty -vv
Created log file at "/tmp/Alacritty-761666.log"
[2020-05-04 19:42:05.507663290] [INFO] Welcome to Alacritty
[2020-05-04 19:42:05.507764305] [INFO] Configuration loaded from "/home/tom/.alacritty.yml"
[2020-05-04 19:42:05.540342695] [DEBUG] Estimated DPR: 1
[2020-05-04 19:42:05.540387467] [DEBUG] Estimated Cell Size: 7 x 14
[2020-05-04 19:42:05.540415529] [DEBUG] Estimated Dimensions: None
[2020-05-04 19:42:05.589497764] [INFO] Device pixel ratio: 1
[2020-05-04 19:42:05.596122801] [INFO] Initializing glyph cache...
[2020-05-04 19:42:05.678563348] [INFO] ... finished initializing glyph cache in 0.082391877s
[2020-05-04 19:42:05.678618862] [INFO] Cell Size: 7 x 14
[2020-05-04 19:42:05.678637006] [INFO] Padding: 0 x 0
[2020-05-04 19:42:05.678654146] [INFO] Width: 800, Height: 600
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.1/src/platform_impl/linux/wayland/window.rs:393:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 
19:42 $ ./target/release/alacritty --print-events
Created log file at "/tmp/Alacritty-761987.log"
[2020-05-04 19:42:16.760583238] [INFO] Welcome to Alacritty
[2020-05-04 19:42:16.760716389] [INFO] Configuration loaded from "/home/tom/.alacritty.yml"
[2020-05-04 19:42:16.842686741] [INFO] Device pixel ratio: 1
[2020-05-04 19:42:16.849393969] [INFO] Initializing glyph cache...
[2020-05-04 19:42:16.934334825] [INFO] ... finished initializing glyph cache in 0.084880146s
[2020-05-04 19:42:16.934404826] [INFO] Cell Size: 7 x 14
[2020-05-04 19:42:16.934434657] [INFO] Padding: 0 x 0
[2020-05-04 19:42:16.934459453] [INFO] Width: 800, Height: 600
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.1/src/platform_impl/linux/wayland/window.rs:393:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


19:44 $ cat /tmp/Alacritty-761987.log
[2020-05-04 19:42:16.760583238] [INFO] Welcome to Alacritty
[2020-05-04 19:42:16.760716389] [INFO] Configuration loaded from "/home/tom/.alacritty.yml"
[2020-05-04 19:42:16.842686741] [INFO] Device pixel ratio: 1
[2020-05-04 19:42:16.849393969] [INFO] Initializing glyph cache...
[2020-05-04 19:42:16.934334825] [INFO] ... finished initializing glyph cache in 0.084880146s
[2020-05-04 19:42:16.934404826] [INFO] Cell Size: 7 x 14
[2020-05-04 19:42:16.934434657] [INFO] Padding: 0 x 0
[2020-05-04 19:42:16.934459453] [INFO] Width: 800, Height: 600

```

**Comment by chrisduerr** [comment]
Do you have at least one output connected?

**Comment by kchibisov** [comment]
Does it crash before this commit?

**Comment by kchibisov** [comment]
Oh, what's your `startup_mode` in alacritty.yml?

**Comment by tomscytale** [comment]
> Oh, what's your startup_mode in alacritty.yml?

`Fullscreen` - if I comment this line out alacritty starts without a problem

> Does it crash before this commit?

yes - I just tried with current HEAD^ - a425fe6bfe734bb80dce334d6f1c53e0bd41c0db - Fix scrolling multiplier documentation
and with 74039bde1249ad77fe8d2d85ec6eb1f363f5c511 (from Feb 3)

both crash

I'll try find a commit that doesn't exhibit the bug

> Do you have at least one output connected?

sorry, can you clarify? I'm not running headless if that's what you mean.

**Comment by kchibisov** [comment]
Ah, it's not regression, it's a quite old our problem on Wayland.

#2714
