### ISSUE TITLE
ToggleFullscreen doesn't work the first time and does not shrink resolution when going back to windowed mode

### ISSUE THREAD

**Issue by Soveu** [alacritty/alacritty#3831]
1. Using ToggleFullscreen to switch from windowed to fullscreen mode doesn't work at first time (another 2x ToggleFullscreens are needed)
2. Toggling between windowed and fullscreen mode does not toggle the size of terminal window (it stays at fullscreen resolution)

### Reproduction
Set `ToggleFullscreen` to F11
Set `decorations` to `none`
Run alacritty
Use F11 to toggle fullscreen

### Effects
1. When toggling into fullscreen for first time, resolution is set to 1920x1050
2. When toggling back into windowed mode, resolution does not go back to the previous windowed resolution

### Expected
1. Toggling into fullscreen sets resolution to 1920x1080
2. Toggling back into windowed mode sets resolution back to resolution before fullscreen mode

### System

OS: Fedora 32
Version: 0.4.3
Wayland, no custom compositor/WM, GNOME environment

### Logs

`alacritty -vv`
```
[2020-06-07 14:31:36.396907698] [INFO] Welcome to Alacritty
[2020-06-07 14:31:36.397022444] [INFO] Configuration loaded from "/home/soveu/.config/alacritty/alacritty.yml"
[2020-06-07 14:31:36.413616963] [DEBUG] Estimated DPR: 1
[2020-06-07 14:31:36.413661116] [DEBUG] Estimated Cell Size: 8 x 17
[2020-06-07 14:31:36.413669552] [DEBUG] Estimated Dimensions: None
[2020-06-07 14:31:36.497734656] [INFO] Device pixel ratio: 1
[2020-06-07 14:31:36.502912687] [INFO] Initializing glyph cache...
[2020-06-07 14:31:36.528523650] [INFO] ... finished initializing glyph cache in 0.025571679s
[2020-06-07 14:31:36.528557894] [INFO] Cell Size: 8 x 17
[2020-06-07 14:31:36.528564737] [INFO] Padding: 0 x 0
[2020-06-07 14:31:36.528574896] [INFO] Width: 800, Height: 600
[2020-06-07 14:31:36.530471645] [INFO] PTY Dimensions: Line(35) x Column(100)
[2020-06-07 14:31:36.534140277] [INFO] Initialisation complete
[2020-06-07 14:31:36.555039064] [DEBUG] [unhandled osc_dispatch]: [['7',],['f','i','l','e',':','/','/','l','o','c','a','l','h','o','s','t','.','l','o','c','a','l','d','o','m','a','i','n','/','h','o','m','e','/','s','o','v','e','u','/','g','i','t','/','d','o','t','f','i','l','e','s','/','a','l','a','c','r','i','t','t','y',],] at line 759
[2020-06-07 14:31:36.586621721] [DEBUG] New num_cols is 100 and num_lines is 33
[2020-06-07 14:31:36.586668229] [INFO] Width: 800, Height: 570
[2020-06-07 14:31:46.797186779] [DEBUG] New num_cols is 240 and num_lines is 61
[2020-06-07 14:31:46.800056978] [INFO] Width: 1920, Height: 1050
[2020-06-07 14:31:48.496441563] [DEBUG] New num_cols is 240 and num_lines is 63
[2020-06-07 14:31:48.502123673] [INFO] Width: 1920, Height: 1080
[2020-06-07 14:31:51.753686932] [INFO] Goodbye
```

**Comment by chrisduerr** [comment]
I've got a couple of questions wrt to this bug:
 - Does this happen only with decorations set to `none`?
 - What's your `startup_mode` in the config? Windowed?
 - Does this same issue happen when running XWayland?

**Comment by Soveu** [comment]
* Sorry, decorations is set to `full` and this bug does not happen on `none`
* Yes, `startup_mode` is `Windowed`
* Both on GNOME on Xorg and XWayland this issue does not appear

Also one thing I have noticed
On Wayland the title bar is plain white rectangle (with minimize, maximize and close buttons), while on Xorg/XWayland the bar looks the same as in other programs

**Comment by chrisduerr** [comment]
>  On Wayland the title bar is plain white rectangle (with minimize, maximize and close buttons), while on Xorg/XWayland the bar looks the same as in other programs

That's intended, it's due to GNOME Wayland not having server-side decorations.

> Sorry, decorations is set to full and this bug does not happen on none

This applies to both issues, right?

I've submitted an issue upstream in https://github.com/rust-windowing/winit/issues/1601.

**Comment by Soveu** [comment]
Yes, this applies to both issues

**Comment by Soveu** [comment]
ToggleFullscreen also does not bring back the decorations when toggling back to windowed mode

**Comment by Soveu** [comment]
Fiddling with ToggleFullscreen (going fullscreen, then windowed, resizing and going fullscreen again) crashes the terminal
```
soveu@localhost ~> alacritty 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /builddir/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/wayland/window.rs:398:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
soveu@localhost ~ [101]> alacritty --version
alacritty 0.4.3
```

**Comment by Soveu** [comment]
Looks like ToggleFullscreen always leaves a gap at the bottom of screen when going from windowed with decorations to fullscreen

**Comment by Soveu** [comment]
I'll try to build alacritty from source and paste the backtrace here

**Comment by Soveu** [comment]
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/soveu/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/wayland/window.rs:398:22
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::panicking::panic
             at src/libcore/panicking.rs:56
  14: core::option::Option<T>::unwrap
             at /home/soveu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/macros/mod.rs:10
  15: winit::platform_impl::platform::wayland::window::Window::current_monitor
             at /home/soveu/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/wayland/window.rs:398
  16: winit::platform_impl::platform::Window::current_monitor
             at /home/soveu/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:441
  17: winit::window::Window::current_monitor
             at /home/soveu/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/window.rs:756
  18: alacritty::window::Window::set_fullscreen
             at alacritty/src/window.rs:373
  19: alacritty::window::Window::toggle_fullscreen
             at alacritty/src/window.rs:363
  20: <alacritty::config::bindings::Action as alacritty::input::Execute<T>>::execute
             at alacritty/src/input.rs:175
  21: <alacritty::config::bindings::Binding<T> as alacritty::input::Execute<U>>::execute
             at alacritty/src/input.rs:94
  22: alacritty::input::Processor<T,A>::process_key_bindings
             at alacritty/src/input.rs:774
  23: alacritty::input::Processor<T,A>::key_input
             at alacritty/src/input.rs:698
  24: alacritty::event::Processor<N>::handle_event
             at alacritty/src/event.rs:615
  25: alacritty::event::Processor<N>::run::{{closure}}
             at alacritty/src/event.rs:503
  26: winit::platform_impl::platform::sticky_exit_callback
             at /home/soveu/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:698
  27: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return
             at /home/soveu/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/wayland/event_loop.rs:537
  28: winit::platform_impl::platform::EventLoop<T>::run_return
             at /home/soveu/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:634
  29: <winit::event_loop::EventLoop<T> as winit::platform::desktop::EventLoopExtDesktop>::run_return
             at /home/soveu/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform/desktop.rs:51
  30: alacritty::event::Processor<N>::run
             at alacritty/src/event.rs:435
  31: alacritty::run
             at alacritty/src/main.rs:190
  32: alacritty::main
             at alacritty/src/main.rs:102
  33: std::rt::lang_start::{{closure}}
             at /home/soveu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  34: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  35: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  36: std::panicking::try
             at src/libstd/panicking.rs:274
  37: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  38: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  39: std::rt::lang_start
             at /home/soveu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  40: main
  41: __libc_start_main
  42: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by kaimast** [comment]
I noticed that snapping (not sure if that is the right term) the window to one side of my desktop does not resize the render buffer either. Manually resizing window by dragging its border fixes it.

This might be the same bug as this problem?

**Comment by kaimast** [comment]
> Looks like ToggleFullscreen always leaves a gap at the bottom of screen when going from windowed with decorations to fullscreen

This is most likely this winit bug: https://github.com/rust-windowing/winit/issues/1509

**Comment by Soveu** [comment]
> I noticed that snapping (not sure if that is the right term) the window to one side of my desktop does not resize the render buffer either. Manually resizing window by dragging its border fixes it.
> 
> This might be the same bug as this problem?

Exactly

**Comment by Vorsplummi** [comment]
Thank you so much for fixing this.
