### ISSUE TITLE
Portable builds for Windows are broken

### ISSUE THREAD

**Issue by ofek** [alacritty/alacritty#3853]
### Note

I noticed that the panic shows the absolute file paths of where it was built (on Travis) rather than relative file paths. Is that normal? This can also be seen in the logs of https://github.com/alacritty/alacritty/issues/3566

### System

OS: Windows
Windows: ConPTY

### Logs

```
ofek@OZONE C:\Users\ofek\Desktop
$ alacritty -v

ofek@OZONE C:\Users\ofek\Desktop
$ Created log file at "C:\Users\ofek\AppData\Local\Temp\Alacritty-108.log"
[2020-06-15 18:47:38.402286400] [WARN] Config scrolling.auto_scroll has been removed and is now always disabled, it can be safely removed from the config
[2020-06-15 18:47:38.403281000] [INFO] Welcome to Alacritty
[2020-06-15 18:47:38.404276300] [INFO] Configuration loaded from "C:\Users\ofek\AppData\Roaming\alacritty\alacritty.yml"
[2020-06-15 18:47:38.795253800] [INFO] Device pixel ratio: 2
[2020-06-15 18:47:38.798253800] [INFO] Initializing glyph cache...
[2020-06-15 18:47:38.800252000] [INFO] ... finished initializing glyph cache in 0.0024518s
[2020-06-15 18:47:38.800252000] [INFO] Estimated DPR correctly, skipping resize
[2020-06-15 18:47:38.800252000] [INFO] Cell Size: 17 x 37
[2020-06-15 18:47:38.801251700] [INFO] Padding: 0 x 0
[2020-06-15 18:47:38.801251700] [INFO] Width: 3825, Height: 1628
[2020-06-15 18:47:38.821250700] [INFO] PTY Dimensions: Line(44) x Column(225)
panicked at 'Unable to spawn shell: The system cannot find the file specified. (os error 2)', alacritty_terminal\src\tty\windows\conpty.rs:247:5
panicked at 'either event handler is re-entrant (likely), or no event handler is registered (very unlikely)', C:\Users\travis\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:235:37
thread panicked while processing panic. aborting.
```

![Capture](https://user-images.githubusercontent.com/9677399/84713553-42fb8d00-af39-11ea-8d4b-b62fe29f8fa7.PNG)

**Comment by chrisduerr** [comment]
Yes it is. You do not have these files on your system locally, there's nothing to reference. The files depend on the sources at build time.

**Comment by ofek** [comment]
@chrisduerr Buddy 😄 The first part is just a note, this is a real issue

**Comment by chrisduerr** [comment]
> panicked at 'Unable to spawn shell: The system cannot find the file specified. (os error 2)'

This error should be sufficient to fix your problem? The shell program you're using doesn't exist. If you're using the default config, maybe try cmd.exe. Make sure to run an up to date version of Windows 10.

**Comment by ofek** [comment]
Thanks!
