### ISSUE TITLE
thread 'main' panicked at 'loading icon: Decoding(DecodingError 

### ISSUE THREAD

**Issue by jonschoning** [alacritty/alacritty#4064]
```
$ alacritty --version                                                                                                                ✘
alacritty 0.6.0-dev (5c8aa67)

$ lsb_release -a                                                                                                                     ✘
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

$ cargo install --git https://github.com/alacritty/alacritty                                                                         
    Updating git repository `https://github.com/alacritty/alacritty`
     Ignored package `alacritty v0.6.0-dev (https://github.com/alacritty/alacritty#5c8aa679)` is already installed, use --force to override

$ RUST_BACKTRACE=full alacritty                             
thread 'main' panicked at 'loading icon: Decoding(DecodingError { format: Exact(Ico), underlying: Some(IcoEntryTooManyPlanesOrHotspot) })', alacritty/src/window.rs:253:14
stack backtrace:
   0:     0x557c7abde9af - backtrace::backtrace::libunwind::trace::h75aedf5f78e5147f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x557c7abde9af - backtrace::backtrace::trace_unsynchronized::h18fb73c9ac9ae753
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x557c7abde9af - std::sys_common::backtrace::_print_fmt::h65f97470ff13ec84
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x557c7abde9af - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hee061c54ddc9f024
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x557c7aaceb2c - core::fmt::write::hfbd2baad61ed21a8
                               at src/libcore/fmt/mod.rs:1117
   5:     0x557c7abde196 - std::io::Write::write_fmt::h72f9bd227f40dc62
                               at src/libstd/io/mod.rs:1508
   6:     0x557c7abddb30 - std::sys_common::backtrace::_print::h2d2cd8fe02feb5fa
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x557c7abddb30 - std::sys_common::backtrace::print::h801b12991252ba7c
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x557c7abddb30 - std::panicking::default_hook::{{closure}}::h25fc1fbf3b63b5c8
                               at src/libstd/panicking.rs:198
   9:     0x557c7abdd1f2 - std::panicking::default_hook::h62c897957a5e0f26
                               at src/libstd/panicking.rs:217
  10:     0x557c7abdd1f2 - std::panicking::rust_panic_with_hook::hb8a276f163c59810
                               at src/libstd/panicking.rs:526
  11:     0x557c7abdce38 - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  12:     0x557c7aacc420 - core::panicking::panic_fmt::h9cc57011b345cfad
                               at src/libcore/panicking.rs:85
  13:     0x557c7aad2f32 - core::option::expect_none_failed::h10abb5a6aef32df8
                               at src/libcore/option.rs:1273
  14:     0x557c7aa0b560 - core::result::Result<T,E>::expect::hab0cc5c8920e1898
                               at /home/jon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:963
  15:     0x557c7aa0b560 - alacritty::window::Window::get_platform_window::h27418a22dc58e523
                               at alacritty/src/window.rs:252
  16:     0x557c7aa0b560 - alacritty::window::Window::new::hb28ba8380df70748
                               at alacritty/src/window.rs:156
  17:     0x557c7a9a75e4 - alacritty::display::Display::new::hc18353d720cad920
                               at alacritty/src/display.rs:200
  18:     0x557c7a96f458 - alacritty::run::h19178cd0536d6817
                               at alacritty/src/main.rs:137
  19:     0x557c7a96f458 - alacritty::main::h7459d27e931df962
                               at alacritty/src/main.rs:104
  20:     0x557c7abf24f3 - std::rt::lang_start::{{closure}}::hcd6bb7fc0cfddfd0
                               at /home/jon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  21:     0x557c7abf24f3 - std::rt::lang_start_internal::{{closure}}::{{closure}}::hcc8955fe0260079a
                               at src/libstd/rt.rs:52
  22:     0x557c7abf24f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2d911168353e93cc
                               at src/libstd/sys_common/backtrace.rs:130
  23:     0x557c7a96af78 - main
  24:     0x7f3fb45710b3 - __libc_start_main
  25:     0x557c7a8d61ae - _start
  26:                0x0 - <unknown>

```

**Comment by chrisduerr** [comment]
Does `cargo install alacritty` work?

**Comment by jonschoning** [comment]
yes, `cargo install alacritty` does work

**Comment by chrisduerr** [comment]
Can you confirm that https://github.com/alacritty/alacritty/commit/9167461eb35687872a7670b2e7105a56244f7a48 broke this? You should be able to repro by just cloning and building these.

**Comment by jonschoning** [comment]
```
$ cargo build --release
   
    Finished release [optimized + debuginfo] target(s) in 5m 00s

$ ./target/release/alacritty --version  
alacritty 0.6.0-dev (bfdfe2b)


 $ RUST_BACKTRACE=full ./target/release/alacritty                                                                                   
thread 'main' panicked at 'loading icon: Decoding(DecodingError { format: Exact(Ico), underlying: Some(IcoEntryTooManyPlanesOrHotspot) })', alacritty/src/window.rs:253:14
stack backtrace:
   0:     0x55ed52a4d39f - backtrace::backtrace::libunwind::trace::h75aedf5f78e5147f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55ed52a4d39f - backtrace::backtrace::trace_unsynchronized::h18fb73c9ac9ae753
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55ed52a4d39f - std::sys_common::backtrace::_print_fmt::h65f97470ff13ec84
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55ed52a4d39f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hee061c54ddc9f024
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55ed5293d66c - core::fmt::write::hfbd2baad61ed21a8
                               at src/libcore/fmt/mod.rs:1117
   5:     0x55ed52a4cb96 - std::io::Write::write_fmt::h72f9bd227f40dc62
                               at src/libstd/io/mod.rs:1508
   6:     0x55ed52a4c580 - std::sys_common::backtrace::_print::h2d2cd8fe02feb5fa
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55ed52a4c580 - std::sys_common::backtrace::print::h801b12991252ba7c
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55ed52a4c580 - std::panicking::default_hook::{{closure}}::h25fc1fbf3b63b5c8
                               at src/libstd/panicking.rs:198
   9:     0x55ed52a4bc42 - std::panicking::default_hook::h62c897957a5e0f26
                               at src/libstd/panicking.rs:217
  10:     0x55ed52a4bc42 - std::panicking::rust_panic_with_hook::hb8a276f163c59810
                               at src/libstd/panicking.rs:526
  11:     0x55ed52a4b888 - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  12:     0x55ed5293af60 - core::panicking::panic_fmt::h9cc57011b345cfad
                               at src/libcore/panicking.rs:85
  13:     0x55ed52941a52 - core::option::expect_none_failed::h10abb5a6aef32df8
                               at src/libcore/option.rs:1273
  14:     0x55ed5277d030 - core::result::Result<T,E>::expect::h8358b10575978cc7
                               at /home/jon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:963
  15:     0x55ed5277d030 - alacritty::window::Window::get_platform_window::hef939d7255fadcac
                               at alacritty/src/window.rs:252
  16:     0x55ed5277d030 - alacritty::window::Window::new::hcb68074397d8230e
                               at alacritty/src/window.rs:156
  17:     0x55ed528413c8 - alacritty::display::Display::new::hb1c5a00e6a2f7aff
                               at alacritty/src/display.rs:200
  18:     0x55ed528081a8 - alacritty::run::h466d505526f85e98
                               at alacritty/src/main.rs:137
  19:     0x55ed528081a8 - alacritty::main::hf1a67cd70727f676
                               at alacritty/src/main.rs:104
  20:     0x55ed52a60d63 - std::rt::lang_start::{{closure}}::h3d004097a672b5bb
                               at /home/jon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  21:     0x55ed52a60d63 - std::rt::lang_start_internal::{{closure}}::{{closure}}::hcc8955fe0260079a
                               at src/libstd/rt.rs:52
  22:     0x55ed52a60d63 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2d911168353e93cc
                               at src/libstd/sys_common/backtrace.rs:130
  23:     0x55ed52803b88 - main
  24:     0x7fb12a9810b3 - __libc_start_main
  25:     0x55ed5273e1ae - _start
  26:                0x0 - <unknown>
```

**Comment by chrisduerr** [comment]
@jonschoning That's just the latest commit. Could you confirm that the commit I've posted is the first one that break it, by testing that one and its parent?

**Comment by jonschoning** [comment]
9167461 crash
d192720 no crash

**Comment by chrisduerr** [comment]
That's what I wanted to know, thanks. Looks like symlinks are not working properly. Are you on a native Ubuntu install, running on ext4?

**Comment by jonschoning** [comment]
yes, native ubuntu, the root filesystem is ext4, which is itself running under LVM

**Comment by chrisduerr** [comment]
If you open the `alacritty/alacritty.ico` file in an image viewer, does it actually show up as an image? Like `feh alacritty/alacritty.ico`.

It looks like it's not following the symlink, but on Ubuntu that doesn't make much sense.

**Comment by jonschoning** [comment]
ah, i see.
I had in my `.gitconfig`
```
[core]
  symlinks = false
```
so the `alacritty/alacritty.ico` was just a text file.
I changed the config to allow symlinks and it works now
