### ISSUE TITLE
Crash when try to select message bar.

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#4120]
To repro: make alacritty render message bar, then start selecting, and move your mouse over it, alacritty should crash. 

```
thread 'main' panicked at 'attempt to subtract with overflow', /home/kchibisov/src/rust/alacritty-workspace/fork/alacritty_terminal/src/grid/mod.rs:359:23
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::panicking::panic
             at src/libcore/panicking.rs:56
  14: alacritty_terminal::grid::Grid<T>::visible_to_buffer
             at ./alacritty_terminal/src/grid/mod.rs:359
  15: alacritty_terminal::term::Term<T>::visible_to_buffer
             at ./alacritty_terminal/src/term/mod.rs:938
  16: <alacritty::event::ActionContext<N,T> as alacritty::input::ActionContext<T>>::update_selection
             at alacritty/src/event.rs:199
  17: <alacritty::event::ActionContext<N,T> as alacritty::input::ActionContext<T>>::scroll
             at alacritty/src/event.rs:177
  18: alacritty::event::Processor<N>::handle_event
             at alacritty/src/event.rs:901
  19: alacritty::event::Processor<N>::run::{{closure}}
             at alacritty/src/event.rs:829
  20: winit::platform_impl::platform::sticky_exit_callback
             at /home/kchibisov/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:698
  21: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return
             at /home/kchibisov/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/wayland/event_loop.rs:537
  22: winit::platform_impl::platform::EventLoop<T>::run_return
             at /home/kchibisov/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:634
  23: <winit::event_loop::EventLoop<T> as winit::platform::desktop::EventLoopExtDesktop>::run_return
             at /home/kchibisov/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform/desktop.rs:51
  24: alacritty::event::Processor<N>::run
             at alacritty/src/event.rs:756
  25: alacritty::run
             at alacritty/src/main.rs:198
  26: alacritty::main
             at alacritty/src/main.rs:104
  27: std::rt::lang_start::{{closure}}
             at /home/kchibisov/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  28: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  29: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  30: std::panicking::try
             at src/libstd/panicking.rs:274
  31: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  32: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  33: std::rt::lang_start
             at /home/kchibisov/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  34: main
  35: __libc_start_main
             at ../csu/libc-start.c:308
  36: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by chrisduerr** [comment]
It doesn't crash for me? That would also be a regression.

**Comment by nixpulvis** [comment]
I'm also unable to make this crash, perhaps I'm not trying hard enough.

**Comment by chrisduerr** [comment]
The problem's actually not with moving it above the message bar during selection, but below it. Leaving the window while the mouse is held down. I'm not entirely sure if it crashes once you're inside the padding or you've left the window, but that should make the repro pretty easy.
