### ISSUE TITLE
thread 'main' panicked at 'failed to read wayland events: Invalid argument (os error 22)'

### ISSUE THREAD

**Issue by eternal-sorrow** [alacritty/alacritty#4139]
Alacritty randomly crashes with this message after some time of normal work. It happens when I do not use it and it's even not on my current workspace. It crashes with whatever application was running in it.

### System

OS: Linux
Version: alacritty 0.5.0
Linux/BSD: Wayland, sway

### Logs

Last lines of log from `RUST_BACKTRACE=full WAYLAND_DEBUG=1 alacritty`:

```
[1473533.104] wl_keyboard@13.keymap(1, fd 1004, 51277)
[1473546.039] wl_keyboard@52.keymap(1, fd 998, 51277)
[1473546.098] wl_keyboard@52.repeat_info(25, 600)
[1473546.114] wl_keyboard@52.keymap(1, fd 1008, 47298)
[1473546.130] wl_keyboard@52.repeat_info(25, 600)
[1473546.142] wl_keyboard@52.keymap(1, fd 1012, 47298)
[1473546.157] wl_keyboard@52.repeat_info(25, 600)
[1473546.169] wl_keyboard@52.keymap(1, fd 1015, 47298)
[1473546.184] wl_keyboard@52.repeat_info(25, 600)
[1473546.196] wl_keyboard@52.keymap(1, fd 1017, 47298)
[1473546.211] wl_keyboard@52.repeat_info(25, 600)
[1473546.222] wl_keyboard@52.keymap(1, fd 1019, 47298)
[1473546.237] wl_keyboard@52.repeat_info(25, 600)
[1473607.155] wl_keyboard@13.repeat_info(25, 600)
[1473607.190] wl_keyboard@13.keymap(1, fd 1010, 47298)
[1473610.050] wl_keyboard@13.repeat_info(25, 600)
[1473610.081] wl_keyboard@13.keymap(1, fd 1014, 47298)
[1473612.501] wl_keyboard@13.repeat_info(25, 600)
[1473612.528] wl_keyboard@13.keymap(1, fd 1016, 47298)
[1473660.129] wl_keyboard@13.repeat_info(25, 600)
[1473660.177] wl_keyboard@13.keymap(1, fd 1018, 47298)
[1473662.681] wl_keyboard@13.repeat_info(25, 600)
[1473662.711] wl_keyboard@13.keymap(1, fd 1020, 47298)
[1473665.117] wl_keyboard@13.repeat_info(25, 600)
file descriptor expected, object (13), message keymap(uhu)
thread 'main' panicked at 'failed to read wayland events: Invalid argument (os error 22)', /rustc/c367798cfd3817ca6ae908ce675d1d99242af148/src/libstd/macros.rs:16:9
stack backtrace:
   0:     0x56322f5a942f - <unknown>
   1:     0x56322f49cfdc - <unknown>
   2:     0x56322f5a8c36 - <unknown>
   3:     0x56322f5a8480 - <unknown>
   4:     0x56322f5a7a39 - <unknown>
   5:     0x56322f5a7688 - <unknown>
   6:     0x56322f5a7630 - <unknown>
   7:     0x56322f2c578e - <unknown>
   8:     0x56322f3f8d16 - <unknown>
   9:     0x56322f35ee17 - <unknown>
  10:     0x56322f5bd193 - <unknown>
  11:     0x56322f355fad - <unknown>
  12:     0x7fb0cc8cbceb - __libc_start_main
  13:     0x56322f29af6a - <unknown>
  14:                0x0 - <unknown>
```

**Comment by brendon-boldt** [comment]
For what it's worth, I have the same issue starting with Alacritty's update to 0.5.0. The stack trace is almost identical, but maybe there is an informative difference.

OS: Arch Linux (2020-08-13)
Version: 0.5.0
DE/WM: Sway (Wayland)

```
file descriptor expected, object (13), message keymap(uhu)
thread 'main' panicked at 'failed to read wayland events: Invalid argument (os error 22)', /build/rust/src/rustc-1.45.1-src/src/libstd/macros.rs:16:9
stack backtrace:
   0:     0x5563e3a159ff - <unknown>
   1:     0x5563e3902c8c - <unknown>
   2:     0x5563e3a15046 - <unknown>
   3:     0x5563e3a14830 - <unknown>
   4:     0x5563e3a13de9 - <unknown>
   5:     0x5563e3a13a38 - <unknown>
   6:     0x5563e3a139e0 - <unknown>
   7:     0x5563e372d5d5 - <unknown>
   8:     0x5563e385f346 - <unknown>
   9:     0x5563e37c5f1a - <unknown>
  10:     0x5563e3a296e3 - <unknown>
  11:     0x5563e37bd6dd - <unknown>
  12:     0x7fcf17e7b002 - __libc_start_main
  13:     0x5563e37030ee - <unknown>
  14:                0x0 - <unknown>
thread 'smithay-clipboard' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-clipboard-0.5.1/src/worker/mod.rs:270:30
stack backtrace:
   0:     0x5563e3a159ff - <unknown>
   1:     0x5563e3902c8c - <unknown>
   2:     0x5563e3a15046 - <unknown>
   3:     0x5563e3a14830 - <unknown>
   4:     0x5563e3a13de9 - <unknown>
   5:     0x5563e3a13a38 - <unknown>
   6:     0x5563e3900560 - <unknown>
   7:     0x5563e3906ff2 - <unknown>
   8:     0x5563e3a10ee7 - <unknown>
   9:     0x5563e39ea858 - <unknown>
  10:     0x5563e3a2a96a - <unknown>
  11:     0x7fcf1803e422 - <unknown>
  12:     0x7fcf17f53bf3 - clone
  13:                0x0 - <unknown>
```

**Comment by kchibisov** [comment]
>For what it's worth, I have the same issue starting with Alacritty's update to 0.5.0. The stack trace is almost identical, but maybe there is an informative difference.

I'm not sure how are you determining stacktraces without debug symbols. Also, could someone include **full** log of `WAYLAND_DEBUG=1` and stacktrace with debug symbols.

**Comment by kchibisov** [comment]
I've opened upstream issue https://github.com/swaywm/sway/issues/5633. For me it happens with literally every app if I hold layout switch for a while. With some apps it happens faster with other slower, but it's happening very reliably. I'd keep that issue around unless upstream provides some response on that crash.

**Comment by eternal-sorrow** [comment]
>Also, could someone include full log of WAYLAND_DEBUG=1 and stacktrace with debug symbols.

It would be way too long, because there may be hours before the crash occurs.
