### ISSUE TITLE
compilation error using "cargo install alacritty" on Debian 10 Buster

### ISSUE THREAD

**Issue by travnewmatic** [alacritty/alacritty#4179]
For Debian 10 Buster, the `rust`/`cargo` version in the Debian repositories will not install alacritty.

using rust from https://www.rust-lang.org/tools/install

```
...
   Compiling wayland-cursor v0.27.0
error: failed to run custom build command for `servo-fontconfig-sys v5.1.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install3iVDur/release/build/servo-fontconfig-sys-f2b3c9fb90a39636/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=FONTCONFIG_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=FONTCONFIG_STATIC
  cargo:rerun-if-env-changed=FONTCONFIG_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'Failed to run `"pkg-config" "--libs" "--cflags" "fontconfig" "fontconfig >= 2.11.1"`: No such file or directory (os error 2)', /home/tnewman/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-5.1.0/build.rs:34:17
  stack backtrace:
     0: backtrace::backtrace::libunwind::trace
               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
     1: backtrace::backtrace::trace_unsynchronized
               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
     2: std::sys_common::backtrace::_print_fmt
               at src/libstd/sys_common/backtrace.rs:78
     3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
               at src/libstd/sys_common/backtrace.rs:59
     4: core::fmt::write
               at src/libcore/fmt/mod.rs:1076
     5: std::io::Write::write_fmt
               at src/libstd/io/mod.rs:1537
     6: std::sys_common::backtrace::_print
               at src/libstd/sys_common/backtrace.rs:62
     7: std::sys_common::backtrace::print
               at src/libstd/sys_common/backtrace.rs:49
     8: std::panicking::default_hook::{{closure}}
               at src/libstd/panicking.rs:198
     9: std::panicking::default_hook
               at src/libstd/panicking.rs:217
    10: std::panicking::rust_panic_with_hook
               at src/libstd/panicking.rs:526
    11: rust_begin_unwind
               at src/libstd/panicking.rs:437
    12: std::panicking::begin_panic_fmt
               at src/libstd/panicking.rs:391
    13: build_script_build::main
    14: std::rt::lang_start::{{closure}}
    15: std::rt::lang_start_internal::{{closure}}
               at src/libstd/rt.rs:52
    16: std::panicking::try::do_call
               at src/libstd/panicking.rs:348
    17: std::panicking::try
               at src/libstd/panicking.rs:325
    18: std::panic::catch_unwind
               at src/libstd/panic.rs:394
    19: std::rt::lang_start_internal
               at src/libstd/rt.rs:51
    20: main
    21: __libc_start_main
               at ../csu/libc-start.c:308
    22: _start
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `alacritty v0.5.0`, intermediate artifacts can be found at `/tmp/cargo-install3iVDur`

Caused by:
  build failed
```

what do :(

**Comment by kchibisov** [comment]
Install dependencies https://github.com/alacritty/alacritty/blob/master/INSTALL.md#debianubuntu
