### ISSUE TITLE
Segmentation fault on Ubuntu 20.04 with Wayland and NVIDIA drivers

### ISSUE THREAD

**Issue by bigzed** [alacritty/alacritty#4265]
After adding `nvidia-drm.modeset=1`, updating the NVIDIA drivers to `nvidia-450` and using Wayland instead of X11 alacritty segfauls when it starts.

Running it with `XWayland` produces the following:
```
$ env WINIT_UNIX_BACKEND=x11 alacritty -v
Created log file at "/tmp/Alacritty-30738.log"
[2020-09-28 12:11:13.248345475] [INFO] Welcome to Alacritty
[2020-09-28 12:11:13.248477602] [INFO] Configuration loaded from "/home/steved/.config/alacritty/alacritty.yml"
[2020-09-28 12:11:13.328214416] [INFO] Device pixel ratio: 1
[2020-09-28 12:11:13.335024755] [INFO] Initializing glyph cache...
[2020-09-28 12:11:13.379706492] [INFO] ... finished initializing glyph cache in 0.044641081s
[2020-09-28 12:11:13.379743912] [INFO] Cell Size: 8 x 17
[2020-09-28 12:11:13.379768067] [INFO] Padding: 0 x 0
[2020-09-28 12:11:13.379776473] [INFO] Width: 800, Height: 600
[2020-09-28 12:11:13.380887843] [INFO] PTY dimensions: Line(35) x Column(100)
[2020-09-28 12:11:13.384878443] [INFO] Initialisation complete
[2020-09-28 12:11:13.385192511] [INFO] Width: 800, Height: 600
[2020-09-28 12:11:13.431824789] [INFO] Width: 3768, Height: 2133
X connection to :0 broken (explicit kill or server shutdown).
```

### System

OS: Linux Ubuntu 20.04
Version: Commit a754d06b44139b85e8b34a71ece4477cb1caa85e
Linux/BSD: Wayland with GNOME

### Logs
[CoreDump.zip](https://github.com/alacritty/alacritty/files/5291459/CoreDump.zip)

**Comment by chrisduerr** [comment]
Can you compile with debug info enabled?

**Comment by bigzed** [comment]
It also segfaults. Core dump is attached.
[Debug-Core.zip](https://github.com/alacritty/alacritty/files/5293379/Debug-Core.zip)

**Comment by chrisduerr** [comment]
Have you tried the open source nvidia drivers? Also could you give me the backtrace for that coredump, since I can't get it myself.

**Comment by bigzed** [comment]
No, I did not yet, because I doubt it even supports my monitor setup, but I'll try it.
Backtrace is attached:
```
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
[New LWP 7624]
Core was generated by `target/debug/alacritty'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa2ad297b7e in ?? ()
(gdb) symbol-file /home/steved/Documents/workspace/
[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K/home/t[Ksteved/stage/alacritty/at[Kt[Kar[K[K[Ktarget/debug/alacritty
Reading symbols from /home/steved/stage/alacritty/target/debug/alacritty...
(gdb) sharedlibrary[K[K[K[K[K[K[K[K[K[K[K[K[Ksharedlibrary
Reading symbols from /lib/x86_64-linux-gnu/libfontconfig.so.1...
(No debugging symbols found in /lib/x86_64-linux-gnu/libfontconfig.so.1)
Reading symbols from /lib/x86_64-linux-gnu/libfreetype.so.6...
(No debugging symbols found in /lib/x86_64-linux-gnu/libfreetype.so.6)
Reading symbols from /lib/x86_64-linux-gnu/libxcb.so.1...
(No debugging symbols found in /lib/x86_64-linux-gnu/libxcb.so.1)
Reading symbols from /lib/x86_64-linux-gnu/libxcb-render.so.0...
(No debugging symbols found in /lib/x86_64-linux-gnu/libxcb-render.so.0)
Reading symbols from /lib/x86_64-linux-gnu/libxcb-shape.so.0...
(No debugging symbols found in /lib/x86_64-linux-gnu/libxcb-shape.so.0)
Reading symbols from /lib/x86_64-linux-gnu/libxcb-xfixes.so.0...
(No debugging symbols found in /lib/x86_64-linux-gnu/libxcb-xfixes.so.0)
Reading symbols from /lib/x86_64-linux-gnu/libdl.so.2...
Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/libdl-2.31.so...
Reading symbols from /lib/x86_64-linux-gnu/libutil.so.1...
Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/libutil-2.31.so...
Reading symbols from /lib/x86_64-linux-gnu/librt.so.1...
Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/librt-2.31.so...
Reading symbols from /lib/x86_64-linux-gnu/libpthread.so.0...
Reading symbols from /usr/lib/debug/.build-id/4f/c5fc33f4429136a494c640b113d76f610e4abc.debug...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Reading symbols from /lib/x86_64-linux-gnu/libgcc_s.so.1...
(No debugging symbols found in /lib/x86_64-linux-gnu/libgcc_s.so.1)
Reading symbols from /lib/x86_64-linux-gnu/libc.so.6...
Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/libc-2.31.so...
Reading symbols from /lib64/ld-linux-x86-64.so.2...
(No debugging symbols found in /lib64/ld-linux-x86-64.so.2)
Reading symbols from /lib/x86_64-linux-gnu/libm.so.6...
Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/libm-2.31.so...
Reading symbols from /lib/x86_64-linux-gnu/libexpat.so.1...
(No debugging symbols found in /lib/x86_64-linux-gnu/libexpat.so.1)
Reading symbols from /lib/x86_64-linux-gnu/libuuid.so.1...
(No debugging symbols found in /lib/x86_64-linux-gnu/libuuid.so.1)
Reading symbols from /lib/x86_64-linux-gnu/libpng16.so.16...
(No debugging symbols found in /lib/x86_64-linux-gnu/libpng16.so.16)
Reading symbols from /lib/x86_64-linux-gnu/libz.so.1...
(No debugging symbols found in /lib/x86_64-linux-gnu/libz.so.1)
Reading symbols from /lib/x86_64-linux-gnu/libXau.so.6...
(No debugging symbols found in /lib/x86_64-linux-gnu/libXau.so.6)
Reading symbols from /lib/x86_64-linux-gnu/libXdmcp.so.6...
(No debugging symbols found in /lib/x86_64-linux-gnu/libXdmcp.so.6)
Reading symbols from /lib/x86_64-linux-gnu/libbsd.so.0...
(No debugging symbols found in /lib/x86_64-linux-gnu/libbsd.so.0)
Reading symbols from /lib/x86_64-linux-gnu/libwayland-client.so.0...
(No debugging symbols found in /lib/x86_64-linux-gnu/libwayland-client.so.0)
Reading symbols from /lib/x86_64-linux-gnu/libffi.so.7...
(No debugging symbols found in /lib/x86_64-linux-gnu/libffi.so.7)
Reading symbols from /lib/x86_64-linux-gnu/libwayland-cursor.so.0...
(No debugging symbols found in /lib/x86_64-linux-gnu/libwayland-cursor.so.0)
Reading symbols from /lib/x86_64-linux-gnu/libxkbcommon.so.0...
(No debugging symbols found in /lib/x86_64-linux-gnu/libxkbcommon.so.0)
Reading symbols from /lib/x86_64-linux-gnu/libwayland-egl.so.1...
(No debugging symbols found in /lib/x86_64-linux-gnu/libwayland-egl.so.1)
Reading symbols from /lib/x86_64-linux-gnu/libEGL.so.1...
(No debugging symbols found in /lib/x86_64-linux-gnu/libEGL.so.1)
Reading symbols from /lib/x86_64-linux-gnu/libGLdispatch.so.0...
(No debugging symbols found in /lib/x86_64-linux-gnu/libGLdispatch.so.0)
Reading symbols from /lib/x86_64-linux-gnu/libEGL_nvidia.so.0...
(No debugging symbols found in /lib/x86_64-linux-gnu/libEGL_nvidia.so.0)
Reading symbols from /lib/x86_64-linux-gnu/libnvidia-glsi.so.450.66...
(No debugging symbols found in /lib/x86_64-linux-gnu/libnvidia-glsi.so.450.66)
Reading symbols from /lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.1...
(No debugging symbols found in /lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.1)
Reading symbols from /lib/x86_64-linux-gnu/libwayland-server.so.0...
(No debugging symbols found in /lib/x86_64-linux-gnu/libwayland-server.so.0)
Reading symbols from /lib/x86_64-linux-gnu/libnvidia-eglcore.so.450.66...
(No debugging symbols found in /lib/x86_64-linux-gnu/libnvidia-eglcore.so.450.66)
Reading symbols from /lib/x86_64-linux-gnu/libEGL_mesa.so.0...
(No debugging symbols found in /lib/x86_64-linux-gnu/libEGL_mesa.so.0)
Reading symbols from /lib/x86_64-linux-gnu/libgbm.so.1...
(No debugging symbols found in /lib/x86_64-linux-gnu/libgbm.so.1)
Reading symbols from /lib/x86_64-linux-gnu/libglapi.so.0...
(No debugging symbols found in /lib/x86_64-linux-gnu/libglapi.so.0)
Reading symbols from /lib/x86_64-linux-gnu/libX11-xcb.so.1...
(No debugging symbols found in /lib/x86_64-linux-gnu/libX11-xcb.so.1)
Reading symbols from /lib/x86_64-linux-gnu/libxcb-dri2.so.0...
(No debugging symbols found in /lib/x86_64-linux-gnu/libxcb-dri2.so.0)
Reading symbols from /lib/x86_64-linux-gnu/libdrm.so.2...
(No debugging symbols found in /lib/x86_64-linux-gnu/libdrm.so.2)
Reading symbols from /lib/x86_64-linux-gnu/libxcb-dri3.so.0...
(No debugging symbols found in /lib/x86_64-linux-gnu/libxcb-dri3.so.0)
Reading symbols from /lib/x86_64-linux-gnu/libxcb-present.so.0...
(No debugging symbols found in /lib/x86_64-linux-gnu/libxcb-present.so.0)
Reading symbols from /lib/x86_64-linux-gnu/libxcb-sync.so.1...
(No debugging symbols found in /lib/x86_64-linux-gnu/libxcb-sync.so.1)
Reading symbols from /lib/x86_64-linux-gnu/libxshmfence.so.1...
(No debugging symbols found in /lib/x86_64-linux-gnu/libxshmfence.so.1)
(gdb) bt
#0  __strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
#1  0x00007fa2ac36622e in ?? () from /lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.1
#2  0x00007fa2ac365558 in ?? () from /lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.1
#3  0x00007fa2ac6cc552 in ?? () from /lib/x86_64-linux-gnu/libEGL_nvidia.so.0
#4  0x00007fa2ac654ff4 in ?? () from /lib/x86_64-linux-gnu/libEGL_nvidia.so.0
#5  0x000055c4f2c00aa2 in ?? ()
#6  0x000055c4f3430d88 in ?? ()
#7  0x000055c4f2c0692f in ?? ()
#8  0x00007fa2aca06d70 in eglCreateSync () from /lib/x86_64-linux-gnu/libEGL.so.1
#9  0x0000000000000000 in ?? ()
(gdb) quit
```

**Comment by bigzed** [comment]
It does not segfault with Nouveau, but is unusable because of the general framerate of wayland.

**Comment by chrisduerr** [comment]
Given the backtrace and it working on nouveau, it's pretty clearly a driver bug to me. Unfortunately you're probably not going to have much success complaining to Nvidia about that one.
