### ISSUE TITLE
Thread 'main' panicked at 'failed to read wayland events'

### ISSUE THREAD

**Issue by pmeiyu** [alacritty/alacritty#4358]
### System

OS: Linux
Version: alacritty 0.5.0
Window Manager: Sway (Wayland)

### How to reproduce the bug

I have a cron job to change wallpaper.  There is a chance that Alacritty will crash when the wallpaper is changed.  This bug has persisted for several months.

The command to change wallpaper:
```
swaymsg --quiet output DP-1 background $wallpaper_left fill
swaymsg --quiet output HDMI-A-1 background $wallpaper_right fill
```

### Logs

Crashes: STDERR, STDOUT
```
 ~  alacritty
file descriptor expected, object (14), message keymap(uhu)
thread 'main' panicked at 'failed to read wayland events: Invalid argument (os error 22)', /build/rustc-1.46.0-src/src/libstd/macros.rs:16:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ~  env RUST_BACKTRACE=1 alacritty                                                                        1.35h < 17:58:59
file descriptor expected, object (48), message keymap(uhu)
thread 'main' panicked at 'failed to read wayland events: Invalid argument (os error 22)', /build/rustc-1.46.0-src/src/libstd/macros.rs:16:9
stack backtrace:
 thread 'smithay-clipboard' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', /build/alacritty-0.5.0-vendor.tar.gz/smithay-clipboard/src/worker/mod.rs:272:14
  0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: __libc_start_main
  13: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: clone
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 ~  env RUST_BACKTRACE=full alacritty                                                                     1.38h < 19:22:11
file descriptor expected, object (14), message keymap(uhu)
thread 'main' panicked at 'failed to read wayland events: Invalid argument (os error 22)', /build/rustc-1.46.0-src/src/libstd/macros.rs:16:9
stack backtrace:
   0:     0x5593b9cb984f - <unknown>
   1:     0x5593b9ba468d - <unknown>
   2:     0x5593b9cc49b4 - <unknown>
   3:     0x5593b9cc1020 - <unknown>
   4:     0x5593b9cc0c32 - <unknown>
   5:     0x5593b9cc1498 - <unknown>
   6:     0x5593b9cc1440 - <unknown>
   7:     0x5593b9acbcdb - <unknown>
   8:     0x5593b9afcb77 - <unknown>
   9:     0x5593b9a43403 - <unknown>
  10:     0x5593b9cb9c13 - <unknown>
  11:     0x5593b9a3ca48 - <unknown>
  12:     0x7f2b769c0dbd - __libc_start_main
  13:     0x5593b99a91da - <unknown>
  14:                0x0 - <unknown>
```

**Comment by chrisduerr** [comment]
Can you reproduce this on the latest master?

**Comment by pmeiyu** [comment]
More logs:
```
 ~  env RUST_BACKTRACE=full alacritty -vv
Created log file at "/tmp/Alacritty-25465.log"
[2020-10-28 10:49:02.503695893] [INFO] Welcome to Alacritty
[2020-10-28 10:49:02.503928875] [INFO] Configuration loaded from "/home/meiyu/.config/alacritty/alacritty.yml"
[2020-10-28 10:49:02.536375695] [DEBUG] Estimated DPR: 1
[2020-10-28 10:49:02.536437301] [DEBUG] Estimated Cell Size: 13 x 25
[2020-10-28 10:49:02.536451911] [DEBUG] Estimated Dimensions: None
[2020-10-28 10:49:02.591717466] [INFO] Device pixel ratio: 1
[2020-10-28 10:49:02.608868362] [INFO] Initializing glyph cache...
[2020-10-28 10:49:02.675006025] [INFO] ... finished initializing glyph cache in 0.066072039s
[2020-10-28 10:49:02.675050891] [INFO] Cell Size: 13 x 25
[2020-10-28 10:49:02.675062034] [INFO] Padding: 0 x 0
[2020-10-28 10:49:02.675074550] [INFO] Width: 800, Height: 600
[2020-10-28 10:49:02.680282282] [INFO] PTY dimensions: Line(24) x Column(61)
[2020-10-28 10:49:02.695213538] [INFO] Initialisation complete
[2020-10-28 10:49:02.699111695] [DEBUG] New num_cols is 125 and num_lines is 33
[2020-10-28 10:49:02.700348612] [INFO] Width: 1636, Height: 845
[2020-10-28 10:49:03.244163246] [DEBUG] [Unhandled CSI] action='l', args=[1, 5, 2004], intermediates=[63]
[2020-10-28 10:49:03.260881629] [DEBUG] [unhandled osc_dispatch]: [['7',],['f','i','l','e',':','/','/','o','f','f','i','c','e','/','h','o','m','e','/','m','e','i','y','u',],] at line 785
[2020-10-28 10:49:21.321694257] [DEBUG] New num_cols is 125 and num_lines is 34
[2020-10-28 10:49:21.332204432] [INFO] Width: 1636, Height: 861
[2020-10-28 10:49:25.853773496] [DEBUG] New num_cols is 125 and num_lines is 33
[2020-10-28 10:49:25.854305237] [INFO] Width: 1636, Height: 845
[2020-10-28 10:49:28.621018124] [DEBUG] New num_cols is 125 and num_lines is 34
[2020-10-28 10:49:28.623533571] [INFO] Width: 1636, Height: 861
[2020-10-28 10:49:29.124052470] [DEBUG] New num_cols is 125 and num_lines is 33
[2020-10-28 10:49:29.124249027] [INFO] Width: 1636, Height: 845
[2020-10-28 10:49:31.473552627] [DEBUG] New num_cols is 125 and num_lines is 34
[2020-10-28 10:49:31.474989073] [INFO] Width: 1636, Height: 861
[2020-10-28 10:49:31.975595480] [DEBUG] New num_cols is 125 and num_lines is 33
[2020-10-28 10:49:31.975799779] [INFO] Width: 1636, Height: 845
[2020-10-28 10:49:33.827217005] [DEBUG] New num_cols is 125 and num_lines is 34
[2020-10-28 10:49:33.828043043] [INFO] Width: 1636, Height: 861
[2020-10-28 10:49:34.342176728] [DEBUG] New num_cols is 125 and num_lines is 33
[2020-10-28 10:49:34.342651786] [INFO] Width: 1636, Height: 845
[2020-10-28 10:49:35.908946881] [DEBUG] New num_cols is 125 and num_lines is 34
[2020-10-28 10:49:35.912414506] [INFO] Width: 1636, Height: 861
[2020-10-28 10:49:36.399098304] [DEBUG] New num_cols is 125 and num_lines is 33
[2020-10-28 10:49:36.399298563] [INFO] Width: 1636, Height: 845
[2020-10-28 10:49:38.330196361] [DEBUG] New num_cols is 125 and num_lines is 34
[2020-10-28 10:49:38.330822682] [INFO] Width: 1636, Height: 861
[2020-10-28 10:49:38.869787786] [DEBUG] New num_cols is 125 and num_lines is 33
[2020-10-28 10:49:38.870245486] [INFO] Width: 1636, Height: 845
[2020-10-28 10:49:40.741235087] [DEBUG] New num_cols is 125 and num_lines is 34
[2020-10-28 10:49:40.743801165] [INFO] Width: 1636, Height: 861
[2020-10-28 10:49:41.238488018] [DEBUG] New num_cols is 125 and num_lines is 33
[2020-10-28 10:49:41.238680164] [INFO] Width: 1636, Height: 845
[2020-10-28 10:49:43.394918548] [DEBUG] New num_cols is 125 and num_lines is 34
[2020-10-28 10:49:43.395864804] [INFO] Width: 1636, Height: 861
[2020-10-28 10:49:43.860760743] [DEBUG] New num_cols is 125 and num_lines is 33
[2020-10-28 10:49:43.860956095] [INFO] Width: 1636, Height: 845
[2020-10-28 10:49:45.739452639] [DEBUG] New num_cols is 125 and num_lines is 34
[2020-10-28 10:49:45.740023227] [INFO] Width: 1636, Height: 861
[2020-10-28 10:49:46.199675309] [DEBUG] New num_cols is 125 and num_lines is 33
[2020-10-28 10:49:46.199897473] [INFO] Width: 1636, Height: 846
[2020-10-28 10:49:46.288810081] [DEBUG] Term::resize dimensions unchanged
[2020-10-28 10:49:46.288905008] [INFO] Width: 1636, Height: 845
[2020-10-28 10:49:48.369342029] [DEBUG] New num_cols is 125 and num_lines is 34
[2020-10-28 10:49:48.370324084] [INFO] Width: 1636, Height: 861
[2020-10-28 10:49:48.862838585] [DEBUG] New num_cols is 125 and num_lines is 33
[2020-10-28 10:49:48.863045773] [INFO] Width: 1636, Height: 845
[2020-10-28 10:49:50.763173882] [DEBUG] New num_cols is 125 and num_lines is 34
[2020-10-28 10:49:50.765220746] [INFO] Width: 1636, Height: 861
[2020-10-28 10:49:51.192917962] [DEBUG] New num_cols is 125 and num_lines is 33
[2020-10-28 10:49:51.193106306] [INFO] Width: 1636, Height: 845
[2020-10-28 10:49:53.003222559] [DEBUG] New num_cols is 125 and num_lines is 34
[2020-10-28 10:49:53.003857207] [INFO] Width: 1636, Height: 861
[2020-10-28 10:49:53.476358833] [DEBUG] New num_cols is 125 and num_lines is 33
[2020-10-28 10:49:53.476616425] [INFO] Width: 1636, Height: 845
[2020-10-28 10:49:54.895067751] [DEBUG] New num_cols is 125 and num_lines is 34
[2020-10-28 10:49:54.896405479] [INFO] Width: 1636, Height: 861
[2020-10-28 10:49:55.358234642] [DEBUG] New num_cols is 125 and num_lines is 33
[2020-10-28 10:49:55.358437941] [INFO] Width: 1636, Height: 845
[2020-10-28 10:49:56.836076828] [DEBUG] New num_cols is 125 and num_lines is 34
[2020-10-28 10:49:56.840837854] [INFO] Width: 1636, Height: 861
[2020-10-28 10:49:57.350096732] [DEBUG] New num_cols is 125 and num_lines is 33
[2020-10-28 10:49:57.350565800] [INFO] Width: 1636, Height: 845
file descriptor expected, object (14), message keymap(uhu)
thread 'main' panicked at 'failed to read wayland events: Invalid argument (os error 22)', /build/rustc-1.46.0-src/src/libstd/macros.rs:16:9
stack backtrace:
   0:     0x5621400d384f - <unknown>
   1:     0x56213ffbe68d - <unknown>
   2:     0x5621400de9b4 - <unknown>
   3:     0x5621400db020 - <unknown>
   4:     0x5621400dac32 - <unknown>
   5:     0x5621400db498 - <unknown>
   6:     0x5621400db440 - <unknown>
   7:     0x56213fee5cdb - <unknown>
   8:     0x56213ff16b77 - <unknown>
   9:     0x56213fe5d403 - <unknown>
  10:     0x5621400d3c13 - <unknown>
  11:     0x56213fe56a48 - <unknown>
  12:     0x7f6aa66c0dbd - __libc_start_main
  13:     0x56213fdc31da - <unknown>
  14:                0x0 - <unknown>
```

**Comment by pmeiyu** [comment]
> Can you reproduce this on the latest master?

I will build and test it.

**Comment by kchibisov** [comment]
Fixed on master.

**Comment by pmeiyu** [comment]
I built alacritty from commit 598684243b587a96c986a0bc9627aaad56b0dfc1 and opened two windows.  They still have not crashed after several hours while one alaccritty v0.5 window crashed in the meantime.  So I think this bug is fixed on master branch. Thank you.
