### ISSUE TITLE
Alacritty crashes when pasting from firefox on wayland

### ISSUE THREAD

**Issue by ibrokemypie** [alacritty/alacritty#4376]
When pasting into alacritty after copying from firefox stable, alacritty freezes until something new is copied, then crashes.
Both alacritty and firefox are running in wayland with following wayland related env vars present
```
MOZ_DBUS_REMOTE=1
MOZ_ENABLE_WAYLAND=1
QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME=qt5ct
blank_mode=0
```
Neither firefox nor alacritty trigger xeyes movement when mouse is moved over them. wl-clipboard-rs and xclip are installed.

### System

OS: Linux
Version: alacritty 0.5.0 (a6681e3a)
Linux/BSD: Sway (wayland)

### Logs

Crashes:
```
thread 'smithay-clipboard' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-clipboard-0.5.1/src/worker/mod.rs:216:18
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-clipboard-0.5.1/src/lib.rs:54:38
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-clipboard-0.5.1/src/lib.rs:85:57
stack backtrace:
   0:     0x559e29007450 - <unknown>
   1:     0x559e28ef05cc - <unknown>
   2:     0x559e29006c36 - <unknown>
   3:     0x559e29006500 - <unknown>
   4:     0x559e29005bf2 - <unknown>
   5:     0x559e29005838 - <unknown>
   6:     0x559e29005804 - <unknown>
   7:     0x559e290057bd - <unknown>
   8:     0x559e28eedd50 - <unknown>
   9:     0x559e28ef4a92 - <unknown>
  10:     0x559e28de8d6e - <unknown>
  11:     0x559e28cf4903 - <unknown>
  12:     0x559e28dc07d6 - <unknown>
  13:     0x559e28dc00dd - <unknown>
  14:     0x559e28e3fac3 - <unknown>
  15:     0x559e28db4d58 - <unknown>
  16:     0x7fe726bb9152 - __libc_start_main
  17:     0x559e28ceb0ae - <unknown>
  18:                0x0 - <unknown>
thread panicked while panicking. aborting.
zsh: illegal hardware instruction (core dumped)  RUST_BACKTRACE=1 alacritty
```
Font/Terminal size: 
```
Created log file at "/tmp/Alacritty-100891.log"
[2020-11-04 16:11:00.077381525] [INFO] Welcome to Alacritty
[2020-11-04 16:11:00.077439242] [INFO] Configuration loaded from "/home/pie/.config/alacritty/alacritty.yml"
[2020-11-04 16:11:00.091469230] [DEBUG] Estimated DPR: 1
[2020-11-04 16:11:00.091489949] [DEBUG] Estimated Cell Size: 8 x 16
[2020-11-04 16:11:00.091495541] [DEBUG] Estimated Dimensions: Some((640, 384))
[2020-11-04 16:11:00.143796564] [INFO] Device pixel ratio: 1
[2020-11-04 16:11:00.147512502] [INFO] Initializing glyph cache...
[2020-11-04 16:11:00.188683024] [INFO] ... finished initializing glyph cache in 0.041148499s
[2020-11-04 16:11:00.188705904] [INFO] Estimated DPR correctly, skipping resize
[2020-11-04 16:11:00.188710080] [INFO] Cell Size: 8 x 16
[2020-11-04 16:11:00.188713881] [INFO] Padding: 0 x 0
[2020-11-04 16:11:00.188720153] [INFO] Width: 640, Height: 384
[2020-11-04 16:11:00.190054322] [INFO] PTY dimensions: Line(24) x Column(80)
[2020-11-04 16:11:00.192671940] [INFO] Initialisation complete
[2020-11-04 16:11:00.200251181] [DEBUG] New num_cols is 56 and num_lines is 61
[2020-11-04 16:11:00.201291213] [INFO] Width: 450, Height: 990
[2020-11-04 16:11:02.059379209] [INFO] Goodbye
Deleted log file at "/tmp/Alacritty-100891.log"
```

Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
Can you repro this on master?

**Comment by ibrokemypie** [comment]
I actually can't seem to reproduce it at all after rebooting for an unrelated reason... Very odd, not sure if should just close now or leave open in case it comes back.

**Comment by chrisduerr** [comment]
It should not be possible to run into this error on master. If you manage to reproduce on master, please let me know and I can re-open this issue.
