### ISSUE TITLE
Segmentation fault on exit in latest Fedora 33

### ISSUE THREAD

**Issue by j39m** [alacritty/alacritty#4824]
### System

OS: Fedora Linux (version 33)
Version: alacritty 0.7.1
Linux/BSD: swaywm on kernel 5.10.16

### Logs

Crashes: stderr only shows "Segmentation fault" (no other logs of note)

### Description & Backtrace

alacritty starts just fine, works just fine, functions perfectly. There is an inexplicable crash on exit (not really noticeable except to users staring at the system logs).

I note that I actually installed alacritty 0.7.1 in late December and it's worked perfectly until a recent system upgrade (including the kernel).

```none
(gdb) bt full
#0  0x00007f7818ab8df0 in wl_list_insert () from /lib64/libwayland-client.so
No symbol table info available.
#1  0x00007f7818aba3d2 in wl_display_read_events () from /lib64/libwayland-client.so
No symbol table info available.
#2  0x00007f7818aba939 in wl_display_dispatch_queue () from /lib64/libwayland-client.so
No symbol table info available.
#3  0x00007f7818abb6ef in wl_display_roundtrip_queue () from /lib64/libwayland-client.so
No symbol table info available.
#4  0x0000557d11cc4667 in wayland_client::imp::event_queue::{{impl}}::sync_roundtrip::{{closure}}<closure-5> () at /usr/share/cargo/registry/wayland-client-0.28.3/src/native_lib/event_queue.rs:85
        self = <optimized out>
        ret = <optimized out>
#5  wayland_client::imp::event_queue::with_dispatch_meta::{{closure}}<core::result::Result<u32, std::io::error::Error>,closure-5,closure-0> ()
    at /usr/share/cargo/registry/wayland-client-0.28.3/src/native_lib/event_queue.rs:24
        f = wayland_client::imp::event_queue::{{impl}}::sync_roundtrip::closure-0 (0x0)
#6  scoped_tls::ScopedKey<core::cell::RefCell<(&mut FnMut<(wayland_client::RawEvent, wayland_client::proxy::Main<wayland_client::anonymous_object::AnonymousObject>, wayland_commons::filter::DispatchData)>, wayland_commons::filter::DispatchData)>>::set<core::cell::RefCell<(&mut FnMut<(wayland_client::RawEvent, wayland_client::proxy::Main<wayland_client::anonymous_object::AnonymousObject>, wayland_commons::filter::DispatchData)>, wayland_commons::filter::DispatchData)>,closure-0,core::result::Result<u32, std::io::error::Error>> (self=<optimized out>, t=0x7f77c64887b0, f=...)
    at /usr/share/cargo/registry/scoped-tls-1.0.0/src/lib.rs:137
        _reset = scoped_tls::{{impl}}::set::Reset {key: 0x557d1201ee90, val: 0}
        prev = <optimized out>
        prev = <optimized out>
        _reset = scoped_tls::{{impl}}::set::Reset {key: 0x0, val: <optimized out>}
#7  wayland_client::imp::event_queue::with_dispatch_meta<core::result::Result<u32, std::io::error::Error>,closure-5,closure-0> (fb=..., data=..., f=...)
    at /usr/share/cargo/registry/wayland-client-0.28.3/src/native_lib/event_queue.rs:24
        data = wayland_commons::filter::DispatchData {data: core::any::&mut Any {pointer: 0x0, vtable: 0x0}}
        fb = core::ops::function::&mut FnMut<(wayland_client::RawEvent, wayland_client::proxy::Main<wayland_client::anonymous_object::AnonymousObject>, wayland_commons::filter::DispatchData)> {pointer: 0x7f77c6488870, vtable: 0x0}
        fb = core::ops::function::&mut FnMut<(wayland_client::RawEvent, wayland_client::proxy::Main<wayland_client::anonymous_object::AnonymousObject>, wayland_commons::filter::DispatchData)> {pointer: 0x0, vtable: 0x0}
        data = wayland_commons::filter::DispatchData {data: core::any::&mut Any {pointer: 0x0, vtable: 0x0}}
#8  wayland_client::imp::event_queue::EventQueueInner::sync_roundtrip<closure-5> (self=<optimized out>, data=..., fallback=...) at /usr/share/cargo/registry/wayland-client-0.28.3/src/native_lib/event_queue.rs:83
No locals.
#9  wayland_client::event_queue::EventQueue::sync_roundtrip<smithay_clipboard::worker::dispatch_data::ClipboardDispatchData,closure-5> (data=..., self=<optimized out>, fallback=...)
    at /usr/share/cargo/registry/wayland-client-0.28.3/src/event_queue.rs:191
        data = wayland_commons::filter::DispatchData {data: core::any::&mut Any {pointer: 0x7f77c6488920, vtable: 0x557d11ff4070}}
        data = wayland_commons::filter::DispatchData {data: core::any::&mut Any {pointer: 0x0, vtable: 0x0}}
#10 smithay_clipboard::worker::worker_impl (display=..., request_rx=..., reply_tx=...) at /usr/share/cargo/registry/smithay-clipboard-0.6.2/src/worker/mod.rs:319
        sa_tracker = smithay_clipboard::worker::sleep_amount_tracker::SleepAmountTracker {max_time_to_sleep: <optimized out>, time_to_sleep: <optimized out>, warm_wakeup: <optimized out>, max_warm_wakeups: <optimized out>}
        dispatch_data = smithay_clipboard::worker::dispatch_data::ClipboardDispatchData {observed_seats: alloc::collections::vec_deque::VecDeque<(wayland_client::protocol::wl_seat::WlSeat, u32)> {tail: 7, head: 0, buf: alloc::raw_vec::RawVec<(wayland_client::protocol::wl_seat::WlSeat, u32), alloc::alloc::Global> {ptr: core::ptr::unique::Unique<(wayland_client::protocol::wl_seat::WlSeat, u32)> {pointer: 0x7f77b4006020, _marker: core::marker::PhantomData<(wayland_client::protocol::wl_seat::WlSeat, u32)>}, cap: 8, alloc: alloc::alloc::Global}}, seats: alloc::vec::Vec<smithay_clipboard::worker::seat_data::SeatData> {buf: alloc::raw_vec::RawVec<smithay_clipboard::worker::seat_data::SeatData, alloc::alloc::Global> {ptr: core::ptr::unique::Unique<smithay_clipboard::worker::seat_data::SeatData> {pointer: 0x7f77b4005e30, _marker: core::marker::PhantomData<smithay_clipboard::worker::seat_data::SeatData>}, cap: 4, alloc: alloc::alloc::Global}, len: 1}}
        listener = smithay_client_toolkit::seat::SeatListener {_cb: alloc::rc::Rc<core::cell::RefCell<FnMut<(wayland_client::proxy::Attached<wayland_client::protocol::wl_seat::WlSeat>, &smithay_client_toolkit::seat::SeatData, wayland_commons::filter::DispatchData)>>> {ptr: core::ptr::non_null::NonNull<alloc::rc::RcBox<core::cell::RefCell<FnMut<(wayland_client::proxy::Attached<wayland_client::protocol::wl_seat::WlSeat>, &smithay_client_toolkit::seat::SeatData, wayland_commons::filter::DispatchData)>>>> {pointer: 0x7f77b40015b0}, phantom: core::marker::PhantomData<alloc::rc::RcBox<core::cell::RefCell<FnMut<(wayland_client::proxy::Attached<wayland_client::protocol::wl_seat::WlSeat>, &smithay_client_toolkit::seat::SeatData, wayland_commons::filter::DispatchData)>>>>}}
        seats = alloc::vec::Vec<smithay_clipboard::worker::seat_data::SeatData> {buf: alloc::raw_vec::RawVec<smithay_clipboard::worker::seat_data::SeatData, alloc::alloc::Global> {ptr: core::ptr::unique::Unique<smithay_clipboard::worker::seat_data::SeatData> {pointer: 0x7f77b4005e30, _marker: core::marker::PhantomData<smithay_clipboard::worker::seat_data::SeatData>}, cap: 4, alloc: alloc::alloc::Global}, len: 1}
        primary_selection_manager = core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionDeviceManager>::Some(smithay_client_toolkit::primary_selection::PrimarySelectionDeviceManager::Zwp(wayland_client::proxy::Attached<wayland_protocols::unstable::primary_selection::v1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1> {_s: core::marker::PhantomData<*mut ()>, inner: wayland_protocols::unstable::primary_selection::v1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1 (wayland_client::proxy::Proxy<wayland_protocols::unstable::primary_selection::v1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1> {_i: core::marker::PhantomData<&wayland_protocols::unstable::primary_selection::v1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1>, inner: wayland_client::imp::proxy::ProxyInner {internal: core::option::Option<alloc::sync::Arc<wayland_client::imp::--Type <RET> for more, q to quit, c to continue without paging--
proxy::ProxyInternal>>::Some(alloc::sync::Arc<wayland_client::imp::proxy::ProxyInternal> {ptr: core::ptr::non_null::NonNull<alloc::sync::ArcInner<wayland_client::imp::proxy::ProxyInternal>> {pointer: 0x7f77b4004e30}, phantom: core::marker::PhantomData<alloc::sync::ArcInner<wayland_client::imp::proxy::ProxyInternal>>}), ptr: 0x7f77b40036d0, wrapping: core::option::Option<*mut wayland_sys::client::wl_proxy>::Some(0x7f77b40036d0), display: core::option::Option<alloc::sync::Weak<wayland_client::imp::display::DisplayGuard>>::None}})}))
        data_device_manager = core::option::Option<wayland_client::proxy::Attached<wayland_client::protocol::wl_data_device_manager::WlDataDeviceManager>>::Some(wayland_client::proxy::Attached<wayland_client::protocol::wl_data_device_manager::WlDataDeviceManager> {_s: core::marker::PhantomData<*mut ()>, inner: wayland_client::protocol::wl_data_device_manager::WlDataDeviceManager (wayland_client::proxy::Proxy<wayland_client::protocol::wl_data_device_manager::WlDataDeviceManager> {_i: core::marker::PhantomData<&wayland_client::protocol::wl_data_device_manager::WlDataDeviceManager>, inner: wayland_client::imp::proxy::ProxyInner {internal: core::option::Option<alloc::sync::Arc<wayland_client::imp::proxy::ProxyInternal>>::Some(alloc::sync::Arc<wayland_client::imp::proxy::ProxyInternal> {ptr: core::ptr::non_null::NonNull<alloc::sync::ArcInner<wayland_client::imp::proxy::ProxyInternal>> {pointer: 0x7f77b4004190}, phantom: core::marker::PhantomData<alloc::sync::ArcInner<wayland_client::imp::proxy::ProxyInternal>>}), ptr: 0x7f77b40040f0, wrapping: core::option::Option<*mut wayland_sys::client::wl_proxy>::Some(0x7f77b40040f0), display: core::option::Option<alloc::sync::Weak<wayland_client::imp::display::DisplayGuard>>::None}})})
        env = smithay_client_toolkit::environment::Environment<smithay_clipboard::env::SmithayClipboard> {manager: wayland_client::globals::GlobalManager {inner: alloc::sync::Arc<std::sync::mutex::Mutex<wayland_client::globals::Inner>> {ptr: core::ptr::non_null::NonNull<alloc::sync::ArcInner<std::sync::mutex::Mutex<wayland_client::globals::Inner>>> {pointer: 0x7f77b4000fe0}, phantom: core::marker::PhantomData<alloc::sync::ArcInner<std::sync::mutex::Mutex<wayland_client::globals::Inner>>>}, registry: wayland_client::proxy::Main<wayland_client::protocol::wl_registry::WlRegistry> {inner: wayland_client::proxy::Attached<wayland_client::protocol::wl_registry::WlRegistry> {_s: core::marker::PhantomData<*mut ()>, inner: wayland_client::protocol::wl_registry::WlRegistry (wayland_client::proxy::Proxy<wayland_client::protocol::wl_registry::WlRegistry> {_i: core::marker::PhantomData<&wayland_client::protocol::wl_registry::WlRegistry>, inner: wayland_client::imp::proxy::ProxyInner {internal: core::option::Option<alloc::sync::Arc<wayland_client::imp::proxy::ProxyInternal>>::Some(alloc::sync::Arc<wayland_client::imp::proxy::ProxyInternal> {ptr: core::ptr::non_null::NonNull<alloc::sync::ArcInner<wayland_client::imp::proxy::ProxyInternal>> {pointer: 0x7f77b4001180}, phantom: core::marker::PhantomData<alloc::sync::ArcInner<wayland_client::imp::proxy::ProxyInternal>>}), ptr: 0x7f77b4001020, wrapping: core::option::Option<*mut wayland_sys::client::wl_proxy>::Some(0x7f77b4001020), display: core::option::Option<alloc::sync::Weak<wayland_client::imp::display::DisplayGuard>>::None}})}}}, inner: alloc::rc::Rc<core::cell::RefCell<smithay_clipboard::env::SmithayClipboard>> {ptr: core::ptr::non_null::NonNull<alloc::rc::RcBox<core::cell::RefCell<smithay_clipboard::env::SmithayClipboard>>> {pointer: 0x7f77b4000f40}, phantom: core::marker::PhantomData<alloc::rc::RcBox<core::cell::RefCell<smithay_clipboard::env::SmithayClipboard>>>}}
        display_proxy = wayland_client::proxy::Attached<wayland_client::protocol::wl_display::WlDisplay> {_s: core::marker::PhantomData<*mut ()>, inner: wayland_client::protocol::wl_display::WlDisplay (wayland_client::proxy::Proxy<wayland_client::protocol::wl_display::WlDisplay> {_i: core::marker::PhantomData<&wayland_client::protocol::wl_display::WlDisplay>, inner: wayland_client::imp::proxy::ProxyInner {internal: core::option::Option<alloc::sync::Arc<wayland_client::imp::proxy::ProxyInternal>>::None, ptr: 0x557d137cccf0, wrapping: core::option::Option<*mut wayland_sys::client::wl_proxy>::Some(0x7f77b4000cb0), display: core::option::Option<alloc::sync::Weak<wayland_client::imp::display::DisplayGuard>>::None}})}
        queue = wayland_client::event_queue::EventQueue {inner: alloc::rc::Rc<wayland_client::imp::event_queue::EventQueueInner> {ptr: core::ptr::non_null::NonNull<alloc::rc::RcBox<wayland_client::imp::event_queue::EventQueueInner>> {pointer: 0x7f77b4000c30}, phantom: core::marker::PhantomData<alloc::rc::RcBox<wayland_client::imp::event_queue::EventQueueInner>>}, display: wayland_client::display::Display {inner: alloc::sync::Arc<wayland_client::imp::display::DisplayInner> {ptr: core::ptr::non_null::NonNull<alloc::sync::ArcInner<wayland_client::imp::display::DisplayInner>> {pointer: 0x557d14219080}, phantom: core::marker::PhantomData<alloc::sync::ArcInner<wayland_client::imp::display::DisplayInner>>}}}
#11 0x0000557d11cafe4c in smithay_clipboard::worker::spawn::{{closure}} () at /usr/share/cargo/registry/smithay-clipboard-0.6.2/src/worker/mod.rs:44
        display = wayland_client::display::Display {inner: alloc::sync::Arc<wayland_client::imp::display::DisplayInner> {ptr: core::ptr::non_null::NonNull<alloc::sync::ArcInner<wayland_client::imp::display::DisplayInner>> {pointer: 0x0}, phantom: core::marker::PhantomData<alloc::sync::ArcInner<wayland_client::imp::display::DisplayInner>>}}
        worker_receiver = <error reading variable worker_receiver (Cannot access memory at address 0x0)>
        worker_replier = <error reading variable worker_replier (Cannot access memory at address 0x0)>
#12 std::sys_common::backtrace::__rust_begin_short_backtrace<closure-0,()> (f=...) at /builddir/build/BUILD/rustc-1.49.0-src/library/std/src/sys_common/backtrace.rs:125
No locals.
#13 0x0000557d11cb408f in std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}<closure-0,()> () at /builddir/build/BUILD/rustc-1.49.0-src/library/std/src/thread/mod.rs:474
        f = <error reading variable f (Cannot access memory at address 0x8)>
#14 std::panic::{{impl}}::call_once<(),closure-0> (self=<error reading variable: Cannot access memory at address 0x8>, _args=<optimized out>) at /builddir/build/BUILD/rustc-1.49.0-src/library/std/src/panic.rs:322
No locals.
#15 std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()> (data=<optimized out>) at /builddir/build/BUILD/rustc-1.49.0-src/library/std/src/panicking.rs:381
        data = <optimized out>
        data = <optimized out>
        data = <optimized out>
        data = <optimized out>
        f = <error reading variable f (Cannot access memory at address 0x8)>
#16 std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>> (f=<error reading variable: Cannot access memory at address 0x8>) at /builddir/build/BUILD/rustc-1.49.0-src/library/std/src/panicking.rs:345
        data_ptr = <optimized out>
        data = std::panicking::try::Data<std::panic::AssertUnwindSafe<closure-0>, ()> {f: core::mem::manually_drop::ManuallyDrop<std::panic::AssertUnwindSafe<closure-0>> {value: std::panic::AssertUnwindSafe<closure-0> (std::thread::{{impl}}::spawn_unchecked::{{closure}}::closure-0 (smithay_clipboard::worker::spawn::closure-0 (wayland_client::display::Display {inner: alloc::sync::Arc<wayland_client::imp::display::DisplayInner> {ptr: core::ptr::non_null::NonNull<alloc::sync::ArcInner<wayland_client::imp::display::DisplayInner>> {pointer: 0x0}, phantom: core::marker::PhantomData<alloc::sync::ArcInner<wayland_client::imp::display::DisplayInner>>}}, std::sync::mpsc::Receiver<smithay_clipboard::worker::Command> {inner: core::cell::UnsafeCell<std::sync::mpsc::Flavor<smithay_clipboard::worker::Command>> {value: std::sync::mpsc::Flavor<smithay_clipboard::worker::Command>::Oneshot(alloc::sync::Arc<std::sync::mpsc::oneshot::Packet<smithay_clipboard::worker::Command>> {ptr: core::ptr::non_null::NonNull<alloc::sync::ArcInner<std::sync::mpsc::oneshot::Packet<smithay_clipboard::worker::Command>>> {pointer: 0x0}, phantom: core::marker::PhantomData<alloc::sync::ArcInner<std::sync::mpsc::oneshot::Packet<smithay_clipboard::worker::Command>>>})}}, std::sync::mpsc::Sender<core::result::Result<alloc::string::String, std::io::error::Error>> {inner: core::cell::UnsafeCell<std::sync::mpsc::Flavor<core::result::Result<alloc::string::String, std::io::error::Error>>> {value: std::sync::mpsc::Flavor<core::result::Result<alloc::string::String, std::io::error::Error>>::Oneshot(alloc::sync::Arc<std::sync::mpsc::oneshot::Packet<core::result::Result<alloc::string::String, std::io::error::Error>>> {ptr: core::ptr::non_null::NonNull<alloc::sync::ArcInner<std::sync::mpsc::oneshot::Packet<core::result::Result<alloc::string::String, std::io::error::Error>>>> {pointer: 0x0}, phantom: core::marker::PhantomData<alloc::sync::A--Type <RET> for more, q to quit, c to continue without paging--
rcInner<std::sync::mpsc::oneshot::Packet<core::result::Result<alloc::string::String, std::io::error::Error>>>>})}})))}, r: core::mem::manually_drop::ManuallyDrop<()> {value: ()}, p: core::mem::manually_drop::ManuallyDrop<alloc::boxed::Box<Any, alloc::alloc::Global>> {value: core::any::Box<Any, alloc::alloc::Global> {pointer: 0x0, vtable: 0x0}}}
        data = <error reading variable data (Cannot access memory at address 0x8)>
        data_ptr = <optimized out>
#17 std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (f=<error reading variable: Cannot access memory at address 0x8>) at /builddir/build/BUILD/rustc-1.49.0-src/library/std/src/panic.rs:396
No locals.
#18 std::thread::{{impl}}::spawn_unchecked::{{closure}}<closure-0,()> () at /builddir/build/BUILD/rustc-1.49.0-src/library/std/src/thread/mod.rs:473
        their_thread = std::thread::Thread {inner: alloc::sync::Arc<std::thread::Inner> {ptr: core::ptr::non_null::NonNull<alloc::sync::ArcInner<std::thread::Inner>> {pointer: 0x557d1417e390}, phantom: core::marker::PhantomData<alloc::sync::ArcInner<std::thread::Inner>>}}
        stdout = core::option::Option<alloc::boxed::Box<LocalOutput, alloc::alloc::Global>>::None
        stderr = core::option::Option<alloc::boxed::Box<LocalOutput, alloc::alloc::Global>>::None
        f = smithay_clipboard::worker::spawn::closure-0 (wayland_client::display::Display {inner: alloc::sync::Arc<wayland_client::imp::display::DisplayInner> {ptr: core::ptr::non_null::NonNull<alloc::sync::ArcInner<wayland_client::imp::display::DisplayInner>> {pointer: 0x557d14219080}, phantom: core::marker::PhantomData<alloc::sync::ArcInner<wayland_client::imp::display::DisplayInner>>}}, std::sync::mpsc::Receiver<smithay_clipboard::worker::Command> {inner: core::cell::UnsafeCell<std::sync::mpsc::Flavor<smithay_clipboard::worker::Command>> {value: std::sync::mpsc::Flavor<smithay_clipboard::worker::Command>::Oneshot(alloc::sync::Arc<std::sync::mpsc::oneshot::Packet<smithay_clipboard::worker::Command>> {ptr: core::ptr::non_null::NonNull<alloc::sync::ArcInner<std::sync::mpsc::oneshot::Packet<smithay_clipboard::worker::Command>>> {pointer: 0x557d1421aca0}, phantom: core::marker::PhantomData<alloc::sync::ArcInner<std::sync::mpsc::oneshot::Packet<smithay_clipboard::worker::Command>>>})}}, std::sync::mpsc::Sender<core::result::Result<alloc::string::String, std::io::error::Error>> {inner: core::cell::UnsafeCell<std::sync::mpsc::Flavor<core::result::Result<alloc::string::String, std::io::error::Error>>> {value: std::sync::mpsc::Flavor<core::result::Result<alloc::string::String, std::io::error::Error>>::Oneshot(alloc::sync::Arc<std::sync::mpsc::oneshot::Packet<core::result::Result<alloc::string::String, std::io::error::Error>>> {ptr: core::ptr::non_null::NonNull<alloc::sync::ArcInner<std::sync::mpsc::oneshot::Packet<core::result::Result<alloc::string::String, std::io::error::Error>>>> {pointer: 0x557d1421acf0}, phantom: core::marker::PhantomData<alloc::sync::ArcInner<std::sync::mpsc::oneshot::Packet<core::result::Result<alloc::string::String, std::io::error::Error>>>>})}})
        their_packet = alloc::sync::Arc<core::cell::UnsafeCell<core::option::Option<core::result::Result<(), alloc::boxed::Box<Any, alloc::alloc::Global>>>>> {ptr: core::ptr::non_null::NonNull<alloc::sync::ArcInner<core::cell::UnsafeCell<core::option::Option<core::result::Result<(), alloc::boxed::Box<Any, alloc::alloc::Global>>>>>> {pointer: 0x557d1421ad40}, phantom: core::marker::PhantomData<alloc::sync::ArcInner<core::cell::UnsafeCell<core::option::Option<core::result::Result<(), alloc::boxed::Box<Any, alloc::alloc::Global>>>>>>}
        name = <optimized out>
        try_result = <error reading variable try_result (Cannot access memory at address 0x0)>
#19 core::ops::function::FnOnce::call_once<closure-0,()> () at /builddir/build/BUILD/rustc-1.49.0-src/library/core/src/ops/function.rs:227
No locals.
#20 0x0000557d11ea1d3a in std::sys::unix::thread::Thread::new::thread_start ()
No symbol table info available.
#21 0x00007f78189073f9 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#22 0x00007f78186ecb53 in clone () from /lib64/libc.so.6
No symbol table info available.
```

**Comment by chrisduerr** [comment]
Fixed in the latest version.

**Comment by mrswats** [comment]
I am having the same poblem after an Update. How did you solve this issue, @chrisduerr ?
