### ISSUE TITLE
SIGSEGV on snappack install. 

### ISSUE THREAD

**Issue by DemetryRomanowski** [alacritty/alacritty#4869]
After a fresh snap install of alacrity on Debian 10, and running it, alacrity crashes with a segmentation fault. 
Obviously this is unintended behavior and I'd expect it to start. 

### System

OS: Linux - Debian 10
Version: 0.2.0
Linux/BSD: X11

### Logs
```
fish: “alacritty” terminated by signal SIGSEGV (Address boundary error)
```
### GDB
```
Thread 1 "alacritty" received signal SIGSEGV, Segmentation fault.
0x00007f4cfb5237c6 in strlen () from /snap/core/current/lib/x86_64-linux-gnu/libc.so.6
```
### GDB Backtrace

```
#0  0x00007f4cfb5237c6 in strlen () from /snap/core/current/lib/x86_64-linux-gnu/libc.so.6
#1  0x0000558059d5f937 in std::ffi::c_str::CStr::from_ptr () at /checkout/src/libstd/ffi/c_str.rs:944
#2  glutin::api::glx::Context::new ()
    at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.16.0/src/api/glx/mod.rs:68
#3  glutin::platform::platform::x11::Context::new ()
    at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.16.0/src/platform/linux/x11.rs:146
warning: (Internal error: pc 0x558059d684e0 in read in psymtab, but not in symtab.)

warning: (Internal error: pc 0x558059d684e0 in read in psymtab, but not in symtab.)

warning: (Internal error: pc 0x558059d681e0 in read in psymtab, but not in symtab.)

warning: (Internal error: pc 0x558059d684e0 in read in psymtab, but not in symtab.)

warning: (Internal error: pc 0x558059d684e0 in read in psymtab, but not in symtab.)

warning: (Internal error: pc 0x558059d684e0 in read in psymtab, but not in symtab.)

#4  0x0000558059d684e1 in glutin::GlWindow::new ()
    at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.16.0/src/platform/linux/mod.rs:58
warning: (Internal error: pc 0x558059d684e0 in read in psymtab, but not in symtab.)

#5  0x0000558059d16e91 in alacritty::display::Display::new () at src/window.rs:212
#6  0x0000558059f40d3c in alacritty::main () at src/main.rs:101
```

**Comment by chrisduerr** [comment]
Don't use snap.

**Comment by DemetryRomanowski** [comment]
> Don't use snap.

:rofl:
