### ISSUE TITLE
Crash when coming back from full screen on i3

### ISSUE THREAD

**Issue by Eijebong** [alacritty/alacritty#4977]
Opening alacritty, setting it to full screen and coming back gets it to crash with the following backtrace:

```
thread 'main' panicked at 'index out of bounds: the len is 1016 but the index is 18446744073709550580', /data/code/alacritty/alacritty_terminal/src/term/search.rs:404:16
stack backtrace:
   0: rust_begin_unwind
             at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:69:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at ./.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:182:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at ./.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:15:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at ./.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2386:9
   6: <alacritty_terminal::grid::storage::Storage<T> as core::ops::index::Index<alacritty_terminal::index::Line>>::index
             at /data/code/alacritty/alacritty_terminal/src/grid/storage.rs:255:10
   7: <alacritty_terminal::grid::Grid<T> as core::ops::index::Index<alacritty_terminal::index::Line>>::index
             at /data/code/alacritty/alacritty_terminal/src/grid/mod.rs:446:10
   8: alacritty_terminal::term::search::<impl alacritty_terminal::term::Term<T>>::line_search_left
             at /data/code/alacritty/alacritty_terminal/src/term/search.rs:404:16
   9: alacritty::display::hint::highlighted_at::{{closure}}::{{closure}}
             at /data/code/alacritty/alacritty/src/display/hint.rs:264:29
  10: alacritty::config::ui_config::LazyRegex::with_compiled
             at /data/code/alacritty/alacritty/src/config/ui_config.rs:359:9
  11: alacritty::display::hint::highlighted_at::{{closure}}
             at /data/code/alacritty/alacritty/src/display/hint.rs:262:9
  12: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::find_map
             at ./.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs:268:38
  13: alacritty::display::hint::highlighted_at
             at /data/code/alacritty/alacritty/src/display/hint.rs:251:5
  14: alacritty::display::Display::update_highlighted_hints
             at /data/code/alacritty/alacritty/src/display/mod.rs:684:32
  15: alacritty::event::Processor<N>::run::{{closure}}
             at /data/code/alacritty/alacritty/src/event.rs:1092:17
  16: winit::platform_impl::platform::sticky_exit_callback
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:736:5
  17: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:330:17
  18: winit::platform_impl::platform::EventLoop<T>::run_return
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:645:56
  19: <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform/run_return.rs:56:9
  20: alacritty::event::Processor<N>::run
             at /data/code/alacritty/alacritty/src/event.rs:1004:9
  21: alacritty::run
             at /data/code/alacritty/alacritty/src/main.rs:204:5
  22: alacritty::main
             at /data/code/alacritty/alacritty/src/main.rs:102:23
  23: core::ops::function::FnOnce::call_once
             at ./.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Full logs:

```
[bastien@radium] ~  >>> alacritty -vv
Created log file at "/tmp/Alacritty-13162.log"
[2021-04-15 11:44:22.139715594] [INFO ] [alacritty] Welcome to Alacritty
[2021-04-15 11:44:22.139812206] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/home/bastien/.config/alacritty/alacritty.yml"
[2021-04-15 11:44:22.163778686] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-04-15 11:44:22.165940320] [DEBUG] [alacritty] Estimated DPR: 1
[2021-04-15 11:44:22.165964394] [DEBUG] [alacritty] Estimated window size: None
[2021-04-15 11:44:22.165983072] [DEBUG] [alacritty] Estimated cell size: 11 x 21
[2021-04-15 11:44:22.255347655] [INFO ] [alacritty] Device pixel ratio: 1
[2021-04-15 11:44:22.258177305] [INFO ] [alacritty] Initializing glyph cache...
[2021-04-15 11:44:22.267867524] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-04-15 11:44:22.279999027] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-04-15 11:44:22.292210163] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-04-15 11:44:22.304621353] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-04-15 11:44:22.313495327] [INFO ] [alacritty] ... finished initializing glyph cache in 0.055287523s
[2021-04-15 11:44:22.313608107] [INFO ] [alacritty] Cell size: 11 x 21
[2021-04-15 11:44:22.313623892] [INFO ] [alacritty] Padding: 0 x 0
[2021-04-15 11:44:22.313633593] [INFO ] [alacritty] Width: 800, Height: 600
[2021-04-15 11:44:22.322797743] [INFO ] [alacritty] PTY dimensions: 28 x 72
[2021-04-15 11:44:22.328271064] [INFO ] [alacritty] Initialisation complete
[2021-04-15 11:44:22.442737023] [DEBUG] [alacritty_terminal] New num_cols is 174 and num_lines is 16
[2021-04-15 11:44:22.459334951] [INFO ] [alacritty] Padding: 0 x 0
[2021-04-15 11:44:22.459385930] [INFO ] [alacritty] Width: 1918, Height: 344
[2021-04-15 11:44:23.008925015] [DEBUG] [alacritty_terminal] New num_cols is 174 and num_lines is 51
[2021-04-15 11:44:23.061543201] [INFO ] [alacritty] Padding: 0 x 0
[2021-04-15 11:44:23.061616294] [INFO ] [alacritty] Width: 1920, Height: 1080
[2021-04-15 11:44:23.423543864] [DEBUG] [alacritty_terminal] New num_cols is 174 and num_lines is 16
[2021-04-15 11:44:23.459638590] [INFO ] [alacritty] Padding: 0 x 0
[2021-04-15 11:44:23.459681849] [INFO ] [alacritty] Width: 1918, Height: 344
thread 'main' panicked at 'index out of bounds: the len is 1016 but the index is 18446744073709550577', /data/code/alacritty/alacritty_terminal/src/term/search.rs:404:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Note that it doesn't happen with every geometry and seems to be linked to the size of the window on opening. Opening a terminal on an empty workspace, going fullscreen and then back doesn't trigger the crash. Opening a second one while splitting vertically and trying to reproduce the bug only works with the newly opened one, not the original one even though their current size is the same.

**Comment by chrisduerr** [comment]
Which version is this?

**Comment by Eijebong** [comment]
Current master, 05917b27405f797bca817fa68305c08b74897997

**Comment by chrisduerr** [comment]
Ah great, that makes sense. Thanks.

**Comment by chrisduerr** [comment]
Looks to me like the mouse cursor position isn't correctly clamped to the viewport after a resize positioned it outside of the window.

**Comment by Eijebong** [comment]
I can even trigger the crash when opening alacritty if my mouse is below where it would open but only on the left side 

Also
![clamps](https://user-images.githubusercontent.com/3650385/114851020-aa949a00-9de1-11eb-86c5-a76d11008495.jpg)

**Comment by chrisduerr** [comment]
Ah, that's likely due to it resizing on start.
