### ISSUE TITLE
crash when pasting (smithay_clipboard SIGPIPE)

### ISSUE THREAD

**Issue by mckellygit** [alacritty/alacritty#5050]
Hi,

Thank you for Alacritty.  When pasting my alacritty terminal often crashes.
The trace is like below.  Not sure if SIGPIPE is expected/should be ignored/etc.
To reproduce more often try pasting 3 or 4 times in a row.
Pls let me know if there is any more info I can provide or test etc.

thx,
-m

Ubuntu 18.04 
alacritty 0.9.0-dev (8f4b752)
Wayland

Thread 11 "smithay-clipboa" received signal SIGPIPE, Broken pipe.

#0  0x00001555541d43a7 in write () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00005555558938f1 in std::sys::unix::fd::FileDesc::write () at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca//library/std/src/sys/unix/fd.rs:139
#2  std::sys::unix::fs::File::write () at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca//library/std/src/sys/unix/fs.rs:845
#3  std::fs::{{impl}}::write () at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca//library/std/src/fs.rs:633
#4  smithay_client_toolkit::data_device::source::{{impl}}::write ()
    at /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.12.3/src/data_device/source.rs:144
#5  std::io::Write::write_all<smithay_client_toolkit::data_device::source::WritePipe> ()
    at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1384
#6  0x0000555555883ab6 in std::io::Write::write_fmt::{{impl}}::write_str<smithay_client_toolkit::data_device::source::WritePipe> ()
    at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1507
#7  0x000055555577cf3c in core::fmt::write () at library/core/src/fmt/mod.rs:1078
#8  0x0000555555893603 in std::io::Write::write_fmt<smithay_client_toolkit::data_device::source::WritePipe> ()
    at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1518
#9  smithay_clipboard::worker::worker_impl::{{closure}} ()
    at /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-clipboard-0.6.3/src/worker/handlers.rs:81
#10 0x000055555589649e in wayland_client::proxy::{{impl}}::quick_assign::{{closure}}<wayland_protocols::misc::gtk_primary_selection::generated::client::gtk_primary_selection_source::GtkPrimarySelectionSource,closure-1> ()
    at /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.12.3/src/primary_selection/source.rs:111

**Comment by chrisduerr** [comment]
What compositor are you running and which version?

**Comment by mckellygit** [comment]
I think mutter ?  I am on Ubuntu 18.04 its default wayland set up.

**Comment by chrisduerr** [comment]
Which version?

**Comment by mckellygit** [comment]
Hi, sorry how to tell ?

**Comment by chrisduerr** [comment]
I'm not using mutter, you are. You should be able to figure out which software you're running on your system hopefully?

**Comment by mckellygit** [comment]
Its gnome-shell version: GNOME Shell 3.28.4
lib is: libmutter-2.so.0
I cannot seem to find out what _MUTTER_VERSION is inside that lib.
I will keep searching.

**Comment by chrisduerr** [comment]
Could you try the latest gnome version please?

**Comment by mckellygit** [comment]
Hi,
ok, I will try.
I have all the latest updates for my dist, I will go learn how to use a newer gnome/mutter.
thx,
-m

**Comment by mckellygit** [comment]
I have not had a chance to try a vm or find a way to upgrade gnome/mutter, sorry.
But - the fix in https://github.com/alacritty/alacritty/issues/5067 did change this issue for me.
With that commit, I no longer see a crash, but after 3 or 4 quick pastes the text that is pasted changes.

**Comment by chrisduerr** [comment]
How does it change? Could you go into a bit more detail on the exact steps you're taking to reproduce this?

**Comment by mckellygit** [comment]
I just do an ls -l for example to fill the screen with text, then select say 10 lines with mouse drag.
Then I paste with middle mouse button.  All is good.  But if I paste say 3 or 4 times in a row rapidly after the first few pastes the selection changes to be less bytes than it was originally.  I would say it seems the selection becomes just one line, which looks like its the last line of the original selection.

**Comment by mckellygit** [comment]
It does seem so far to only happen to me when the original selection is more than a few lines.

**Comment by chrisduerr** [comment]
That's odd, that almost sounds like a DOS protection mechanism by Wayland kicking in. I'd assume this can be reproduced by pasting into a different application, right? So not just copying&pasting into the same Alacritty instance.

Also does this only apply to selection + middle mouse paste, or can you also reproduce this with explicit keyboard copy+paste?

**Comment by mckellygit** [comment]
I cannot seem to cause the issue with a mouse select and keyboard (C-S-v) pastes.
I will keep trying to narrow it down.
