### ISSUE TITLE
Immediate crash on launch under Wayland

### ISSUE THREAD

**Issue by MTCoster** [alacritty/alacritty#5111]
As per the title, Alacritty crashes almost instantly when launching. This is my first time using the program on this system.

The initial error doesn't *seem* to make a lot of sense (to my untrained eye anyway), given the directory is present and correct afaik.

### System

OS: Ubuntu 21.04 (uname: `Linux LNB-M-COSTER 5.11.0-16-generic #17-Ubuntu SMP Wed Apr 14 20:12:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`)
Version: `alacritty 0.7.2 (5ac8060)`
Wayland compositor: `mutter 3.38.4-1ubuntu2`

### Logs

```
❯ RUST_BACKTRACE=full alacritty -vvv
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
Created log file at "/tmp/Alacritty-143964.log"
[2021-05-12 10:23:51.239652963] [INFO ] [alacritty_config_derive] No config file found; using default
[2021-05-12 10:23:51.239724174] [INFO ] [alacritty] Welcome to Alacritty
[2021-05-12 10:23:51.239733479] [INFO ] [alacritty] Configuration files loaded from:
[2021-05-12 10:23:51.249791138] [TRACE] [crossfont] Number of fonts is 59
[2021-05-12 10:23:51.249828771] [TRACE] [crossfont] Got font path="/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", index=0
[2021-05-12 10:23:51.249890609] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-05-12 10:23:51.250810595] [DEBUG] [alacritty] Estimated DPR: 1
[2021-05-12 10:23:51.250830244] [DEBUG] [alacritty] Estimated window size: None
[2021-05-12 10:23:51.250839192] [DEBUG] [alacritty] Estimated cell size: 9 x 17
thread 'main' panicked at 'internal error: entered unreachable code', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/wayland/window/mod.rs:218:77
stack backtrace:
   0:     0x558d807db4e0 - std::backtrace_rs::backtrace::libunwind::trace::h74532f8b485906a1
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x558d807db4e0 - std::backtrace_rs::backtrace::trace_unsynchronized::h2c8425dd0be5999b
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x558d807db4e0 - std::sys_common::backtrace::_print_fmt::hd8ce6577f46119ce
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x558d807db4e0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6289eeebc1f97d57
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x558d806bd12f - core::fmt::write::h3d3f8a8bb9d4c367
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/fmt/mod.rs:1092:17
   5:     0x558d807dadb1 - std::io::Write::write_fmt::ha117cbfa72664a7b
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/io/mod.rs:1572:15
   6:     0x558d807da755 - std::sys_common::backtrace::_print::h112e8a4ac2720a21
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x558d807da755 - std::sys_common::backtrace::print::h2a4ab5824600ebce
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x558d807da755 - std::panicking::default_hook::{{closure}}::h399ab06c3b83a1f2
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:208:50
   9:     0x558d807d9b3a - std::panicking::default_hook::h7481e93ca9c2d739
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:225:9
  10:     0x558d807d9b3a - std::panicking::rust_panic_with_hook::h01f9d4e9485ccb8b
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:591:17
  11:     0x558d807f73fe - std::panicking::begin_panic_handler::{{closure}}::h25bff4eb752cc444
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:495:13
  12:     0x558d807f739c - std::sys_common::backtrace::__rust_end_short_backtrace::h5dfd3f7920e58cc5
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x558d807f734d - rust_begin_unwind
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:493:5
  14:     0x558d8050c360 - core::panicking::panic_fmt::h5673e42e796a7b06
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:92:14
  15:     0x558d8050c2ac - core::panicking::panic::h20773dbe024b562f
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:50:5
  16:     0x558d805cb713 - winit::platform_impl::platform::wayland::window::Window::new::{{closure}}::{{closure}}::h200e30db820438ca
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/wayland/window/mod.rs:218:77
  17:     0x558d808263cf - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h90765c95500950f6
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/ops/function.rs:269:13
  18:     0x558d808263cf - wayland_client::imp::proxy::proxy_dispatcher::{{closure}}::{{closure}}::h2cb7bd66819f4626
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/proxy.rs:412:25
  19:     0x558d808263cf - scoped_tls::ScopedKey<T>::with::h8fcff654cd17c50a
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:171:13
  20:     0x558d808263cf - wayland_client::imp::proxy::proxy_dispatcher::{{closure}}::h7bccfb5422535d8d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/proxy.rs:409:21
  21:     0x558d808263cf - std::panicking::try::do_call::h995b7a103d327a94
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:379:40
  22:     0x558d808263cf - std::panicking::try::h934ff54c6755b0e8
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:343:19
  23:     0x558d808263cf - std::panic::catch_unwind::h892515fb27242874
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panic.rs:431:14
  24:     0x558d808263cf - wayland_client::imp::proxy::proxy_dispatcher::h573322a985391dfa
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/proxy.rs:376:15
  25:     0x7f62fbffa627 - <unknown>
  26:     0x7f62fbff6a92 - <unknown>
  27:     0x7f62fbff81dc - wl_display_dispatch_queue_pending
  28:     0x7f62fbff86df - wl_display_roundtrip_queue
  29:     0x558d805f3dd7 - wayland_client::imp::event_queue::EventQueueInner::sync_roundtrip::{{closure}}::h1fe58ab1798f017e
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/event_queue.rs:85:17
  30:     0x558d805f3dd7 - wayland_client::imp::event_queue::with_dispatch_meta::{{closure}}::h27fd881f2e923e0a
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/event_queue.rs:24:57
  31:     0x558d805f3dd7 - scoped_tls::ScopedKey<T>::set::h8aaa4781faa4e4c0
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  32:     0x558d805f3dd7 - wayland_client::imp::event_queue::with_dispatch_meta::h4fcb106cbbd72ded
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/event_queue.rs:24:5
  33:     0x558d805f3dd7 - wayland_client::imp::event_queue::EventQueueInner::sync_roundtrip::h21160f286441c662
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/event_queue.rs:83:9
  34:     0x558d805f3dd7 - wayland_client::event_queue::EventQueue::sync_roundtrip::he8acdaef66f30eb0
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/event_queue.rs:191:9
  35:     0x558d805f3dd7 - winit::platform_impl::platform::wayland::window::Window::new::{{closure}}::hb5e470696488c707
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/wayland/window/mod.rs:218:21
  36:     0x558d805f3dd7 - calloop::loop_logic::LoopHandle<Data>::with_source::h0976799811ca6783
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.6.5/src/loop_logic.rs:153:9
  37:     0x558d805f3dd7 - winit::platform_impl::platform::wayland::window::Window::new::h5d266efce60650ac
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/wayland/window/mod.rs:216:9
  38:     0x558d805f6d61 - winit::platform_impl::platform::Window::new::h230ec1288147f20f
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:277:17
  39:     0x558d805f6d61 - winit::window::WindowBuilder::build::h266459845b3f0858
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/window.rs:333:9
  40:     0x558d805f6d61 - glutin::platform_impl::platform_impl::wayland::Context::new::hed7375df979adde9
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/platform_impl/unix/wayland.rs:91:19
  41:     0x558d805f6d61 - glutin::platform_impl::platform_impl::Context::new_windowed::h9c524e3677af4c04
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/platform_impl/unix/mod.rs:113:20
  42:     0x558d805f6d61 - glutin::windowed::<impl glutin::ContextBuilder<T>>::build_windowed::h40b1346c6d4876c2
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/windowed.rs:341:9
  43:     0x558d8055f792 - alacritty::window::create_gl_window::h8c2c1e0e1f3f9ce1
                               at /build/alacritty/parts/alacritty/build/alacritty/src/window.rs:133:28
  44:     0x558d80561efe - alacritty::window::Window::new::h504f074815c76472
                               at /build/alacritty/parts/alacritty/build/alacritty/src/window.rs:186:13
  45:     0x558d8062b077 - alacritty::display::Display::new::h1433b3eec69c197c
                               at /build/alacritty/parts/alacritty/build/alacritty/src/display.rs:210:26
  46:     0x558d8063e390 - alacritty::run::h0ec2aa3cd2e02a7d
                               at /build/alacritty/parts/alacritty/build/alacritty/src/main.rs:144:19
  47:     0x558d8063e390 - alacritty::main::hbb178f27d9dc88cb
                               at /build/alacritty/parts/alacritty/build/alacritty/src/main.rs:109:23
  48:     0x558d80526313 - core::ops::function::FnOnce::call_once::h3db78e381ce3289b
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/ops/function.rs:227:5
  49:     0x558d80526313 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc0ae9b68f2a04d49
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:125:18
  50:     0x558d8063d1c6 - main
  51:     0x7f62fc0f90b3 - __libc_start_main
  52:     0x558d8051787e - _start
  53:                0x0 - <unknown>
[wayland-client error] A handler for wl_keyboard panicked.
[1]    143964 IOT instruction (core dumped)  RUST_BACKTRACE=full alacritty -vvv
```

```
❯ ls -alh /usr/share/X11/xkb
total 40K
drwxr-xr-x  8 root root 4.0K Jul 31  2020 .
drwxr-xr-x  5 root root 4.0K Apr 27 10:26 ..
drwxr-xr-x  2 root root 4.0K Apr 27 10:26 compat
drwxr-xr-x  4 root root 4.0K Apr 27 10:26 geometry
drwxr-xr-x  4 root root 4.0K Apr 27 10:26 keycodes
drwxr-xr-x  2 root root 4.0K Apr 27 10:26 rules
drwxr-xr-x 14 root root  12K Apr 27 10:26 symbols
drwxr-xr-x  2 root root 4.0K Apr 27 10:26 types
```

**Comment by chrisduerr** [comment]
Please try the latest master.

**Comment by kchibisov** [comment]
It seems like you don't have libxkbcommon linked to alacritty binary, so that's why it crashed.
