### ISSUE TITLE
Crash when displaying Chinese/Japanese characters

### ISSUE THREAD

**Issue by philj56** [alacritty/alacritty#5118]
Trying to display any Chinese/Japanese characters results in an immediate crash. Other UTF-8 characters (emojis, other alphabets/writing systems etc.) seem to work fine.

### System

OS: Arch Linux
Version: alacritty 0.7.2 (also happens on latest master, alacritty 0.9.0-dev (6d8db6b9))
Compositor: Sway version 1.6-85291411 (Apr 23 2021, branch 'master')

### Logs
Opening a new terminal, then trying to paste "風" into it: [alacritty.log](https://github.com/alacritty/alacritty/files/6472623/alacritty.log)
```
$ RUST_BACKTRACE=full alacritty --config-file=/dev/null -vv
Created log file at "/tmp/Alacritty-43267.log"
[2021-05-13 13:57:18.451633451] [INFO ] [alacritty] Welcome to Alacritty
[2021-05-13 13:57:18.451671521] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/dev/null"
[2021-05-13 13:57:18.459291239] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-05-13 13:57:18.461113677] [DEBUG] [alacritty] Estimated DPR: 1
[2021-05-13 13:57:18.461124527] [DEBUG] [alacritty] Estimated window size: None
[2021-05-13 13:57:18.461130287] [DEBUG] [alacritty] Estimated cell size: 9 x 21
[2021-05-13 13:57:18.486041039] [INFO ] [alacritty] Device pixel ratio: 1
[2021-05-13 13:57:18.488470943] [INFO ] [alacritty] Initializing glyph cache...
[2021-05-13 13:57:18.489926018] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-05-13 13:57:18.492449353] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-05-13 13:57:18.495027939] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-05-13 13:57:18.497643316] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-05-13 13:57:18.503918889] [INFO ] [alacritty] ... finished initializing glyph cache in 0.015433156s
[2021-05-13 13:57:18.503933050] [INFO ] [alacritty] Cell size: 9 x 21
[2021-05-13 13:57:18.503937260] [INFO ] [alacritty] Padding: 0 x 0
[2021-05-13 13:57:18.503940570] [INFO ] [alacritty] Width: 800, Height: 600
[2021-05-13 13:57:18.505363074] [INFO ] [alacritty] PTY dimensions: 28 x 88
[2021-05-13 13:57:18.506883419] [INFO ] [alacritty] Initialisation complete
[2021-05-13 13:57:18.516634008] [DEBUG] [alacritty_terminal] New num_cols is 106 and num_lines is 50
[2021-05-13 13:57:18.517507076] [INFO ] [alacritty] Padding: 0 x 0
[2021-05-13 13:57:18.517516347] [INFO ] [alacritty] Width: 959, Height: 1052
[2021-05-13 13:57:18.536628480] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1','2',],['7',],] at line 947
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 48, error_len: Some(1) }', /home/phil/.cargo/registry/src/github.com-1ecc6299db9ec823/crossfont-0.3.0/src/ft/fc/pattern.rs:53:80
stack backtrace:
   0:     0x56360f497e90 - std::backtrace_rs::backtrace::libunwind::trace::hd78b4ba06ac993cf
                               at /build/rust/src/rustc-1.52.1-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x56360f497e90 - std::backtrace_rs::backtrace::trace_unsynchronized::h95fa5389a1d2b354
                               at /build/rust/src/rustc-1.52.1-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56360f497e90 - std::sys_common::backtrace::_print_fmt::h37c6e01c9162dc76
                               at /build/rust/src/rustc-1.52.1-src/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56360f497e90 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5e97b27aa3eb98aa
                               at /build/rust/src/rustc-1.52.1-src/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x56360f3640cc - core::fmt::write::h98716008e9958965
                               at /build/rust/src/rustc-1.52.1-src/library/core/src/fmt/mod.rs:1092:17
   5:     0x56360f4976f1 - std::io::Write::write_fmt::h6ad0c4b41a2162ae
                               at /build/rust/src/rustc-1.52.1-src/library/std/src/io/mod.rs:1572:15
   6:     0x56360f497055 - std::sys_common::backtrace::_print::h9cca5cb30d369019
                               at /build/rust/src/rustc-1.52.1-src/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x56360f497055 - std::sys_common::backtrace::print::he57cb67e061bdd05
                               at /build/rust/src/rustc-1.52.1-src/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x56360f497055 - std::panicking::default_hook::{{closure}}::h8f7a0c254a6550f7
                               at /build/rust/src/rustc-1.52.1-src/library/std/src/panicking.rs:208:50
   9:     0x56360f49646c - std::panicking::default_hook::h696f935972289aa4
                               at /build/rust/src/rustc-1.52.1-src/library/std/src/panicking.rs:225:9
  10:     0x56360f49646c - std::panicking::rust_panic_with_hook::h10b3b7dcacb4acba
                               at /build/rust/src/rustc-1.52.1-src/library/std/src/panicking.rs:591:17
  11:     0x56360f4b5738 - std::panicking::begin_panic_handler::{{closure}}::h246428c494c1ff0e
                               at /build/rust/src/rustc-1.52.1-src/library/std/src/panicking.rs:497:13
  12:     0x56360f4b56ac - std::sys_common::backtrace::__rust_end_short_backtrace::h2df1ff8d2361119c
                               at /build/rust/src/rustc-1.52.1-src/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x56360f4b565d - rust_begin_unwind
                               at /build/rust/src/rustc-1.52.1-src/library/std/src/panicking.rs:493:5
  14:     0x56360f361950 - core::panicking::panic_fmt::h4ffea0aa70cef767
                               at /build/rust/src/rustc-1.52.1-src/library/core/src/panicking.rs:92:14
  15:     0x56360f368762 - core::option::expect_none_failed::h66609ef557e191aa
                               at /build/rust/src/rustc-1.52.1-src/library/core/src/option.rs:1329:5
  16:     0x56360f3710ce - core::result::Result<T,E>::unwrap::hdca355e6401a93ec
                               at /build/rust/src/rustc-1.52.1-src/library/core/src/result.rs:1037:23
  17:     0x56360f3710ce - crossfont::ft::fc::pattern::StringPropertyIter::get_value::hb84696f93bd5b103
                               at /home/phil/.cargo/registry/src/github.com-1ecc6299db9ec823/crossfont-0.3.0/src/ft/fc/pattern.rs:53:32
  18:     0x56360f3710ce - <crossfont::ft::fc::pattern::StringPropertyIter as core::iter::traits::iterator::Iterator>::next::h1bd701c5998ca4c6
                               at /home/phil/.cargo/registry/src/github.com-1ecc6299db9ec823/crossfont-0.3.0/src/ft/fc/pattern.rs:262:31
  19:     0x56360f3710ce - <crossfont::ft::fc::pattern::StringPropertyIter as core::iter::traits::iterator::Iterator>::nth::he2947844f448dbe6
                               at /home/phil/.cargo/registry/src/github.com-1ecc6299db9ec823/crossfont-0.3.0/src/ft/fc/pattern.rs:270:21
  20:     0x56360f3710ce - crossfont::ft::fc::pattern::PatternRef::file::h9e190d08f029b6fe
                               at /home/phil/.cargo/registry/src/github.com-1ecc6299db9ec823/crossfont-0.3.0/src/ft/fc/pattern.rs:606:18
  21:     0x56360f3710ce - crossfont::ft::fc::pattern::PatternRef::ft_face_location::h4b9a7ab43088ff95
                               at /home/phil/.cargo/registry/src/github.com-1ecc6299db9ec823/crossfont-0.3.0/src/ft/fc/pattern.rs:610:16
  22:     0x56360f3710ce - crossfont::ft::FreeTypeRasterizer::face_from_pattern::h07428efef5221d89
                               at /home/phil/.cargo/registry/src/github.com-1ecc6299db9ec823/crossfont-0.3.0/src/ft/mod.rs:316:41
  23:     0x56360f373b5a - crossfont::ft::FreeTypeRasterizer::load_face_with_glyph::hb4dc711720494c23
                               at /home/phil/.cargo/registry/src/github.com-1ecc6299db9ec823/crossfont-0.3.0/src/ft/mod.rs:412:31
  24:     0x56360f373b5a - crossfont::ft::FreeTypeRasterizer::face_for_glyph::ha9e1b6cb4e3facbc
                               at /home/phil/.cargo/registry/src/github.com-1ecc6299db9ec823/crossfont-0.3.0/src/ft/mod.rs:382:9
  25:     0x56360f373b5a - crossfont::ft::FreeTypeRasterizer::get_rendered_glyph::heefe7ccacca0fefd
                               at /home/phil/.cargo/registry/src/github.com-1ecc6299db9ec823/crossfont-0.3.0/src/ft/mod.rs:425:24
  26:     0x56360f373b5a - <crossfont::ft::FreeTypeRasterizer as crossfont::Rasterize>::get_glyph::h465036997d5c0546
                               at /home/phil/.cargo/registry/src/github.com-1ecc6299db9ec823/crossfont-0.3.0/src/ft/mod.rs:174:9
  27:     0x56360f28b9b8 - alacritty::renderer::GlyphCache::get::h83ea75e200ddc5a7
                               at /usr/src/debug/alacritty/alacritty/src/renderer/mod.rs:270:27
  28:     0x56360f28b758 - alacritty::renderer::RenderApi::render_cell::h66bda81dd4670857
                               at /usr/src/debug/alacritty/alacritty/src/renderer/mod.rs:891:21
  29:     0x56360f2c4eee - alacritty::display::Display::draw::{{closure}}::hddf133222614e183
                               at /usr/src/debug/alacritty/alacritty/src/display/mod.rs:536:21
  30:     0x56360f2c4eee - alacritty::renderer::QuadRenderer::with_api::hc725206beec99de4
                               at /usr/src/debug/alacritty/alacritty/src/renderer/mod.rs:699:19
  31:     0x56360f2c4eee - alacritty::display::Display::draw::he30748508f7e4cb5
                               at /usr/src/debug/alacritty/alacritty/src/display/mod.rs:521:13
  32:     0x56360f2ab52a - alacritty::event::Processor<N>::run::{{closure}}::h5868d38eed9536b0
                               at /usr/src/debug/alacritty/alacritty/src/event.rs:1138:17
  33:     0x56360f2a9132 - winit::platform_impl::platform::sticky_exit_callback::hd013e1e63cc173ea
                               at /home/phil/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:736:5
  34:     0x56360f2a9132 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return::hea9d9fe589e79138
                               at /home/phil/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/wayland/event_loop/mod.rs:388:13
  35:     0x56360f2a9132 - winit::platform_impl::platform::EventLoop<T>::run_return::h6874f56e211fe561
                               at /home/phil/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:645:56
  36:     0x56360f231fd9 - <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return::h9cfa58c97db7db74
                               at /home/phil/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform/run_return.rs:56:9
  37:     0x56360f231fd9 - alacritty::event::Processor<N>::run::hdc2ceb5dee1b5d40
                               at /usr/src/debug/alacritty/alacritty/src/event.rs:1029:9
  38:     0x56360f2defc5 - alacritty::run::h3734b0a97d7eda87
                               at /usr/src/debug/alacritty/alacritty/src/main.rs:204:5
  39:     0x56360f2defc5 - alacritty::main::h6056fe90bcc5bcf4
                               at /usr/src/debug/alacritty/alacritty/src/main.rs:102:23
  40:     0x56360f1a3143 - core::ops::function::FnOnce::call_once::he853569db0844751
                               at /build/rust/src/rustc-1.52.1-src/library/core/src/ops/function.rs:227:5
  41:     0x56360f1a3143 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4690b918bdbd4ecf
                               at /build/rust/src/rustc-1.52.1-src/library/std/src/sys_common/backtrace.rs:125:18
  42:     0x56360f2da336 - main
  43:     0x7f47c1d09b25 - __libc_start_main
  44:     0x56360f19006e - _start
  45:                0x0 - <unknown>
```

**Comment by chrisduerr** [comment]
Huh that's interesting, seems like something inside your pattern is not a valid UTF-8 string. Do you have a Rust toolchain installed? I'm curious what part of the pattern is causing this issue. I believe this should mean that you have a font installed with a filename that is not valid UTF-8, but I'd like to verify.

**Comment by philj56** [comment]
Ahah, you're right - looks like the culprit is [Chihaya Gothic](https://welina.xyz/font/tegaki/gothic/) which I had installed. This has a completely busted name in e.g. kitty:
![2021-05-13T15:48:42,725894813+01:00](https://user-images.githubusercontent.com/13610623/118143511-5510d480-b403-11eb-8c7d-5e042a1b8f30.png)

I'm happy to build / rebuild whatever to debug if you want.

**Comment by chrisduerr** [comment]
This shouldn't crash Alacritty, but we can basically do whatever in that scenario (I don't particularly mind skipping those fonts). So I think this should be fairly easy to resolve.

**Comment by r00ster91** [comment]
I cannot reproduce this on 0.8.0 when I type in Japanese or Chinese characters with the IME or paste them in.
