### ISSUE TITLE
Cause crash when display multi byte character in tmux and resize window or change font size.

### ISSUE THREAD

**Issue by kuuote** [alacritty/alacritty#5170]
I always use alacritty, thanks.

### Repro step
0. Run tmux session
0. Execute `for i in $(seq 1000); do echo '\u3042'; done` in shell
0. Resize window or change font size many times

### System

OS: Linux
Version: alacritty 0.9.0-dev (3c61e07)
X11, i3wm
tmux 3.2

### Logs

Crashes: STDERR, STDOUT
```
thread 'PTY reader' panicked at 'index out of bounds: the len is 85 but the index is 85', /hd/ghq/github.com/alacritty/alacritty/alacritty_terminal/src/term/mod.rs:778:17
stack backtrace:
   0: rust_begin_unwind
             at /build/rust/src/rustc-1.52.1-src/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /build/rust/src/rustc-1.52.1-src/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /build/rust/src/rustc-1.52.1-src/library/core/src/panicking.rs:69:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index_mut
             at /build/rust/src/rustc-1.52.1-src/library/core/src/slice/index.rs:188:14
   4: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /build/rust/src/rustc-1.52.1-src/library/core/src/slice/index.rs:26:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut
             at /build/rust/src/rustc-1.52.1-src/library/alloc/src/vec/mod.rs:2393:9
   6: <alacritty_terminal::grid::row::Row<T> as core::ops::index::IndexMut<alacritty_terminal::index::Column>>::index_mut
             at /hd/ghq/github.com/alacritty/alacritty/alacritty_terminal/src/grid/row.rs:200:14
   7: alacritty_terminal::term::Term<T>::write_at_cursor
             at /hd/ghq/github.com/alacritty/alacritty/alacritty_terminal/src/term/mod.rs:778:17
   8: <alacritty_terminal::term::Term<T> as alacritty_terminal::ansi::Handler>::input
             at /hd/ghq/github.com/alacritty/alacritty/alacritty_terminal/src/term/mod.rs:864:13
   9: <alacritty_terminal::ansi::Performer<H> as vte::Perform>::print
             at /hd/ghq/github.com/alacritty/alacritty/alacritty_terminal/src/ansi.rs:883:9
  10: vte::Parser::perform_action
             at /home/arch/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.10.1/src/lib.rs:219:30
  11: vte::Parser::perform_state_change
             at /home/arch/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.10.1/src/lib.rs:162:17
  12: vte::Parser::advance
             at /home/arch/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.10.1/src/lib.rs:130:9
  13: alacritty_terminal::ansi::Processor::advance
             at /hd/ghq/github.com/alacritty/alacritty/alacritty_terminal/src/ansi.rs:162:13
  14: alacritty_terminal::event_loop::EventLoop<T,U>::pty_read
             at /hd/ghq/github.com/alacritty/alacritty/alacritty_terminal/src/event_loop.rs:243:25
  15: alacritty_terminal::event_loop::EventLoop<T,U>::spawn::{{closure}}
             at /hd/ghq/github.com/alacritty/alacritty/alacritty_terminal/src/event_loop.rs:376:51
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'expected send event loop msg: Disconnected', alacritty_terminal/src/event_loop.rs:81:41
stack backtrace:
   0: rust_begin_unwind
             at /build/rust/src/rustc-1.52.1-src/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /build/rust/src/rustc-1.52.1-src/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /build/rust/src/rustc-1.52.1-src/library/core/src/option.rs:1329:5
   3: core::result::Result<T,E>::expect
             at /build/rust/src/rustc-1.52.1-src/library/core/src/result.rs:997:23
   4: <alacritty_terminal::event_loop::Notifier as alacritty_terminal::event::OnResize>::on_resize
             at /hd/ghq/github.com/alacritty/alacritty/alacritty_terminal/src/event_loop.rs:81:9
   5: alacritty::display::Display::handle_update
             at /hd/ghq/github.com/alacritty/alacritty/alacritty/src/display/mod.rs:460:9
   6: alacritty::event::Processor<N>::submit_display_update
             at /hd/ghq/github.com/alacritty/alacritty/alacritty/src/event.rs:1432:9
   7: alacritty::event::Processor<N>::run::{{closure}}
             at /hd/ghq/github.com/alacritty/alacritty/alacritty/src/event.rs:1107:17
   8: winit::platform_impl::platform::sticky_exit_callback
             at /home/arch/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:736:5
   9: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/arch/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:330:17
  10: winit::platform_impl::platform::EventLoop<T>::run_return
             at /home/arch/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:645:56
  11: <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return
             at /home/arch/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform/run_return.rs:56:9
  12: alacritty::event::Processor<N>::run
             at /hd/ghq/github.com/alacritty/alacritty/alacritty/src/event.rs:1029:9
  13: alacritty::run
             at /hd/ghq/github.com/alacritty/alacritty/alacritty/src/main.rs:204:5
  14: alacritty::main
             at /hd/ghq/github.com/alacritty/alacritty/alacritty/src/main.rs:102:23
  15: core::ops::function::FnOnce::call_once
             at /build/rust/src/rustc-1.52.1-src/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Font/Terminal size: `alacritty -vv`
```
[2021-05-24 20:31:54.415692674] [INFO ] [alacritty] Welcome to Alacritty
[2021-05-24 20:31:54.415913866] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/home/arch/.config/alacritty/alacritty.yml"
[2021-05-24 20:31:54.431093138] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-05-24 20:31:54.433603753] [DEBUG] [alacritty] Estimated DPR: 1
[2021-05-24 20:31:54.433759743] [DEBUG] [alacritty] Estimated window size: None
[2021-05-24 20:31:54.433880666] [DEBUG] [alacritty] Estimated cell size: 6 x 18
[2021-05-24 20:31:54.470319285] [INFO ] [alacritty] Device pixel ratio: 1
[2021-05-24 20:31:54.478948167] [INFO ] [alacritty] Initializing glyph cache...
[2021-05-24 20:31:54.484091149] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-05-24 20:31:54.490144440] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-05-24 20:31:54.497148441] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-05-24 20:31:54.503694221] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-05-24 20:31:54.518687503] [INFO ] [alacritty] ... finished initializing glyph cache in 0.039492442s
[2021-05-24 20:31:54.519142659] [INFO ] [alacritty] Cell size: 6 x 18
[2021-05-24 20:31:54.519225033] [INFO ] [alacritty] Padding: 0 x 0
[2021-05-24 20:31:54.519307853] [INFO ] [alacritty] Width: 800, Height: 600
[2021-05-24 20:31:54.536759471] [INFO ] [alacritty] PTY dimensions: 33 x 133
[2021-05-24 20:31:54.542902725] [INFO ] [alacritty] Initialisation complete
[2021-05-24 20:31:54.558952698] [DEBUG] [alacritty_terminal] New num_cols is 156 and num_lines is 57
[2021-05-24 20:31:54.579677710] [INFO ] [alacritty] Padding: 0 x 0
[2021-05-24 20:31:54.579859767] [INFO ] [alacritty] Width: 941, Height: 1035
```

**Comment by chrisduerr** [comment]
Could you go into a little more detail? I don't think I can reproduce the crash, at least it wasn't possible immediately. Are you just running the command once and then resizing or do you keep running it?
