### ISSUE TITLE
Alacrity Blank White Screen & Not Responding

### ISSUE THREAD

**Issue by riez** [alacritty/alacritty#5182]
### System
OS:Windows
Version: 0.8.0

### Screenshot
![image](https://user-images.githubusercontent.com/37952353/119766148-b4301800-bede-11eb-9cbd-604e581d113b.png)

### Additional Information
- Newly Fresh Install from Relase Page using msi installer
- It doesn't show anything from start. Only White blank screen. I'm using AMD vga. Is this matter?

**Comment by chrisduerr** [comment]
Which GPU are you using?

**Comment by riez** [comment]
Sapphire Rx 5700 XT

**Comment by chrisduerr** [comment]
What output do you get when starting Alacritty from a different terminal? Looks like the application is frozen.

**Comment by riez** [comment]
I just tested it .. Its work when opening it from other terminal.
![image](https://user-images.githubusercontent.com/37952353/119791713-421bfb00-beff-11eb-9fd9-d4e8072d764b.png)

But why it doesn't when opening through windows start?

**Comment by chrisduerr** [comment]
Likely an issue with your configuration. Are you running with an empty Alacritty/shell config?

**Comment by riez** [comment]
Yep .. I'm not set any configuration file..

Anyway I can't use Ctrl + Shift + c to copy test while I can use Ctrl + Shift + v for paste.

**Comment by chrisduerr** [comment]
Are there any other popup windows open when Alacritty freezes like that?

**Comment by riez** [comment]
Nope.. There is no other windows popup..

**Comment by chrisduerr** [comment]
Could you set your shell to the full path of the powershell executable, rather than resolving it through the `PATH`?

**Comment by riez** [comment]
Is this what you refers to?
![image](https://user-images.githubusercontent.com/37952353/120233636-7cc7bf80-c280-11eb-8a49-79166c0da8d7.png)

**Comment by chrisduerr** [comment]
I'm talking about your Alacritty configuration.

**Comment by riez** [comment]
![image](https://user-images.githubusercontent.com/37952353/120554806-66f2ff80-c424-11eb-8e5b-25ea8bb76227.png)

Not getting luck yet with that configuration

**Comment by chrisduerr** [comment]
By which you mean you get the exact same error, or a different one? The backslashes might create some problems with text escapes, you should try forward slashes too.

**Comment by riez** [comment]
Still.. only white blank no error pop up.

**Comment by codemonkey76** [comment]
I get the same thing, mine is not all the time though, so it's not a config problem... it works flawlessly for a while, and maybe once or twice a day, it crashes and won't open, just gives me the not responding white screen and I normally have to reboot before it starts working again. It always works after a reboot. I am using WSL2, and Windows 11

**Comment by alexya** [comment]
I met the same problem today.

**Comment by MikeGitIt** [comment]
This is where it panics for me and yes, the screen is as white as snow:
`panicked at alacritty_terminal\src\tty\windows\conpty.rs:305:5:`

**Comment by MikeGitIt** [comment]
Never mind. I deleted everything in my alacritty.toml file (which was nothing other than `import = []
shell = "/bin/zsh"`.

**Comment by kon-sv** [comment]
I had this problem today trying to open Alacritty from windows 10 context menu on a secondary disk partition (marked as E:\) inside any folder. The screen of alacritty remains white until I pressed Alt which had the following error appeared

`
---------------------------
Alacritty: Runtime Error
---------------------------
panicked at alacritty_terminal\src\tty\windows\conpty.rs:305:5:
Unable to spawn shell: The directory name is invalid. (os error 267)
`
