### ISSUE TITLE
Zooming in Gomuks when a image is displayed crashes Alacritty?

### ISSUE THREAD

**Issue by nonetrix** [alacritty/alacritty#5203]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Arch Linux archbtw 5.12.8-zen1-1-zen
Version: alacritty 0.8.0 (a1b13e68)
Linux/BSD: X11 Awesome VM

### Logs

Crashes: 
```
thread 'PTY reader' panicked at 'index out of bounds: the len is 78 but the index is 78', /build/alacritty/src/alacritty/alacritty_terminal/src/term/mod.rs:778:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'expected send event loop msg: Disconnected', alacritty_terminal/src/event_loop.rs:81:41
```
zooming into the terminal with ctrl + plus in gomuks while a image is displayed crashes the terminal I can reproduce it every time 

Font/Terminal size: 
```
[2021-06-02 23:10:43.294783664] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Oblique, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-06-02 23:10:43.296592796] [INFO ] [alacritty] Font size changed to Size(30) with DPR of 1
[2021-06-02 23:10:43.298505933] [INFO ] [alacritty] Cell size: 12 x 24
thread 'main' panicked at 'expected send event loop msg: Disconnected', alacritty_terminal/src/event_loop.rs:81:41
```
Keyboard and bindings:
```
[2021-06-02 23:11:42.741154728] [INFO ] [alacritty] Width: 943, Height: 1155
thread 'PTY reader' panicked at 'index out of bounds: the len is 78 but the index is 78', /build/alacritty/src/alacritty/alacritty_terminal/src/term/mod.rs:778:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-06-02 23:11:42.827764115] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 26048, tv_nsec: 553557553 }, requested_resume: None })
[2021-06-02 23:11:42.827827744] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(8))), event: Key(KeyboardInput { scancode: 13, state: Released, virtual_keycode: Some(Equals), modifiers: CTRL }) }
[2021-06-02 23:11:42.827850897] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(35651586))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 13, state: Released, virtual_keycode: Some(Equals), modifiers: CTRL }, is_synthetic: false } }
[2021-06-02 23:11:42.827862569] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-06-02 23:11:42.827868260] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-06-02 23:11:43.328789993] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 26048, tv_nsec: 620474859 }, requested_resume: None })
[2021-06-02 23:11:43.328847120] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(8))), event: Key(KeyboardInput { scancode: 13, state: Pressed, virtual_keycode: Some(Equals), modifiers: CTRL }) }
[2021-06-02 23:11:43.328872418] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(35651586))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 13, state: Pressed, virtual_keycode: Some(Equals), modifiers: CTRL }, is_synthetic: false } }
[2021-06-02 23:11:43.328887736] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(35651586))), event: ReceivedCharacter('=') }
[2021-06-02 23:11:43.328898817] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-06-02 23:11:43.328906692] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-06-02 23:11:43.355507336] [INFO ] [alacritty] Font size changed to Size(30) with DPR of 1
[2021-06-02 23:11:43.357442855] [INFO ] [alacritty] Cell size: 12 x 24
thread 'main' panicked at 'expected send event loop msg: Disconnected', alacritty_terminal/src/event_loop.rs:81:41
```

video of the bug:
https://youtu.be/AR6YWVBngPg

**Comment by chrisduerr** [comment]
Can you try the latest master?
