### ISSUE TITLE
Crash when resizing

### ISSUE THREAD

**Issue by amacfie** [alacritty/alacritty#5284]
When I resize an alacritty window with the mutt inbox loaded inside tmux, it crashes.

### System

OS: Linux
Version: 0.8.0
Linux/BSD: X11, xmonad

### Logs

```
thread 'PTY reader' panicked at 'index out of bounds: the len is 99 but the index is 99', /build/source/alacritty_terminal/src/term/mod.rs:778:17
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: <alacritty_terminal::term::Term<T> as alacritty_terminal::ansi::Handler>::input
   4: vte::Parser::perform_action
   5: alacritty_terminal::event_loop::EventLoop<T,U>::pty_read
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'expected send event loop msg: Disconnected', alacritty_terminal/src/event_loop.rs:81:41
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <alacritty_terminal::event_loop::Notifier as alacritty_terminal::event::OnResize>::on_resize
   4: alacritty::event::Processor<N>::submit_display_update
   5: alacritty::event::Processor<N>::run::{{closure}}.3530
   6: winit::platform_impl::platform::EventLoop<T>::run_return
   7: alacritty::event::Processor<N>::run
   8: alacritty::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by chrisduerr** [comment]
Should be fixed with the latest master.
