### ISSUE TITLE
Panic in 'PTY reader' thread when printing large binary file to stdout

### ISSUE THREAD

**Issue by Dar13** [alacritty/alacritty#5337]
After following the `refterm` saga, I generated a large binary file via `dd` from `/dev/urandom` and tried `cat`ing it to stdout to see how fast Alacritty got through it. Instead Alacritty unexpectedly panicked in the pty reader thread.

I tried narrowing down the file to the bare minimum, but couldn't shrink it past this point and still reproduce the issue.

I'll try doing a build with debug symbols in the upcoming couple of days to get a more useful stack dump.

### System

OS: Linux (Arch Linux)
Version: alacritty 0.8.0 (a1b13e68)
DE: Gnome 40.3

### Logs
This zip contains the smallest file that still reproduces the issue in my install: [bad.zip](https://github.com/alacritty/alacritty/files/6833589/bad.zip)
```
$ env RUST_BACKTRACE=full alacritty
$ cat bad.bin
thread 'PTY reader' panicked at 'index out of bounds: the len is 120 but the index is 18446744073709551615', /build/alacritty/src/alacritty/alacritty_terminal/src/term/mod.rs:780:17
stack backtrace:
   0:     0x5611b6112e80 - <unknown>
   1:     0x5611b5fe047c - <unknown>
   2:     0x5611b61126e1 - <unknown>
   3:     0x5611b6112045 - <unknown>
   4:     0x5611b611145c - <unknown>
   5:     0x5611b6130728 - <unknown>
   6:     0x5611b613069c - <unknown>
   7:     0x5611b613064d - <unknown>
   8:     0x5611b5fddd00 - <unknown>
   9:     0x5611b5fddb91 - <unknown>
  10:     0x5611b5f4f910 - <unknown>
  11:     0x5611b5f143ce - <unknown>
  12:     0x5611b5e19de6 - <unknown>
  13:     0x5611b5e1c76e - <unknown>
  14:     0x5611b5ed4ddc - <unknown>
  15:     0x5611b614379a - <unknown>
  16:     0x7f63b4158259 - start_thread
  17:     0x7f63b3f3d5e3 - __GI___clone
  18:                0x0 - <unknown>
thread 'main' panicked at 'send event loop msg: Disconnected', /build/alacritty/src/alacritty/alacritty_terminal/src/event_loop.rs:75:40
stack backtrace:
   0:     0x5611b6112e80 - <unknown>
   1:     0x5611b5fe047c - <unknown>
   2:     0x5611b61126e1 - <unknown>
   3:     0x5611b6112045 - <unknown>
   4:     0x5611b611145c - <unknown>
   5:     0x5611b6130728 - <unknown>
   6:     0x5611b613069c - <unknown>
   7:     0x5611b613064d - <unknown>
   8:     0x5611b5fddd00 - <unknown>
   9:     0x5611b5fe4b12 - <unknown>
  10:     0x5611b5e5bf43 - <unknown>
  11:     0x5611b5eb38b4 - <unknown>
  12:     0x5611b5f2515f - <unknown>
  13:     0x5611b5f22999 - <unknown>
  14:     0x5611b5eaaf54 - <unknown>
  15:     0x5611b5f5e655 - <unknown>
  16:     0x5611b5e21403 - <unknown>
  17:     0x5611b5f595f6 - <unknown>
  18:     0x7f63b3e66b25 - __libc_start_main
  19:     0x5611b5e0806e - <unknown>
  20:                0x0 - <unknown>
```

**Comment by chrisduerr** [comment]
Can you reproduce that with the latest master?

**Comment by e00E** [comment]
I couldn't reproduce this on master or v0.8.0 . Not saying the issue doesn't exist just that it isn't deterministic. Arch Linux, Sway.

**Comment by chrisduerr** [comment]
Let me know if you can reproduce it.

**Comment by Dar13** [comment]
Reproduced on commit 7913aa557618ca0df8d5a144f9425cb9b357c815, and got a full backtrace:
```
thread 'PTY reader' panicked at 'index out of bounds: the len is 120 but the index is 18446744073709551615', <snip>/alacritty/alacritty_terminal/src/term/mod.rs:798:17
stack backtrace:
   0:     0x55a2132c6f1d - backtrace::backtrace::libunwind::trace::hc1c4a1d8ad423b97
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55a2132c6f1d - backtrace::backtrace::trace_unsynchronized::h82274781060cb056
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55a2132c6f1d - std::sys_common::backtrace::_print_fmt::h2a45d89b653a4da8
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55a2132c6f1d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41a0a93ab85e6aa1
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55a213188c8c - core::fmt::write::hdaea18585065a96d
                               at src/libcore/fmt/mod.rs:1069
   5:     0x55a2132c6784 - std::io::Write::write_fmt::h0cea70c809005252
                               at src/libstd/io/mod.rs:1504
   6:     0x55a2132c5fd5 - std::sys_common::backtrace::_print::hd95f9978cc145ca4
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55a2132c5fd5 - std::sys_common::backtrace::print::hfb25ca2291be47d0
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55a2132c5fd5 - std::panicking::default_hook::{{closure}}::h44f76cee5dc8591c
                               at src/libstd/panicking.rs:198
   9:     0x55a2132c5561 - std::panicking::default_hook::h198e1a712910f1e6
                               at src/libstd/panicking.rs:218
  10:     0x55a2132c5561 - std::panicking::rust_panic_with_hook::hc0b4730bb8013f9d
                               at src/libstd/panicking.rs:511
  11:     0x55a2132c50f8 - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x55a213186720 - core::panicking::panic_fmt::h1ac71ad045d55416
                               at src/libcore/panicking.rs:111
  13:     0x55a2131865b1 - core::panicking::panic_bounds_check::h111737a547b9c0f6
                               at src/libcore/panicking.rs:69
  14:     0x55a213123b98 - <alacritty_terminal::term::Term<T> as alacritty_terminal::ansi::Handler>::input::hda9fdfe4646f9e1c
                               at <snip>/alacritty/alacritty_terminal/src/term/mod.rs:0
  15:     0x55a2130c391e - <alacritty_terminal::ansi::Performer<H> as vte::Perform>::print::h3bd3d1d3afe5aaf6
                               at <snip>/alacritty/alacritty_terminal/src/ansi.rs:883
  16:     0x55a2130c391e - <vte::VtUtf8Receiver<P> as utf8parse::Receiver>::codepoint::h56ef73692f477775
                               at <snip>/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.10.1/src/lib.rs:60
  17:     0x55a2130c391e - utf8parse::Parser::perform_action::h011b827e66ab9095
                               at <snip>/.cargo/registry/src/github.com-1ecc6299db9ec823/utf8parse-0.2.0/src/lib.rs:72
  18:     0x55a2130c391e - utf8parse::Parser::advance::h665c402430087938
                               at <snip>/.cargo/registry/src/github.com-1ecc6299db9ec823/utf8parse-0.2.0/src/lib.rs:51
  19:     0x55a21306c8e1 - vte::Parser::process_utf8::h35a2821ded5f2d6c
                               at <snip>/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.10.1/src/lib.rs:140
  20:     0x55a21306c8e1 - vte::Parser::advance::h9671daab0f298b8f
                               at <snip>/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.10.1/src/lib.rs:115
  21:     0x55a21306c8e1 - alacritty_terminal::ansi::Processor::advance::hb11fe90ea2b45e2e
                               at <snip>/Development/alacritty/alacritty_terminal/src/ansi.rs:162
  22:     0x55a21306c8e1 - alacritty_terminal::event_loop::EventLoop<T,U>::pty_read::h2e9126d261434e55
                               at <snip>/Development/alacritty/alacritty_terminal/src/event_loop.rs:261
  23:     0x55a21306a85a - alacritty_terminal::event_loop::EventLoop<T,U>::spawn::{{closure}}::h97ce25f862964002
                               at <snip>/Development/alacritty/alacritty_terminal/src/event_loop.rs:389
  24:     0x55a21306a85a - std::sys_common::backtrace::__rust_begin_short_backtrace::hb35aca47e1944f0e
                               at <snip>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys_common/backtrace.rs:130
  25:     0x55a2130cf3b6 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::heb4fbd9e22608ee6
                               at <snip>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/mod.rs:475
  26:     0x55a2130cf3b6 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h1c101c02f6452d61
                               at <snip>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:318
  27:     0x55a2130cf3b6 - std::panicking::try::do_call::h8b6c30e94acf6e5b
                               at <snip>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:331
  28:     0x55a2130cf3b6 - std::panicking::try::ha815f77e1acdf279
                               at <snip>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:274
  29:     0x55a2130cf3b6 - std::panic::catch_unwind::h2fe0f1c1041f1b59
                               at <snip>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:394
  30:     0x55a2130cf3b6 - std::thread::Builder::spawn_unchecked::{{closure}}::h7c36999ce6643be5
                               at <snip>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/mod.rs:474
  31:     0x55a2130cf3b6 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h51115bcf4a9142b0
                               at <snip>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  32:     0x55a2132dc55a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h1f1fac7de7dd9691
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
  33:     0x55a2132dc55a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::ha031f48633a6af54
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
  34:     0x55a2132dc55a - std::sys::unix::thread::Thread::new::thread_start::h241864caf436e182
                               at src/libstd/sys/unix/thread.rs:87
  35:     0x7fb035000259 - start_thread
  36:     0x7fb034f0c5e3 - __GI___clone
  37:                0x0 - <unknown>
```

Build command: `cargo build --release`

**Comment by Dar13** [comment]
I haven't yet narrowed it how it got to this state, but the issue appears to be that `point.column` is 0 when it reaches this line:
```rust
self.grid[point.line][point.column - 1].clear_wide();
```
The `point.column - 1` causes a 64-bit unsigned integer underflow.

Following diff fixes the issue in my builds, though I'm sure it's not acceptable for merge or anything like that:
```diff
diff --git a/alacritty_terminal/src/term/mod.rs b/alacritty_terminal/src/term/mod.rs
index b560d69e..b4586beb 100644
--- a/alacritty_terminal/src/term/mod.rs
+++ b/alacritty_terminal/src/term/mod.rs
@@ -795,7 +795,8 @@ impl<T> Term<T> {
             if wide && point.column + 1 < self.columns() {
                 self.grid[point.line][point.column + 1].flags.remove(Flags::WIDE_CHAR_SPACER);
             } else {
-                self.grid[point.line][point.column - 1].clear_wide();
+                let n = point.sub(&mut self.grid, Boundary::Grid, 1);
+                self.grid[point.line][n.column].clear_wide();
             }

             // Remove leading spacers.
```

**Comment by chrisduerr** [comment]
@Dar13 Do you know how to reproduce it?

**Comment by chrisduerr** [comment]
While fixing this should be trivial, I'd **really** like to know how this edgecase can be created. I'm certainly not able to reproduce it. So I'm going to hold off on sending a patch until someone can provide repro instructions.

**Comment by Dar13** [comment]
I'm having a hard time narrowing it down to something smaller than a 12K file, but I'm still working on it. Between work and other stuff, it might take me a few days.

**Comment by e00E** [comment]
I think chrisduerr means that for him like for me the catting the file does not panic. Maybe the dimensions of the alacritty window and font size matter.

**Comment by chrisduerr** [comment]
Yes, I cannot reproduce it. I ran `cat /dev/urandom` in the primary and alt screen for 30 minutes without any luck.

So I'd ensure that you're running the version you think you're running and provide some **exact** details on what is necessary to reproduce this.

**Comment by Dar13** [comment]
> I think chrisduerr means that for him like for me the catting the file does not panic. Maybe the dimensions of the alacritty window and font size matter.

You're on to something re: alacritty window and font size, when the terminal window made wider the underflow doesn't occur. when I launch alacritty, it has the following size:
```
[2021-07-21 06:29:59.255243518] [INFO ] [alacritty] Cell size: 9 x 18
[2021-07-21 06:29:59.255290011] [INFO ] [alacritty] Padding: 2 x 2
[2021-07-21 06:29:59.255335493] [INFO ] [alacritty] Width: 1084, Height: 544
[2021-07-21 06:29:59.265294079] [INFO ] [alacritty] PTY dimensions: 30 x 120
```
I can reproduce the underflow in this size reliably.

If I make the window wider:
```
[2021-07-21 06:30:28.371629269] [INFO ] [alacritty] Padding: 4 x 4
[2021-07-21 06:30:28.371691863] [INFO ] [alacritty] Width: 2186, Height: 1088
```
then I don't see the underflow occur.

Log from running with `-vvv`: [test.log](https://github.com/alacritty/alacritty/files/6854943/test.log), the line(s) that starts with `Point column is zero!` shows that the bug has been encountered
Output from `--version`: `alacritty 0.10.0-dev (7913aa55)`
I've been using this file in particular to reproduce, I can't shrink it down anymore without the issue going away: [bad3.zip](https://github.com/alacritty/alacritty/files/6854982/bad3.zip)

If you still can't reproduce @chrisduerr, I'm fine with you ignoring/closing this issue until I find the time to get to the root cause.

**Comment by chrisduerr** [comment]
Can reproduce with 30x120 dimensions.

**Comment by chrisduerr** [comment]
It seems like this is related to insert mode, where it is possible to move a wide character to the right of the row by inserting numbers in front of it.

I believe the issue is that we do this by rotating the current line and then overwriting the existing text, however when the spacer of a wide character is rotated back to the beginning of the line and we then overwrite it, we end up trying to write to a cell that is now occupied by a wide char spacer in the first column.

I should have a fix up in a bit.

**Comment by chrisduerr** [comment]
This is a little script for reproducing the issue:

```sh
#!/bin/sh

# Write our wide char + spacer.
printf "漢"

# Enter insert mode.
printf "\e[4h"

# Go to beginning of line.
printf "\r"

# Move the wide char to the edge of the row.
for _ in $(seq 3 $(tput cols)); do
    printf "x"
done

# Write next character to the first column.
printf "\r"

# Write to the column that contains the wide char spacer.
printf "_"
```
