### ISSUE TITLE
Alacritty - SIGSEGV on startup 

### ISSUE THREAD

**Issue by StianHB** [alacritty/alacritty#5365]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

VMware Workstation Player 16
OS: Fedora 34 , running i3 version 4.19.2
Version: alacritty 0.10.0-dev (78795522) (The same SEGV happens with alacritty 0.8.0 from the Fedora repo) 
Linux/BSD: X11
```
$ lspci | grep VGA
00:0f.0 VGA compatible controller: VMware SVGA II Adapter
$ glxinfo | grep -i vendor
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    Vendor: VMware, Inc. (0x15ad)
OpenGL vendor string: VMware, Inc.
```

### Logs
The crashes also happens with the config file from this repo placed in ~/.config/alacritty/alacritty.yml

Crashes: 
```
$ ./alacritty -v
Created log file at "/tmp/Alacritty-50124.log"
[2021-07-24 13:24:07.671583941] [INFO ] [alacritty_config_derive] No config file found; using default
[2021-07-24 13:24:07.671663831] [INFO ] [alacritty] Welcome to Alacritty
Segmentation fault (core dumped)
```

Font/Terminal size: `alacritty -vv`
```
$ ./alacritty -vv
Created log file at "/tmp/Alacritty-50080.log"
[2021-07-24 13:21:59.795544290] [INFO ] [alacritty_config_derive] No config file found; using default
[2021-07-24 13:21:59.795731402] [INFO ] [alacritty] Welcome to Alacritty
[2021-07-24 13:21:59.804137674] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-07-24 13:21:59.804781917] [DEBUG] [alacritty] Estimated DPR: 1
[2021-07-24 13:21:59.804823776] [DEBUG] [alacritty] Estimated window size: None
[2021-07-24 13:21:59.804850015] [DEBUG] [alacritty] Estimated cell size: 9 x 18
Segmentation fault (core dumped)
```
Keyboard and bindings: `alacritty --print-events`
```
$ ./alacritty --print-events
Created log file at "/tmp/Alacritty-50097.log"
[2021-07-24 13:23:00.023394214] [INFO ] [alacritty_config_derive] No config file found; using default
[2021-07-24 13:23:00.023496116] [INFO ] [alacritty] Welcome to Alacritty
Segmentation fault (core dumped)
```

### GDB output
```
(gdb) r
Starting program: /home/stianb/dev/alacritty/target/release/alacritty 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
Missing separate debuginfos, use: dnf debuginfo-install elfutils-libelf-0.185-2.fc34.x86_64 expat-2.4.1-1.fc34.x86_64 libX11-1.7.0-3.fc34.x86_64 libX11-xcb-1.7.0-3.fc34.x86_64 libXcursor-1.2.0-5.fc34.x86_64 libXext-1.3.4-6.fc34.x86_64 libXfixes-6.0.0-1.fc34.x86_64 libXi-1.7.10-6.fc34.x86_64 libXrandr-1.5.2-6.fc34.x86_64 libXrender-0.9.10-14.fc34.x86_64 libXxf86vm-1.1.4-16.fc34.x86_64 libdrm-2.4.107-1.fc34.x86_64 libedit-3.1-38.20210714cvs.fc34.x86_64 libffi-3.1-28.fc34.x86_64 libglvnd-1.3.3-1.fc34.x86_64 libglvnd-glx-1.3.3-1.fc34.x86_64 libselinux-3.2-1.fc34.x86_64 libxshmfence-1.3-8.fc34.x86_64 llvm-libs-12.0.0-2.fc34.x86_64 mesa-dri-drivers-21.1.5-1.fc34.x86_64 mesa-libGL-21.1.5-1.fc34.x86_64 mesa-libglapi-21.1.5-1.fc34.x86_64 ncurses-libs-6.2-4.20200222.fc34.x86_64 pcre2-10.36-4.fc34.x86_64 vulkan-loader-1.2.162.0-2.fc34.x86_64
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007fffe9c669c0 in __glXGetDrawableAttribute.part.0 () from /lib64/libGLX_mesa.so.0
#2  0x00005555556c32c9 in glutin_glx_sys::glx::Glx::QueryDrawable () at /home/stianb/dev/alacritty/target/release/build/glutin_glx_sys-58d0fa901fcd1994/out/glx_bindings.rs:549
#3  glutin::api::glx::ContextPrototype::finish () at /home/stianb/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.27.0/src/api/glx/mod.rs:386
#4  glutin::platform_impl::platform_impl::x11::Context::new_impl<alacritty::event::Event> () at /home/stianb/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.27.0/src/platform_impl/unix/x11.rs:479
#5  glutin::platform_impl::platform_impl::x11::{{impl}}::new::{{closure}}<alacritty::event::Event> () at /home/stianb/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.27.0/src/platform_impl/unix/x11.rs:426
#6  0x00005555556b880c in glutin::platform_impl::platform_impl::x11::Context::try_then_fallback<closure-0,(winit::window::Window, glutin::platform_impl::platform_impl::x11::Context)> () at /home/stianb/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.27.0/src/platform_impl/unix/x11.rs:165
#7  glutin::platform_impl::platform_impl::x11::Context::new<alacritty::event::Event> () at /home/stianb/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.27.0/src/platform_impl/unix/x11.rs:425
#8  glutin::platform_impl::platform_impl::Context::new_windowed<alacritty::event::Event> () at /home/stianb/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.27.0/src/platform_impl/unix/mod.rs:123
#9  glutin::ContextBuilder::build_windowed<glutin::context::NotCurrent,alacritty::event::Event> () at /home/stianb/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.27.0/src/windowed.rs:341
#10 alacritty::display::window::create_gl_window<alacritty::event::Event> () at alacritty/src/display/window.rs:136
#11 0x00005555556b53db in alacritty::display::window::Window::new<alacritty::event::Event> () at alacritty/src/display/window.rs:189
#12 0x000055555570ef18 in alacritty::display::Display::new<alacritty::event::Event> () at alacritty/src/display/mod.rs:243
#13 0x00005555555d58f5 in alacritty::main () at alacritty/src/main.rs:137
```

Please let me know if you need anymore info to track this down.

**Comment by chrisduerr** [comment]
Huh, that looks like a segfault in mesa. I'd assume you cannot reproduce this outside of your VM?

**Comment by StianHB** [comment]
Probably not, as the only other time I have tested Alacritty was on a machine running native Fedora 34 and it worked out of the box.

**Comment by StianHB** [comment]
I found this, https://gitlab.freedesktop.org/mesa/mesa/-/issues/4495 and tried to run glxgears on my system as well. glxgears also gives SIGSEGV, while crashing on __glXGetDrawableAttribute.part.0 () from /lib64/libGLX_mesa.so.0 so I guess the issue lies elsewhere.

**Comment by StianHB** [comment]
Disabling 3D acceleration stops Alacritty from segfaulting at start.
Sorry for opening an Issue ticket in your project.

Thank you for making an awesome terminal :)
