### ISSUE TITLE
Crash while resizing with 'index out of bounds: the len is 55 but the index mod.rs:796:17'

### ISSUE THREAD

**Issue by beeender** [alacritty/alacritty#5383]
### Description

I am not entirely sure about the preconditions, but it seems to be related to the font.

- Start `nvim` in the `alacrity` and open some file to edit
- Keep resizing the window multiple times
- crash

Building alacrity with below diff seems fixing the issue:

```diff
diff --git a/alacritty_terminal/src/term/mod.rs b/alacritty_terminal/src/term/mod.rs
index 8013f6c5..1808f3aa 100644
--- a/alacritty_terminal/src/term/mod.rs
+++ b/alacritty_terminal/src/term/mod.rs
@@ -792,7 +792,7 @@ impl<T> Term<T> {
             // Remove wide char and spacer.
             let wide = cursor_cell.flags.contains(Flags::WIDE_CHAR);
             let point = self.grid.cursor.point;
-            if wide && point.column <= self.last_column() {
+            if wide && point.column < self.last_column() {
                 self.grid[point.line][point.column + 1].flags.remove(Flags::WIDE_CHAR_SPACER);
             } else if point.column > 0 {
                 self.grid[point.line][point.column - 1].clear_wide();
```

### System

OS: Linux archlinux
Version: `alacritty --version` output
```
➜  glrnvim git:(cfg_dir) "/home/cc/repo/alacritty/target/debug/alacritty" --version
alacritty 0.10.0-dev (259e7c7a)
```
The same issue happens to `0.8.0` as well.

Linux: X11, awesomeWM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`

```
➜  glrnvim git:(cfg_dir) "/home/cc/repo/alacritty/target/debug/alacritty" "--config-file" "/tmp/.tmpagTGPw" -vv                                                              
Created log file at "/tmp/Alacritty-617710.log"
[2021-08-01 23:54:37.055820781] [INFO ] [alacritty] Welcome to Alacritty
[2021-08-01 23:54:37.055886081] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/tmp/.tmpagTGPw"
[2021-08-01 23:54:37.065258017] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: DEFAULT | TARGET_NORMAL, render_mode: "Normal", lcd_filter: 1 }
[2021-08-01 23:54:37.066585964] [DEBUG] [alacritty] Estimated DPR: 1.1666666666666667
[2021-08-01 23:54:37.066618704] [DEBUG] [alacritty] Estimated window size: None
[2021-08-01 23:54:37.066638484] [DEBUG] [alacritty] Estimated cell size: 11 x 24
[2021-08-01 23:54:37.104108239] [INFO ] [alacritty] Device pixel ratio: 1.1666666666666667
[2021-08-01 23:54:37.106530643] [INFO ] [alacritty] Initializing glyph cache...
[2021-08-01 23:54:37.107644480] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: DEFAULT | TARGET_NORMAL, render_mode: "Normal", lcd_filter: 1 }
[2021-08-01 23:54:37.109805064] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: DEFAULT | TARGET_NORMAL, render_mode: "Normal", lcd_filter: 1 }
[2021-08-01 23:54:37.111897769] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP, render_mode: "Normal", lcd_filter: 1 }
[2021-08-01 23:54:37.114033674] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP, render_mode: "Normal", lcd_filter: 1 }
[2021-08-01 23:54:37.125275035] [INFO ] [alacritty] ... finished initializing glyph cache in 0.018700132s
[2021-08-01 23:54:37.125337345] [INFO ] [alacritty] Cell size: 11 x 24
[2021-08-01 23:54:37.125360465] [INFO ] [alacritty] Padding: 0 x 0
[2021-08-01 23:54:37.125376955] [INFO ] [alacritty] Width: 800, Height: 600
[2021-08-01 23:54:37.139958488] [INFO ] [alacritty] PTY dimensions: 25 x 72
[2021-08-01 23:54:37.142642211] [INFO ] [alacritty] Initialisation complete
[2021-08-01 23:54:37.157275644] [DEBUG] [alacritty_terminal] New num_cols is 138 and num_lines is 59
[2021-08-01 23:54:37.162382431] [INFO ] [alacritty] Padding: 0 x 0
[2021-08-01 23:54:37.162435981] [INFO ] [alacritty] Width: 1521, Height: 1420
[2021-08-01 23:54:37.229797570] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1',],['~','/','r','e','p','o','/','g','l','r','n','v','i','m',],] at line 947
[2021-08-01 23:54:37.242825907] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: DEFAULT | TARGET_NORMAL, render_mode: "Normal", lcd_filter: 1 }
```

config file:
```
➜  glrnvim git:(cfg_dir) cat /tmp/.tmpagTGPw
---
font:
  size: 12
  normal:
    family: FiraCode Nerd Font
key_bindings:
  - key: Z
    mods: Control
    action: None%
```

Keyboard and bindings: `alacritty --print-events`

```
➜  glrnvim git:(cfg_dir) RUST_BACKTRACE=full glrnvim src/main.rs
➜  glrnvim git:(cfg_dir) thread 'PTY reader' panicked at 'index out of bounds: the len is 55 but the index is 55', /home/cc/repo/alacritty/alacritty_terminal/src/term/mod.rs:796:17
stack backtrace:
   0:     0x55646c932b50 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55646c932b50 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55646c932b50 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55646c932b50 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55646c95922f - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x55646c92f3b5 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x55646c934dbb - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55646c934dbb - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55646c934dbb - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x55646c93488d - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x55646c9353cd - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x55646c934f67 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
  12:     0x55646c932fec - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55646c934ec9 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x55646bd656e1 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:     0x55646bd656a2 - core::panicking::panic_bounds_check::hab5cb3227e3c0b2e
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:69:5
  16:     0x55646c2f8d5e - <usize as core::slice::index::SliceIndex<[T]>>::index_mut::hb72374d84ac6ece5
                               at /home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:190:14
  17:     0x55646c305597 - core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut::h69534b4ea7d6b6a6
                               at /home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:26:9
  18:     0x55646c2f39af - <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut::h7a9b19dc6f1f5800
                               at /home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2396:9
  19:     0x55646c2e61eb - <alacritty_terminal::grid::row::Row<T> as core::ops::index::IndexMut<alacritty_terminal::index::Column>>::index_mut::haa541a19edfccaf0
                               at /home/cc/repo/alacritty/alacritty_terminal/src/grid/row.rs:200:14
  20:     0x55646bdc6e38 - alacritty_terminal::term::Term<T>::write_at_cursor::hc5ffa5bf625c100f
                               at /home/cc/repo/alacritty/alacritty_terminal/src/term/mod.rs:796:17
  21:     0x55646bdc6e38 - <alacritty_terminal::term::Term<T> as alacritty_terminal::ansi::Handler>::input::h2f61f9078f895d9e
                               at /home/cc/repo/alacritty/alacritty_terminal/src/term/mod.rs:882:13
  22:     0x55646bdbd04f - <alacritty_terminal::ansi::Performer<H> as vte::Perform>::print::hbcd717aa19f559d2
                               at /home/cc/repo/alacritty/alacritty_terminal/src/ansi.rs:883:9
  23:     0x55646be8b091 - vte::Parser::perform_action::h4c7390b7407b747e
                               at /home/cc/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.10.1/src/lib.rs:219:30
  24:     0x55646be8bb3f - vte::Parser::perform_state_change::h4eb8f6501d07c0f1
                               at /home/cc/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.10.1/src/lib.rs:162:17
  25:     0x55646be8bdb9 - vte::Parser::advance::h0879117775f5eca3
                               at /home/cc/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.10.1/src/lib.rs:130:9
  26:     0x55646bd8cb1f - alacritty_terminal::ansi::Processor::advance::ha9a722afdf25b779
                               at /home/cc/repo/alacritty/alacritty_terminal/src/ansi.rs:162:13
  27:     0x55646bf275a2 - alacritty_terminal::event_loop::EventLoop<T,U>::pty_read::h0505034dd642168b
                               at /home/cc/repo/alacritty/alacritty_terminal/src/event_loop.rs:261:17
  28:     0x55646bf26578 - alacritty_terminal::event_loop::EventLoop<T,U>::spawn::{{closure}}::hbbf561838a26e0ef
                               at /home/cc/repo/alacritty/alacritty_terminal/src/event_loop.rs:389:51
  29:     0x55646bf2a18f - std::sys_common::backtrace::__rust_begin_short_backtrace::hb216a97c2ea7530d
                               at /home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  30:     0x55646bd9f3af - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hb4df168bb6c50466
                               at /home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:481:17
  31:     0x55646bd88f5e - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h0a5d15dcffb3da73
                               at /home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  32:     0x55646bf2ac4d - std::panicking::try::do_call::hbdd68a542924ef46
                               at /home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  33:     0x55646bf4419d - __rust_try
  34:     0x55646bf2aa1e - std::panicking::try::h8d0bcdb909dfab04
                               at /home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  35:     0x55646bd9dbaf - std::panic::catch_unwind::haf24685464a52511
                               at /home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  36:     0x55646bd9f193 - std::thread::Builder::spawn_unchecked::{{closure}}::h60dcd8ca89ec2e35
                               at /home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:480:30
  37:     0x55646bda2d1e - core::ops::function::FnOnce::call_once{{vtable.shim}}::he532f9b326a176f1
                               at /home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  38:     0x55646c93a9da - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h75c2ca1daad47228
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
  39:     0x55646c93a9da - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdf9f8afc9d34e311
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
  40:     0x55646c93a9da - std::sys::unix::thread::Thread::new::thread_start::hc238bac7748b195d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys/unix/thread.rs:71:17
  41:     0x7f4094de8259 - start_thread
  42:     0x7f4094bcd5e3 - __GI___clone
  43:                0x0 - <unknown>
thread 'main' panicked at 'expected send event loop msg: Disconnected', alacritty_terminal/src/event_loop.rs:84:41
stack backtrace:
   0:     0x55646c932b50 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55646c932b50 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55646c932b50 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55646c932b50 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55646c95922f - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x55646c92f3b5 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x55646c934dbb - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55646c934dbb - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55646c934dbb - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x55646c93488d - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x55646c9353cd - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x55646c934f67 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
  12:     0x55646c932fec - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55646c934ec9 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x55646bd656e1 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:     0x55646bd657d3 - core::result::unwrap_failed::hcbdf25d28ce8f0ca
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
  16:     0x55646c2f5841 - core::result::Result<T,E>::expect::hf6d9bd7374cf5928
                               at /home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:997:23
  17:     0x55646c304f7d - <alacritty_terminal::event_loop::Notifier as alacritty_terminal::event::OnResize>::on_resize::h11bfd31370f49c11
                               at /home/cc/repo/alacritty/alacritty_terminal/src/event_loop.rs:84:9
  18:     0x55646bfd2080 - alacritty::display::Display::handle_update::h4025045ba237a138
                               at /home/cc/repo/alacritty/alacritty/src/display/mod.rs:460:9
  19:     0x55646bf65f16 - alacritty::event::Processor<N>::submit_display_update::h6288c7f28d400f0f
                               at /home/cc/repo/alacritty/alacritty/src/event.rs:1470:9
  20:     0x55646bf63b9a - alacritty::event::Processor<N>::run::{{closure}}::hfc6441d65dbead0c
                               at /home/cc/repo/alacritty/alacritty/src/event.rs:1145:17
  21:     0x55646be78f4e - winit::platform_impl::platform::sticky_exit_callback::h781c0f8f27e743c4
                               at /home/cc/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:736:5
  22:     0x55646bdedb06 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::hfc0951bf91779c95
                               at /home/cc/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:330:17
  23:     0x55646be78423 - winit::platform_impl::platform::EventLoop<T>::run_return::h3dcb3bf94b39ad07
                               at /home/cc/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:645:56
  24:     0x55646bd88fd3 - <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return::h4ad1a23a1baff436
                               at /home/cc/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform/run_return.rs:56:9
  25:     0x55646bf62f02 - alacritty::event::Processor<N>::run::h3a5ae85f104f5c39
                               at /home/cc/repo/alacritty/alacritty/src/event.rs:1067:9
  26:     0x55646be2b9cc - alacritty::run::h3f1dd7f5e06ebb13
                               at /home/cc/repo/alacritty/alacritty/src/main.rs:204:5
  27:     0x55646be2a735 - alacritty::main::h55addabea8c46846
                               at /home/cc/repo/alacritty/alacritty/src/main.rs:102:23
  28:     0x55646bda357b - core::ops::function::FnOnce::call_once::h489d095ea8ece64c
                               at /home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  29:     0x55646bf2a12e - std::sys_common::backtrace::__rust_begin_short_backtrace::h94d5bc4930bef9fd
                               at /home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  30:     0x55646bfbc531 - std::rt::lang_start::{{closure}}::ha37bce41e055dff5
                               at /home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:49:18
  31:     0x55646c9357ca - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc4354216bf39217c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
  32:     0x55646c9357ca - std::panicking::try::do_call::hb68eb312780385cf
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  33:     0x55646c9357ca - std::panicking::try::h22b8e08595060b8b
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  34:     0x55646c9357ca - std::panic::catch_unwind::hc64f1a6a0e71b1fc
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  35:     0x55646c9357ca - std::rt::lang_start_internal::h4461fc58637f04f8
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  36:     0x55646bfbc510 - std::rt::lang_start::h722a313baea2abe0
                               at /home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:48:5
  37:     0x55646be3c88c - main
  38:     0x7f4094af6b25 - __libc_start_main
  39:     0x55646bd65e7e - _start
  40:                0x0 - <unknown>

```

**Comment by chrisduerr** [comment]
Your patch is correct, do you want to send a PR?

**Comment by chrisduerr** [comment]
Have submitted a patch myself to speed up the process. Thanks for the report.
