### ISSUE TITLE
Panic on launch with unsupported OpenGL version

### ISSUE THREAD

**Issue by xobs** [alacritty/alacritty#5413]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Ubuntu 20.04 via WSL2
Version: alacritty 0.9.0
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

```
user@Ondo:~$ alacritty -vv
Created log file at "/tmp/Alacritty-32734.log"
[2021-08-13 18:36:08.903546814] [INFO ] [alacritty_config_derive] No config file found; using default
[2021-08-13 18:36:08.903644657] [INFO ] [alacritty] Welcome to Alacritty
[2021-08-13 18:36:08.906380102] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-08-13 18:36:08.906678851] [DEBUG] [alacritty] Estimated DPR: 1
[2021-08-13 18:36:08.906708096] [DEBUG] [alacritty] Estimated window size: None
[2021-08-13 18:36:08.906730087] [DEBUG] [alacritty] Estimated cell size: 9 x 18
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/api/egl/mod.rs:422:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
user@Ondo:~$ alacritty  --print-events
Created log file at "/tmp/Alacritty-32736.log"
[2021-08-13 18:36:22.274541902] [INFO ] [alacritty_config_derive] No config file found; using default
[2021-08-13 18:36:22.274630147] [INFO ] [alacritty] Welcome to Alacritty
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/api/egl/mod.rs:422:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
user@Ondo:~$ cat /tmp/Alacritty-32736.log
[2021-08-13 18:36:22.274541902] [INFO ] [alacritty_config_derive] No config file found; using default
[2021-08-13 18:36:22.274630147] [INFO ] [alacritty] Welcome to Alacritty
user@Ondo:~$
```

I'm using WSL2 which does have a valid OpenGL driver.  `glmark2`  works, although `glmark2-es2` does not.

`glxgears -info` shows that I'm running `GL_VERSION 3.1 Mesa 20.2.6`, which admittedly is not the GL version 3.3 that is stated as a requirement.

At the very least, there should be a better error message than:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/api/egl/mod.rs:422:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by chrisduerr** [comment]
Unsupported OpenGL versions cause a crash because they're unsupported. Shouldn't be much of a surprise really.
