### ISSUE TITLE
Panic on font initialization

### ISSUE THREAD

**Issue by rayslava** [alacritty/alacritty#5686]
alacritty 0.9.0 panics on start.
Apparently this is related to my system-wide font setup, but I'm not sure where to check that
```
$ RUST_BACKTRACE=full alacritty --config-file=/dev/null -vv                                                                                     
Created log file at "/tmp/Alacritty-31353.log"
[2021-12-14 17:05:31.620035931] [INFO ] [alacritty] Welcome to Alacritty
[2021-12-14 17:05:31.620078781] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/dev/null"
[2021-12-14 17:05:31.626064144] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-12-14 17:05:31.626585822] [DEBUG] [alacritty] Estimated DPR: 1
[2021-12-14 17:05:31.626595119] [DEBUG] [alacritty] Estimated window size: None
[2021-12-14 17:05:31.626599307] [DEBUG] [alacritty] Estimated cell size: 9 x 18
[2021-12-14 17:05:31.657174707] [INFO ] [alacritty] Device pixel ratio: 1
[2021-12-14 17:05:31.659307045] [INFO ] [alacritty] Initializing glyph cache...
[2021-12-14 17:05:31.662435672] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-12-14 17:05:31.665608280] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-12-14 17:05:31.668656215] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Oblique, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-12-14 17:05:31.671713187] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Oblique, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
thread 'main' panicked at 'attempt to create unaligned or null slice', /rustc/1.57.0/library/core/src/slice/raw.rs:89:5
stack backtrace:
   0:     0x5572e0631c0a - std::backtrace_rs::backtrace::libunwind::trace::hd55e07c245669fc6
                               at /rustc/1.57.0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5572e0631c0a - std::backtrace_rs::backtrace::trace_unsynchronized::h469354ec750ea2c5
                               at /rustc/1.57.0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5572e0631c0a - std::sys_common::backtrace::_print_fmt::hbff708d0afe31558
                               at /rustc/1.57.0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5572e0631c0a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7fb705d6dbc61f4a
                               at /rustc/1.57.0/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5572e057a09f - core::fmt::write::h056cdd7a9fa2aa0b
                               at /rustc/1.57.0/library/core/src/fmt/mod.rs:1163:17
   5:     0x5572e06301a4 - std::io::Write::write_fmt::h57be7f97afc7c30d
                               at /rustc/1.57.0/library/std/src/io/mod.rs:1696:15
   6:     0x5572e0630a0c - std::sys_common::backtrace::_print::h3b7dd2fe84524fa4
                               at /rustc/1.57.0/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5572e0630a0c - std::sys_common::backtrace::print::h1459667a96fa2462
                               at /rustc/1.57.0/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5572e0630a0c - std::panicking::default_hook::{{closure}}::hbfbb65b524c3de05
                               at /rustc/1.57.0/library/std/src/panicking.rs:210:50
   9:     0x5572e062fa8a - std::panicking::default_hook::h06f8dae55170dc57
                               at /rustc/1.57.0/library/std/src/panicking.rs:227:9
  10:     0x5572e062fa8a - std::panicking::rust_panic_with_hook::h1abc1d5ecc9b50b5
                               at /rustc/1.57.0/library/std/src/panicking.rs:624:17
  11:     0x5572e0655846 - std::panicking::begin_panic_handler::{{closure}}::he488f8cc94ce3547
                               at /rustc/1.57.0/library/std/src/panicking.rs:519:13
  12:     0x5572e06557e6 - std::sys_common::backtrace::__rust_end_short_backtrace::h19598e3fa618f1a6
                               at /rustc/1.57.0/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x5572e06557a2 - rust_begin_unwind
                               at /rustc/1.57.0/library/std/src/panicking.rs:517:5
  14:     0x5572e03cc730 - core::panicking::panic_fmt::h5ce04b9827ee7302
                               at /rustc/1.57.0/library/core/src/panicking.rs:100:14
  15:     0x5572e03cc67c - core::panicking::panic::hbfbb78a01b3bcb8f
                               at /rustc/1.57.0/library/core/src/panicking.rs:50:5
  16:     0x5572e058c884 - crossfont::ft::FreeTypeRasterizer::get_rendered_glyph::hdf1a8e6d7d085ba0
  17:     0x5572e058c884 - <crossfont::ft::FreeTypeRasterizer as crossfont::Rasterize>::get_glyph::h534e0cf78dc0f553
                               at /var/tmp/portage/x11-terms/alacritty-0.9.0-r1/work/cargo_home/gentoo/crossfont-0.3.1/src/ft/mod.rs:176:9
  18:     0x5572e041f70b - alacritty::renderer::GlyphCache::get::h2748551737a1c1a7
                               at /var/tmp/portage/x11-terms/alacritty-0.9.0-r1/work/alacritty-0.9.0/alacritty/src/renderer/mod.rs:270:27
  19:     0x5572e041f70b - alacritty::renderer::GlyphCache::load_glyphs_for_font::h845c8e69fec3372b
                               at /var/tmp/portage/x11-terms/alacritty-0.9.0-r1/work/alacritty-0.9.0/alacritty/src/renderer/mod.rs:182:13
  20:     0x5572e04f4fbc - alacritty::renderer::GlyphCache::load_common_glyphs::h205e929518d10000
                               at /var/tmp/portage/x11-terms/alacritty-0.9.0-r1/work/alacritty-0.9.0/alacritty/src/renderer/mod.rs:366:9
  21:     0x5572e04f4fbc - alacritty::renderer::GlyphCache::new::hf2b6db5cdfa8d524
                               at /var/tmp/portage/x11-terms/alacritty-0.9.0-r1/work/alacritty-0.9.0/alacritty/src/renderer/mod.rs:172:9
  22:     0x5572e04f4fbc - alacritty::display::Display::new_glyph_cache::{{closure}}::hf29ff68c99c7ab29
                               at /var/tmp/portage/x11-terms/alacritty-0.9.0-r1/work/alacritty-0.9.0/alacritty/src/display/mod.rs:369:48
  23:     0x5572e04f4fbc - alacritty::renderer::QuadRenderer::with_loader::h99cf8fcb1557a164
                               at /var/tmp/portage/x11-terms/alacritty-0.9.0-r1/work/alacritty-0.9.0/alacritty/src/renderer/mod.rs:727:9
  24:     0x5572e04f4fbc - alacritty::display::Display::new_glyph_cache::h6b7ff53c884aca4f
                               at /var/tmp/portage/x11-terms/alacritty-0.9.0-r1/work/alacritty-0.9.0/alacritty/src/display/mod.rs:369:17
  25:     0x5572e04f4fbc - alacritty::display::Display::new::h451a839b96b4e82e
                               at /var/tmp/portage/x11-terms/alacritty-0.9.0-r1/work/alacritty-0.9.0/alacritty/src/display/mod.rs:257:13
  26:     0x5572e04f4fbc - alacritty::run::hf3441589c6a49261
                               at /var/tmp/portage/x11-terms/alacritty-0.9.0-r1/work/alacritty-0.9.0/alacritty/src/main.rs:137:19
  27:     0x5572e04f4fbc - alacritty::main::ha9baf5a49476839a
                               at /var/tmp/portage/x11-terms/alacritty-0.9.0-r1/work/alacritty-0.9.0/alacritty/src/main.rs:102:23
  28:     0x5572e03ee073 - core::ops::function::FnOnce::call_once::hb55921957c038d51
                               at /rustc/1.57.0/library/core/src/ops/function.rs:227:5
  29:     0x5572e03ee073 - std::sys_common::backtrace::__rust_begin_short_backtrace::hced77d0b7dcaa9d7
                               at /rustc/1.57.0/library/std/src/sys_common/backtrace.rs:123:18
  30:     0x5572e04ef42e - main
  31:     0x7f65c73402fa - __libc_start_call_main
  32:     0x7f65c73403a8 - __libc_start_main_alias_1
  33:     0x5572e03df551 - _start
  34:                0x0 - <unknown>
```

**Comment by chrisduerr** [comment]
Unfortunately this is missing the most interesting parts of the backtrace. Did you change it or why is the location missing at `16`?

**Comment by rayslava** [comment]
Oh, sorry. Didn't change it, apparently that's related to `portage` build environment.
Anyway, I just performed debug rebuild from latest git:
```
[2021-12-14 18:31:58.999487408] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/dev/null"
[2021-12-14 18:31:59.006178934] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-12-14 18:31:59.006792886] [DEBUG] [alacritty] Estimated DPR: 1
[2021-12-14 18:31:59.006820367] [DEBUG] [alacritty] Estimated window size: None
[2021-12-14 18:31:59.006834093] [DEBUG] [alacritty] Estimated cell size: 9 x 18
[2021-12-14 18:31:59.041946821] [INFO ] [alacritty] Device pixel ratio: 1
[2021-12-14 18:31:59.079824983] [INFO ] [alacritty] Initializing glyph cache...
[2021-12-14 18:31:59.083204240] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-12-14 18:31:59.086475263] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-12-14 18:31:59.089666206] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Oblique, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-12-14 18:31:59.092917252] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Oblique, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
thread 'main' panicked at 'attempt to create unaligned or null slice', /rustc/1.57.0/library/core/src/slice/raw.rs:89:5
stack backtrace:
   0:     0x560fb9b3fcec - std::backtrace_rs::backtrace::libunwind::trace::hd55e07c245669fc6
                               at /rustc/1.57.0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x560fb9b3fcec - std::backtrace_rs::backtrace::trace_unsynchronized::h469354ec750ea2c5
                               at /rustc/1.57.0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560fb9b3fcec - std::sys_common::backtrace::_print_fmt::hbff708d0afe31558
                               at /rustc/1.57.0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x560fb9b3fcec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7fb705d6dbc61f4a
                               at /rustc/1.57.0/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x560fb9b6913e - core::fmt::write::h056cdd7a9fa2aa0b
                               at /rustc/1.57.0/library/core/src/fmt/mod.rs:1163:17
   5:     0x560fb9b3a8c5 - std::io::Write::write_fmt::h57be7f97afc7c30d
                               at /rustc/1.57.0/library/std/src/io/mod.rs:1696:15
   6:     0x560fb9b41cbc - std::sys_common::backtrace::_print::h3b7dd2fe84524fa4
                               at /rustc/1.57.0/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x560fb9b41cbc - std::sys_common::backtrace::print::h1459667a96fa2462
                               at /rustc/1.57.0/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x560fb9b41cbc - std::panicking::default_hook::{{closure}}::hbfbb65b524c3de05
                               at /rustc/1.57.0/library/std/src/panicking.rs:210:50
   9:     0x560fb9b41776 - std::panicking::default_hook::h06f8dae55170dc57
                               at /rustc/1.57.0/library/std/src/panicking.rs:227:9
  10:     0x560fb9b42251 - std::panicking::rust_panic_with_hook::h1abc1d5ecc9b50b5
                               at /rustc/1.57.0/library/std/src/panicking.rs:624:17
  11:     0x560fb9b41e62 - std::panicking::begin_panic_handler::{{closure}}::he488f8cc94ce3547
                               at /rustc/1.57.0/library/std/src/panicking.rs:519:13
  12:     0x560fb9b401f4 - std::sys_common::backtrace::__rust_end_short_backtrace::h19598e3fa618f1a6
                               at /rustc/1.57.0/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x560fb9b41df9 - rust_begin_unwind
                               at /rustc/1.57.0/library/std/src/panicking.rs:517:5
  14:     0x560fb8f67311 - core::panicking::panic_fmt::h5ce04b9827ee7302
                               at /rustc/1.57.0/library/core/src/panicking.rs:100:14
  15:     0x560fb8f6725d - core::panicking::panic::hbfbb78a01b3bcb8f
                               at /rustc/1.57.0/library/core/src/panicking.rs:50:5
  16:     0x560fb9b108ea - core::slice::raw::from_raw_parts::h1dcf58badcd04a2c
                               at /rustc/1.57.0/library/core/src/slice/raw.rs:89:5
  17:     0x560fb932a548 - freetype::bitmap::Bitmap::buffer::h205ceab5bf3dcd93
                               at /home/ray/.cargo/registry/src/github.com-1ecc6299db9ec823/freetype-rs-0.26.0/src/bitmap.rs:67:13
  18:     0x560fb9300ad8 - crossfont::ft::FreeTypeRasterizer::normalize_buffer::h7c65ac167d7a1f82
                               at /home/ray/.cargo/registry/src/github.com-1ecc6299db9ec823/crossfont-0.3.2/src/ft/mod.rs:439:19
  19:     0x560fb930037e - crossfont::ft::FreeTypeRasterizer::get_rendered_glyph::hdeb530a0d0188465
                               at /home/ray/.cargo/registry/src/github.com-1ecc6299db9ec823/crossfont-0.3.2/src/ft/mod.rs:399:13
  20:     0x560fb92fe5f0 - <crossfont::ft::FreeTypeRasterizer as crossfont::Rasterize>::get_glyph::h90bbdf1d0c51aa4a
                               at /home/ray/.cargo/registry/src/github.com-1ecc6299db9ec823/crossfont-0.3.2/src/ft/mod.rs:176:9
  21:     0x560fb90b5194 - alacritty::renderer::GlyphCache::get::h94d929045bc944d4
                               at /tmp/alacritty/alacritty/src/renderer/mod.rs:269:27
  22:     0x560fb90b490f - alacritty::renderer::GlyphCache::load_glyphs_for_font::h10728c5dce8243e6
                               at /tmp/alacritty/alacritty/src/renderer/mod.rs:181:13
  23:     0x560fb90b6286 - alacritty::renderer::GlyphCache::load_common_glyphs::hb32836f0fd4ffe73
                               at /tmp/alacritty/alacritty/src/renderer/mod.rs:365:9
  24:     0x560fb90b46fe - alacritty::renderer::GlyphCache::new::hbdb276ae228691dd
                               at /tmp/alacritty/alacritty/src/renderer/mod.rs:171:9
  25:     0x560fb91d8089 - alacritty::display::Display::new_glyph_cache::{{closure}}::hfe866830e2f8657b
                               at /tmp/alacritty/alacritty/src/display/mod.rs:361:48
  26:     0x560fb90b74e9 - alacritty::renderer::QuadRenderer::with_loader::h850bdf09ff65d2e8
                               at /tmp/alacritty/alacritty/src/renderer/mod.rs:722:9
  27:     0x560fb8fc2b39 - alacritty::display::Display::new_glyph_cache::h8251bc5211f68350
                               at /tmp/alacritty/alacritty/src/display/mod.rs:361:17
  28:     0x560fb91d6c8b - alacritty::display::Display::new::h0272279d784ba23d
                               at /tmp/alacritty/alacritty/src/display/mod.rs:250:13
  29:     0x560fb90b11e8 - alacritty::window_context::WindowContext::new::hf7d1a24a037f9ca7
                               at /tmp/alacritty/alacritty/src/window_context.rs:67:23
  30:     0x560fb8fd762b - alacritty::event::Processor::create_window::hd660e6a3bc663191
                               at /tmp/alacritty/alacritty/src/event.rs:1199:30
  31:     0x560fb9015de4 - alacritty::alacritty::hc2ed132e92e6ea20
                               at /tmp/alacritty/alacritty/src/main.rs:185:5
  32:     0x560fb9015122 - alacritty::main::hd855324cbee66154
                               at /tmp/alacritty/alacritty/src/main.rs:79:17
  33:     0x560fb9036b1b - core::ops::function::FnOnce::call_once::hd570fa5959db5e96
                               at /rustc/1.57.0/library/core/src/ops/function.rs:227:5
  34:     0x560fb8f8a82e - std::sys_common::backtrace::__rust_begin_short_backtrace::h91f09beb068bf452
                               at /rustc/1.57.0/library/std/src/sys_common/backtrace.rs:123:18
  35:     0x560fb901a0b1 - std::rt::lang_start::{{closure}}::h08d6e711be3092e6
                               at /rustc/1.57.0/library/std/src/rt.rs:146:18
  36:     0x560fb9b3f9cb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hec1545a9cdbf0f3a
                               at /rustc/1.57.0/library/core/src/ops/function.rs:259:13
  37:     0x560fb9b3f9cb - std::panicking::try::do_call::h74280ef2f9d691d8
                               at /rustc/1.57.0/library/std/src/panicking.rs:403:40
  38:     0x560fb9b3f9cb - std::panicking::try::h04b327616a9c9dfd
                               at /rustc/1.57.0/library/std/src/panicking.rs:367:19
  39:     0x560fb9b3f9cb - std::panic::catch_unwind::h5f1fac855b76b3de
                               at /rustc/1.57.0/library/std/src/panic.rs:133:14
  40:     0x560fb9b3f9cb - std::rt::lang_start_internal::{{closure}}::heb4674e65091e96b
                               at /rustc/1.57.0/library/std/src/rt.rs:128:48
  41:     0x560fb9b3f9cb - std::panicking::try::do_call::h226897f155c15f6b
                               at /rustc/1.57.0/library/std/src/panicking.rs:403:40
  42:     0x560fb9b3f9cb - std::panicking::try::h604b4c4879a3055e
                               at /rustc/1.57.0/library/std/src/panicking.rs:367:19
  43:     0x560fb9b3f9cb - std::panic::catch_unwind::hea2b0decacb4e90a
                               at /rustc/1.57.0/library/std/src/panic.rs:133:14
  44:     0x560fb9b3f9cb - std::rt::lang_start_internal::h09a6f7871e0b6fb3
                               at /rustc/1.57.0/library/std/src/rt.rs:128:20
  45:     0x560fb901a080 - std::rt::lang_start::hf725c8e2af651945
                               at /rustc/1.57.0/library/std/src/rt.rs:145:17
  46:     0x560fb90166dc - main
  47:     0x7effd126a2fa - __libc_start_call_main
  48:     0x7effd126a3a8 - __libc_start_main_alias_1
  49:     0x560fb8f67c31 - _start
  50:                0x0 - <unknown>
```
now backtrace leads into `freetype-rs`

**Comment by chrisduerr** [comment]
Seems like you have an emoji/bitmap font installed that is somehow malformed? Are you aware of any bitmap fonts on your system that might cause such an issue?
