### ISSUE TITLE
Alacritty failed to launch on GNU/Linux

### ISSUE THREAD

**Issue by eval-exec** [alacritty/alacritty#5851]
### System

OS: Linux
Version:alacritty 0.10.0 (8a26dee0)
Linux/BSD: KDE/plasma, Linux mufasa 5.15.18-1-lts #1 SMP Sat, 29 Jan 2022 12:13:13 +0000 x86_64 GNU/Linux

### Logs
```
❯ alacritty -vv      
Created log file at "/tmp/Alacritty-1310989.log"
[0.000553599s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/vory/.config/alacritty/alacritty.yml"
[0.112091255s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.116308563s] [DEBUG] [alacritty] Estimated DPR: 2
[0.116325772s] [DEBUG] [alacritty] Estimated window size: None
[0.116338738s] [DEBUG] [alacritty] Estimated cell size: 14 x 28
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
[0.196513090s] [INFO ] [alacritty] Device pixel ratio: 2
[0.204918688s] [INFO ] [alacritty] Initializing glyph cache...
[0.230179758s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.257935838s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.284348958s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.311140515s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.320203015s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.115259552s
[0.320354046s] [INFO ] [alacritty] Cell size: 14 x 28
[0.320371355s] [INFO ] [alacritty] Padding: 0 x 0
[0.320377874s] [INFO ] [alacritty] Width: 800, Height: 600
[0.322642556s] [INFO ] [alacritty] PTY dimensions: 21 x 57
[0.327489710s] [INFO ] [alacritty] Initialisation complete
[0.332332602s] [DEBUG] [alacritty_terminal] New num_cols is 274 and num_lines is 77
[0.334370894s] [INFO ] [alacritty] Padding: 0 x 0
[0.334391471s] [INFO ] [alacritty] Width: 3840, Height: 2160
X connection to :0 broken (explicit kill or server shutdown).
```

**Comment by chrisduerr** [comment]
Running inside of a VM or any other special circumstances?

**Comment by nitingupta910** [comment]
I'm running into a similar issue where alacritty is failing to launch:

```
$ alacritty -vv
Created log file at "/tmp/Alacritty-92269.log"
[0.000145718s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.016888278s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.019049671s] [DEBUG] [alacritty] Estimated DPR: 1
[0.019098635s] [DEBUG] [alacritty] Estimated window size: None
[0.019109055s] [DEBUG] [alacritty] Estimated cell size: 9 x 18
[0.103790621s] [INFO ] [alacritty] Device pixel ratio: 1
[0.104821187s] [INFO ] [alacritty] Initializing glyph cache...
[0.107009271s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.109735672s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.112566453s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Oblique, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.115454161s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Oblique, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.119916925s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.015069167s
[0.119937314s] [INFO ] [alacritty] Cell size: 9 x 18
[0.119944908s] [INFO ] [alacritty] Padding: 0 x 0
[0.119950098s] [INFO ] [alacritty] Width: 800, Height: 600
[0.120947170s] [INFO ] [alacritty] PTY dimensions: 33 x 88
[0.123493959s] [INFO ] [alacritty] Initialisation complete
[destroyed object]: error 7: failed to import supplied dmabufs: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a 
[0.160423960s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-92269.log"
```

I'm trying to run it on a native Linux system (not in a VM)

**Comment by nitingupta910** [comment]
I compiled alcritty in debug mode and here's the output with RUST_BACKTRACE=full:

```
$ RUST_BACKTRACE=full alacritty 
[destroyed object]: error 7: failed to import supplied dmabufs: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a 
thread 'main' panicked at 'failed to dispatch wayland event queue: Os { code: 71, kind: Uncategorized, message: "Protocol error" }', /home/niting/.cargo/registry/src/github.com-1ecc6299db9ec823/alacritty-0.10.0/src/event.rs:1285:30
stack backtrace:
   0:     0x5636d084b75c - std::backtrace_rs::backtrace::libunwind::trace::h09f7e4e089375279
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5636d084b75c - std::backtrace_rs::backtrace::trace_unsynchronized::h1ec96f1c7087094e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5636d084b75c - std::sys_common::backtrace::_print_fmt::h317b71fc9a5cf964
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5636d084b75c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he3555b48e7dfe7f0
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5636d087225c - core::fmt::write::h513b07ca38f4fb1b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17
   5:     0x5636d0846745 - std::io::Write::write_fmt::haf8c932b52111354
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15
   6:     0x5636d084d4c0 - std::sys_common::backtrace::_print::h195c38364780a303
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5636d084d4c0 - std::sys_common::backtrace::print::hc09dfdea923b6730
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5636d084d4c0 - std::panicking::default_hook::{{closure}}::hb2e38ec0d91046a3
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:211:50
   9:     0x5636d084d075 - std::panicking::default_hook::h60284635b0ad54a8
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:228:9
  10:     0x5636d084db74 - std::panicking::rust_panic_with_hook::ha677a669fb275654
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:606:17
  11:     0x5636d084d650 - std::panicking::begin_panic_handler::{{closure}}::h976246fb95d93c31
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:502:13
  12:     0x5636d084bc04 - std::sys_common::backtrace::__rust_end_short_backtrace::h38077ee5b7b9f99a
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x5636d084d5b9 - rust_begin_unwind
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
  14:     0x5636cfd1b841 - core::panicking::panic_fmt::h35f3a62252ba0fd2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
  15:     0x5636cfd1b933 - core::result::unwrap_failed::hb53671404b9e33c2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
  16:     0x5636cfeb22af - core::result::Result<T,E>::expect::he0ff83616096eb66
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1255:23
  17:     0x5636cff1771a - alacritty::event::Processor::run::{{closure}}::h2f3591bf1c04a7f0
                               at /home/niting/.cargo/registry/src/github.com-1ecc6299db9ec823/alacritty-0.10.0/src/event.rs:1283:25
  18:     0x5636cfdb7532 - winit::platform_impl::platform::sticky_exit_callback::h96af2fda7a453198
                               at /home/niting/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/mod.rs:753:5
  19:     0x5636cff936b9 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return::h8713228bce8f86bf
                               at /home/niting/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/wayland/event_loop/mod.rs:406:13
  20:     0x5636cfdb690f - winit::platform_impl::platform::EventLoop<T>::run_return::h0a8f85a0417e01a5
                               at /home/niting/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/mod.rs:662:56
  21:     0x5636cfe16b63 - <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return::h4b4eaef7358a18bd
                               at /home/niting/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform/run_return.rs:56:9
  22:     0x5636cff17195 - alacritty::event::Processor::run::h0995d9cd59e65860
                               at /home/niting/.cargo/registry/src/github.com-1ecc6299db9ec823/alacritty-0.10.0/src/event.rs:1238:9
  23:     0x5636cfdc1ad0 - alacritty::alacritty::h218f11f7565b2ed3
                               at /home/niting/.cargo/registry/src/github.com-1ecc6299db9ec823/alacritty-0.10.0/src/main.rs:193:5
  24:     0x5636cfdc0902 - alacritty::main::hb2160978046327b2
                               at /home/niting/.cargo/registry/src/github.com-1ecc6299db9ec823/alacritty-0.10.0/src/main.rs:79:17
  25:     0x5636cfd7407b - core::ops::function::FnOnce::call_once::h3f45cac71dcbed78
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
  26:     0x5636cfdaf1ae - std::sys_common::backtrace::__rust_begin_short_backtrace::h1a94de44596e5fc7
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:123:18
  27:     0x5636cfd71ee1 - std::rt::lang_start::{{closure}}::h256077fdc7c09484
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:145:18
  28:     0x5636d084b3eb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7e688d7cdfeb7e00
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:259:13
  29:     0x5636d084b3eb - std::panicking::try::do_call::h4be824d2350b44c9
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  30:     0x5636d084b3eb - std::panicking::try::h0a6fc7affbe5088d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  31:     0x5636d084b3eb - std::panic::catch_unwind::h22c320f732ec805e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  32:     0x5636d084b3eb - std::rt::lang_start_internal::{{closure}}::hd38309c108fe679d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:48
  33:     0x5636d084b3eb - std::panicking::try::do_call::h8fcaf501f097a28e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  34:     0x5636d084b3eb - std::panicking::try::h20e906825f98acc1
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  35:     0x5636d084b3eb - std::panic::catch_unwind::h8c5234dc632124ef
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  36:     0x5636d084b3eb - std::rt::lang_start_internal::hc4dd8cd3ec4518c2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:20
  37:     0x5636cfd71eb0 - std::rt::lang_start::h0ec8e6b3f07a7f3e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:144:17
  38:     0x5636cfdd040c - main
  39:     0x7faaf9430fd0 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  40:     0x7faaf943107d - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:409:3
  41:     0x5636cfd1c005 - _start
  42:                0x0 - <unknown>
```

FYI, I'm running Wayland:

```
$ echo $XDG_SESSION_TYPE 
wayland
```

OpenGL render:
```
$ glxinfo | grep "OpenGL renderer"
OpenGL renderer string: AMD Radeon Pro W6600 (DIMGREY_CAVEFISH, DRM 3.42.0, 5.15.0-18-generic, LLVM 12.0.1)
```

OS: Ubuntu 22.04

**Comment by kchibisov** [comment]
That seems like mesa is acting up, since dmabufs importing is up to it.

**Comment by eval-exec** [comment]
> Running inside of a VM or any other special circumstances?

No, I run alacritty  on host machine  ( XPS 15 7590 ) directly. 
I can't reproduce this problem after I upgrade nvidia driver for linux-lts to `1:510.47.03-2`, really doubtful.
