### ISSUE TITLE
Fails to parse TermInfo in a non-login session on Wayland

### ISSUE THREAD

**Issue by op** [alacritty/alacritty#5927]
If I launch alacritty from the desktop and do Ctrl-r (for backwards search), I get a stacktrace.
If I launch zsh within alacritty, Ctrl-r works fine.

Having just switched to Wayland and GNOME at the same time (which also made me upgrade Alacritty), I'm unsure what caused this.

### System

OS: Linux
Version:  alacritty 0.11.0-dev (d8113dc2) (tested 0.9 and 0.10.1 too)
Linux: Wayland, GNOME

### Logs

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: TerminfoParsing(BadMagic(27745)) }', src/libcore/result.rs:1084:5
stack backtrace:
   0:     0x5608f766581d - backtrace::backtrace::libunwind::trace::he8b122396753abc9
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1:     0x5608f766581d - backtrace::backtrace::trace_unsynchronized::h18fe1998c04a41d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2:     0x5608f766581d - std::sys_common::backtrace::_print::habdbb4fd9d9c0917
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x5608f766581d - std::sys_common::backtrace::print::hb1a087501dbb63e0
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x5608f766581d - std::panicking::default_hook::{{closure}}::h24dac8a570d8db04
                               at src/libstd/panicking.rs:200
   5:     0x5608f7664f81 - std::panicking::default_hook::h893744b6a334a746
                               at src/libstd/panicking.rs:214
   6:     0x5608f7664f81 - std::panicking::rust_panic_with_hook::h86238c539b0cb6f7
                               at src/libstd/panicking.rs:477
   7:     0x5608f7664aaf - std::panicking::continue_panic_fmt::h40d8b593540103a4
                               at src/libstd/panicking.rs:384
   8:     0x5608f7675ff6 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x5608f7680c29 - core::panicking::panic_fmt::hd39929f6b65962b9
                               at src/libcore/panicking.rs:85
  10:     0x5608f7683a66 - core::result::unwrap_failed::hba83d9a1c7cbeac2
                               at src/libcore/result.rs:1084
  11:     0x5608f7536e6b - skim::Skim::run_with::h0cb27af22c954f00
  12:     0x5608f76a163b - sk::real_main::hb145bbd6b850e526
  13:     0x5608f769126d - sk::main::hc5783e3f6ebfd1c5
  14:     0x5608f768c1c3 - std::rt::lang_start::{{closure}}::h3a6b0cae99efa346
  15:     0x5608f768ecce - main
  16:     0x7f48c89a67fd - __libc_start_main
  17:     0x5608f74d416a - _start
  18:                0x0 - <unknown>
```

**Comment by kchibisov** [comment]
Oh, it seems like strack trace is not from alacritty? Are you using some other rust application in zsh?

**Comment by kchibisov** [comment]
Apparently it seems like https://github.com/lotabout/skim crashed bringing zsh down? I'd assume if you instead of doing `ctrl + r` launch zsh one more time and do `ctrl + r` in it it'll crash, but not bringing alacritty down?

**Comment by op** [comment]
Oh, how embarrassing! You're totally right. Thanks a lot for the help and sorry for wasting your time! :blush:
