### ISSUE TITLE
`flutter run -v -d linux` gives error

### ISSUE THREAD

**Issue by ahmetbombaci** [alacritty/alacritty#5946]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux / Ubuntu 20.04.4 LTS x86_64
Version: alacritty 0.8.0 (a1b13e6)
Linux/BSD: X11, DE: GNOME 3.36.9, WM: Mutter
### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

This could be rather snap issue than alacritty but opening this issue for observability. This happened for a few other cases that I cannot recall immediately. Whenever I execute commands with verbose mode and see logs regarding alacritty/snap, I immediately try with another terminal emulator (Gnome Terminal or Terminator) and I do not have any issues.

In this specific problem, I ran this issue while executing the following command:

`flutter run -v -d linux`

This is the relevant part of the logs:

```
intermediates_do_not_run/myapp  -Wl,-rpath,/home/ahmet/dev/flutter/myapp/linux/flutter/ephemeral:
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgtk-3.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk-3.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libpango-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libatk-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo-gobject.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so
/home/ahmet/dev/flutter/myapp/linux/flutter/ephemeral/libflutter_linux_gtk.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgio-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgobject-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libglib-2.0.so && :
[   +1 ms] /snap/alacritty/46/usr/lib/x86_64-linux-gnu/libpng16.so.16: undefined reference to `pow@GLIBC_2.29'
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[   +2 ms] ninja: build stopped: subcommand failed.
[  +16 ms] Building Linux application... (completed in 3.8s)
[+4994 ms] Exception: Build process failed
[   +1 ms] "flutter run" took 9,242ms.
[   +4 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
```

Installation steps and sample app can be found at https://docs.flutter.dev/get-started/install

**Comment by chrisduerr** [comment]
> This could be rather snap issue than alacritty

Snap is not supported.
