### ISSUE TITLE
Running issue on wsl2 Ubuntu

### ISSUE THREAD

**Issue by wang-tc** [alacritty/alacritty#6046]
I tried to install alacritty on wsl2 Ubuntu. I followed the manual installation steps and they worked fine. However, I have the following bug when I run the application. I know it is unusual to install on wsl2, but I was just wondering if there is any quick fix or what the right direction could be. Many thanks.

### System

OS: Ubuntu (wsl2)
Version: alacritty 0.11.0-dev (ad3ebba5)
Linux/BSD: Wayland (based on messages below)

### Logs

Crashes: 
```
export RUST_BACKTRACE=full
alacritty
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.28.0/src/api/egl/mod.rs:424:32
stack backtrace:
   0:     0x557bedbf07e1 - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x557bedbf07e1 - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557bedbf07e1 - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x557bedbf07e1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x557bedac28dc - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x557bedbc4f79 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x557bedbf2a72 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x557bedbf2a72 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x557bedbf2a72 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x557bedbf3ada - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x557bedbf3ada - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:     0x557bedbf34fb - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:586:13
  12:     0x557bedbf3496 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x557bedbf3452 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:     0x557bed8eed22 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:     0x557bed8eee7c - core::panicking::panic::h4241c5ccea17faca
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5
  16:     0x557bed9254b8 - core::option::Option<T>::unwrap::hbb01f60783d526a4
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:752:21
  17:     0x557bed9254b8 - glutin::api::egl::Context::new::h5c4aec942784ea4d
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.28.0/src/api/egl/mod.rs:424:19
  18:     0x557bed9254b8 - glutin::platform_impl::platform_impl::wayland::Context::new_raw_context::hf4e444da27e56b9c
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.28.0/src/platform_impl/unix/wayland.rs:124:13
  19:     0x557bed9254b8 - glutin::platform_impl::platform_impl::wayland::Context::new::h7ec4a7ae2c05ee0b
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.28.0/src/platform_impl/unix/wayland.rs:105:23
  20:     0x557bed9254b8 - glutin::platform_impl::platform_impl::Context::new_windowed::h0681f9799f6a7c89
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.28.0/src/platform_impl/unix/mod.rs:113:20
  21:     0x557bed9254b8 - glutin::windowed::<impl glutin::ContextBuilder<T>>::build_windowed::he27a3996bfa875ee
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.28.0/src/windowed.rs:341:9
  22:     0x557bed9254b8 - alacritty::display::window::create_gl_window::h1763f98a3daf85ac
                               at /home/ubuntu/apps/alacritty/alacritty/src/display/window.rs:152:28
  23:     0x557bed9254b8 - alacritty::display::window::Window::new::hac31e71b661686cc
                               at /home/ubuntu/apps/alacritty/alacritty/src/display/window.rs:218:37
  24:     0x557beda0a436 - alacritty::display::Display::new::h7ab1cb9f6b707727
                               at /home/ubuntu/apps/alacritty/alacritty/src/display/mod.rs:411:22
  25:     0x557bed9a1831 - alacritty::window_context::WindowContext::new::h40e1e53d01bf8011
                               at /home/ubuntu/apps/alacritty/alacritty/src/window_context.rs:81:23
  26:     0x557bed9c92d1 - alacritty::event::Processor::create_window::h16079b1a62a1ec0c
                               at /home/ubuntu/apps/alacritty/alacritty/src/event.rs:1232:30
  27:     0x557beda61e0e - alacritty::alacritty::h77e28e182d6091f1
                               at /home/ubuntu/apps/alacritty/alacritty/src/main.rs:194:5
  28:     0x557beda61e0e - alacritty::main::h83b04149449a39f0
                               at /home/ubuntu/apps/alacritty/alacritty/src/main.rs:81:17
  29:     0x557beda59863 - core::ops::function::FnOnce::call_once::hfede5006e31a218b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
  30:     0x557beda59863 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf0bf241ee1321db8
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:122:18
  31:     0x557beda5c341 - main
  32:     0x7f0a660b30b3 - __libc_start_main
  33:     0x557bed8fa63e - _start
  34:                0x0 - <unknown>
```

Font/Terminal size:
```
alacritty -vv
Created log file at "/tmp/Alacritty-317.log"
[0.000001192s] [INFO ] [alacritty] Welcome to Alacritty
[0.000073056s] [INFO ] [alacritty] Version 0.11.0-dev (ad3ebba5)
[0.000088395s] [INFO ] [alacritty] Running on Wayland
[0.000138248s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.000218287s] [DEBUG] [alacritty] Loading "monospace" font
[0.002416283s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.002626465s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.002808755s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.002994491s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.003155010s] [DEBUG] [alacritty] Estimated scaling factor: 1
[0.003171661s] [DEBUG] [alacritty] Estimated window size: None
[0.003175388s] [DEBUG] [alacritty] Estimated cell size: 9 x 18
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.28.0/src/api/egl/mod.rs:424:32
...
```

Keyboard and bindings: 
```
alacritty --print-events
Created log file at "/tmp/Alacritty-344.log"
[0.000000672s] [INFO ] [alacritty] Welcome to Alacritty
[0.000069981s] [INFO ] [alacritty] Version 0.11.0-dev (ad3ebba5)
[0.000085159s] [INFO ] [alacritty] Running on Wayland
[0.000132367s] [INFO ] [alacritty_config_derive] No config file found; using default
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.28.0/src/api/egl/mod.rs:424:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Deleted log file at "/tmp/Alacritty-344.log"
```

**Comment by thetrompf** [comment]
I looks like it fails building the EGL display context in the glutin library (low-level library), when running in WSL.
https://github.com/rust-windowing/glutin/blob/v0.28.0/glutin/src/api/egl/mod.rs#L424

I don't think it was built for running inside WSL.

**Comment by chrisduerr** [comment]
Are you installing it into the WSL VM, or are you just using the shell/PTY from the WSL?

**Comment by wang-tc** [comment]
@thetrompf Thank you for the information. I was just asking to see if there is an easy fix. Since there seems not to be an easy fix, I'll just forget about running it in WSL.

**Comment by thetrompf** [comment]
Why do you want to run it inside WSL anyway? You can just run the WSL shell inside the windows version of Alacritty?

**Comment by wang-tc** [comment]
@chrisduerr Thank you for the response. I was installing it into the WSL. Since it may need some extra work and it is not an important issue, would it be okay for me to close the issue?

**Comment by thetrompf** [comment]
or you can uses the same config file across Linux and windows and just pass the few different options directly to the executable in a shortcut file.

**Comment by wang-tc** [comment]
@thetrompf Thank you for the tips. Didn't know the config options can be passed to the executable.

**Comment by chrisduerr** [comment]
> @chrisduerr Thank you for the response. I was installing it into the WSL. Since it may need some extra work and it is not an important issue, would it be okay for me to close the issue?

Yeah, this is not exactly a system we support. So if you run into issues with that, you're on your own. You'll likely run into issues similar to running Alacritty in some Virtual Machines, with the slight inconvenience that it's also a terrible Windows virtual machine.
