### ISSUE TITLE
panic on `maximum number of clients reached`

### ISSUE THREAD

**Issue by arctic-penguin** [alacritty/alacritty#6098]
### System

OS: Arch Linux
Version: alacritty 0.10.1 ()
Linux/BSD: X11, i3-gaps, picom

### Logs

Spawn a large number of alacritty terminals until you reach the limit (apparently 47?). Then spawn another one.

Crashes: STDERR, STDOUT

(I compiled the debug version of 0.10.1 for this)
```
$ RUST_BACKTRACE=full cargo r 
Maximum number of clients reached
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: XcbConn(Connection)', alacritty/src/clipboard.rs:57:90
stack backtrace:
   0:     0x557951c9089d - std::backtrace_rs::backtrace::libunwind::trace::h22893a5306c091b4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x557951c9089d - std::backtrace_rs::backtrace::trace_unsynchronized::h29c3bc6f9e91819d
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557951c9089d - std::sys_common::backtrace::_print_fmt::he497d8a0ec903793
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x557951c9089d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c2a9d2774d81873
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x557951cb61ec - core::fmt::write::hba4337c43d992f49
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
   5:     0x557951c8c361 - std::io::Write::write_fmt::heb73de6e02cfabed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
   6:     0x557951c92525 - std::sys_common::backtrace::_print::h63c8b24acdd8e8ce
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x557951c92525 - std::sys_common::backtrace::print::h426700d6240cdcc2
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x557951c92525 - std::panicking::default_hook::{{closure}}::hc9a76eed0b18f82b
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
   9:     0x557951c921d9 - std::panicking::default_hook::h2e88d02087fae196
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
  10:     0x557951c92a72 - std::panicking::rust_panic_with_hook::habfdcc2e90f9fd4c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:698:17
  11:     0x557951c92957 - std::panicking::begin_panic_handler::{{closure}}::he054b2a83a51d2cd
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:588:13
  12:     0x557951c90d54 - std::sys_common::backtrace::__rust_end_short_backtrace::ha48b94ab49b30915
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x557951c92689 - rust_begin_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
  14:     0x5579511657f3 - core::panicking::panic_fmt::h366d3a309ae17c94
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
  15:     0x5579511658e3 - core::result::unwrap_failed::hddd78f4658ac7d0f
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
  16:     0x55795137dfd5 - core::result::Result<T,E>::unwrap::hfb7577eb66f8612d
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1078:23
  17:     0x5579512cd900 - <alacritty::clipboard::Clipboard as core::default::Default>::default::h96f6a53ee2cb4a25
                               at /home/XXXXXXXX/tmp/alacritty/alacritty/src/clipboard.rs:57:38
  18:     0x5579512cd555 - alacritty::clipboard::Clipboard::new::hb2ce402d489cc6af
                               at /home/XXXXXXXX/tmp/alacritty/alacritty/src/clipboard.rs:37:21
  19:     0x55795123f7fa - alacritty::event::Processor::run::he08d56081aa509a9
                               at /home/XXXXXXXX/tmp/alacritty/alacritty/src/event.rs:1235:38
  20:     0x5579512982eb - alacritty::alacritty::h5d9f93506ee374aa
                               at /home/XXXXXXXX/tmp/alacritty/alacritty/src/main.rs:201:5
  21:     0x5579512970f2 - alacritty::main::hec27989a3c48a675
                               at /home/XXXXXXXX/tmp/alacritty/alacritty/src/main.rs:81:17
  22:     0x5579511a676b - core::ops::function::FnOnce::call_once::hc27d9a089c4b5f98
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  23:     0x55795135089e - std::sys_common::backtrace::__rust_begin_short_backtrace::h10ec5f91c2a0dde8
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:122:18
  24:     0x55795134c321 - std::rt::lang_start::{{closure}}::h966255788ffa7d99
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:145:18
  25:     0x557951c859fe - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::had4f69b3aefb47a8
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
  26:     0x557951c859fe - std::panicking::try::do_call::hf2ad5355fcafe775
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  27:     0x557951c859fe - std::panicking::try::h0a63ac363423e61e
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  28:     0x557951c859fe - std::panic::catch_unwind::h18088edcecb8693a
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  29:     0x557951c859fe - std::rt::lang_start_internal::{{closure}}::ha7dad166dc711761
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
  30:     0x557951c859fe - std::panicking::try::do_call::hda0c61bf3a57d6e6
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  31:     0x557951c859fe - std::panicking::try::hbc940e68560040a9
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  32:     0x557951c859fe - std::panic::catch_unwind::haed0df2aeb3fa368
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  33:     0x557951c859fe - std::rt::lang_start_internal::h9c06694362b5b80c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
  34:     0x55795134c2f0 - std::rt::lang_start::h3ebb68566a6645a7
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:144:17
  35:     0x55795129897c - main
  36:     0x7f42c2086290 - <unknown>
  37:     0x7f42c208634a - __libc_start_main
  38:     0x557951165ae5 - _start
                               at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
  39:                0x0 - <unknown>



```
Font/Terminal size:
```
Created log file at "/tmp/Alacritty-187696.log"
[0.000003569s] [INFO ] [alacritty] Welcome to Alacritty
[0.000827642s] [INFO ] [alacritty] Version 0.10.1 ()
[0.000842014s] [INFO ] [alacritty] Running on X11
[0.002484277s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/XXXXXXXX/.config/alacritty/alacritty.yml"
[0.024649650s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.027576936s] [DEBUG] [alacritty] Estimated DPR: 1
[0.027601976s] [DEBUG] [alacritty] Estimated window size: None
[0.027621321s] [DEBUG] [alacritty] Estimated cell size: 8 x 18
[0.071200811s] [INFO ] [alacritty] Device pixel ratio: 1
[0.078543401s] [INFO ] [alacritty] Initializing glyph cache...
[0.080711904s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.085519788s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.091601059s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.095573530s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.104340347s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.025772707s
[0.104458712s] [INFO ] [alacritty] Cell size: 8 x 18
[0.104479975s] [INFO ] [alacritty] Padding: 4 x 3
[0.104483445s] [INFO ] [alacritty] Width: 800, Height: 600
[0.118375464s] [INFO ] [alacritty] PTY dimensions: 33 x 99
[0.121394910s] [INFO ] [alacritty] Initialisation complete
[0.123129120s] [DEBUG] [alacritty_terminal] New num_cols is 2 and num_lines is 1
[0.123225938s] [INFO ] [alacritty] Padding: 0 x 0
[0.123236213s] [INFO ] [alacritty] Width: 0, Height: 0
[0.377446601s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-187696.log"
```

Keyboard and bindings: `alacritty --print-events`
```
Created log file at "/tmp/Alacritty-188315.log"
[0.000003791s] [INFO ] [alacritty] Welcome to Alacritty
[0.000691699s] [INFO ] [alacritty] Version 0.10.1 ()
[0.000704446s] [INFO ] [alacritty] Running on X11
[0.002040651s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/XXXXXXXX/.config/alacritty/alacritty.yml"
[0.060610447s] [INFO ] [alacritty] Device pixel ratio: 1
[0.067547303s] [INFO ] [alacritty] Initializing glyph cache...
[0.091076671s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.023492317s
[0.091177846s] [INFO ] [alacritty] Cell size: 8 x 18
[0.091204132s] [INFO ] [alacritty] Padding: 4 x 3
[0.091207666s] [INFO ] [alacritty] Width: 800, Height: 600
[0.106900130s] [INFO ] [alacritty] PTY dimensions: 33 x 99
[0.111788526s] [INFO ] [alacritty] Initialisation complete
[0.113092155s] [INFO ] [alacritty] glutin event: NewEvents(Init)
[0.113165716s] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(16))), event: Key(KeyboardInput { scancode: 31, state: Released, virtual_keycode: Some(S), modifiers: (empty) }) }
[0.113213129s] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(16))), event: Key(KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: (empty) }) }
[0.113445275s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(104857602))), event: Moved(PhysicalPosition { x: 0, y: 0 }) }
[0.113482014s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(104857602))), event: Resized(PhysicalSize { width: 0, height: 0 }) }
[0.113505831s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.113528011s] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(X(WindowId(104857602))))
[0.113533209s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.113623257s] [INFO ] [alacritty] Padding: 0 x 0
[0.113630167s] [INFO ] [alacritty] Width: 0, Height: 0
[0.132908057s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 11058, tv_nsec: 50977576 }, requested_resume: None })
[0.132939599s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(X(WindowId(104857602)))), payload: Terminal(Wakeup) })
[0.132976074s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.132982535s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.248798611s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 11058, tv_nsec: 66196793 }, requested_resume: None })
[0.248854309s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(X(WindowId(104857602)))), payload: Terminal(Wakeup) })
[0.248865480s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.248872627s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.264886625s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 11058, tv_nsec: 182957049 }, requested_resume: None })
[0.264925043s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(X(WindowId(104857602)))), payload: Terminal(Wakeup) })
[0.264934088s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.264939984s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.366800892s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 11058, tv_nsec: 199576185 }, requested_resume: None })
[0.366836271s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.366843804s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.367085332s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 11058, tv_nsec: 284928767 }, requested_resume: None })
[0.367105358s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(X(WindowId(104857602)))), payload: Terminal(Exit) })
[0.374528167s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(X(WindowId(104857602)))), payload: Terminal(Wakeup) })
[0.374553336s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.374565707s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.374589767s] [INFO ] [alacritty] glutin event: LoopDestroyed
[0.374693036s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-188315.log"
```

**Comment by arctic-penguin** [comment]
The line that causes the crash is this.

https://github.com/alacritty/alacritty/blob/master/alacritty/src/clipboard.rs#L57

**Comment by chrisduerr** [comment]
You can fix this by increasing the client limit. This is also something you will run into sooner or later anyway, so it's not completely avoidable. I'd assume the 47 terminal clients were explicitly just to cause this issue and are not a normal usage scenario.

That said, clipboard rework should significantly reduce the number of X clients: https://github.com/alacritty/alacritty/issues/2735

**Comment by iaamp** [comment]
I have the same problem, using i3 v4.21 and alacritty 0.13.0-dev (ead652221) on Regolith (on top of Ubuntu 22.04).
My workflow involves a lot of terminals, that i like to keep open. For me, the limit seems to be 32 terminals, at least that is the max in my current session.

Is there a workaround that i can use? Not sure about the suggestion from kchibisov about using windows, i think i3 is indeed opening a window with alacritty for each one.

**Comment by kchibisov** [comment]
If you run `alacritty` in your i3 config you're opening a new instance.

If you use `CreateWindow` hotkey in alacritty (you should bind it manually on Linux) or `alacritty msg create-window` you're creating a new window. Otherwise instance.

You can have in i3 something like `alacritty msg create-window || alacritty`.

**Comment by kchibisov** [comment]
Or, as an alternative, you could raise amount of clients in X.org settings to 2048.
