### ISSUE TITLE
Crash while typing in neovim

### ISSUE THREAD

**Issue by Duckonaut** [alacritty/alacritty#6487]
While on Wayland, I experience random crashes while typing in Neovim. Log is below. I cannot reproduce it other than by just using Neovim as I normally would. I also cannot reproduce it with a clean config, though since it happens seemingly at random I might've just not ran into it. But for that reason, I'm linking my config as of the time of this issue [here](https://github.com/Duckonaut/nvim/tree/9afe3c2be60f1990437cac97d61902bc4eeacb4c), plugins list is [here](https://github.com/Duckonaut/nvim/blob/9afe3c2be60f1990437cac97d61902bc4eeacb4c/lua/plugins.lua)

When running under X11, this doesn't ever happen.

### System

OS: Linux
Version: alacritty 0.11.0 (8dbaa0bb)
Linux/BSD: Wayland, Hyprland

### Logs

The important bit:
```
thread 'main' panicked at 'already borrowed: BorrowMutError', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.10.1/src/loop_logic.rs:101:46
stack backtrace:
   0:     0x55719bc17431 - <unknown>
   1:     0x55719bad06dc - <unknown>
   2:     0x55719bbedf94 - <unknown>
   3:     0x55719bc193e6 - <unknown>
   4:     0x55719bc1a478 - <unknown>
   5:     0x55719bc19f52 - <unknown>
   6:     0x55719bc19ec6 - <unknown>
   7:     0x55719bc19e82 - <unknown>
   8:     0x55719b8b3ba2 - <unknown>
   9:     0x55719b8b3e22 - <unknown>
  10:     0x55719bc9dcf1 - <unknown>
  11:     0x55719bcc8cba - <unknown>
  12:     0x55719bcd11e3 - <unknown>
  13:     0x55719bcbdd67 - <unknown>
  14:     0x55719bc58144 - <unknown>
  15:     0x7f7e8a8fcd65 - <unknown>
  16:     0x7f7e8a8fcffc - wl_display_dispatch_queue_pending
  17:     0x55719b9ba91a - <unknown>
  18:     0x55719b9b9d71 - <unknown>
  19:     0x55719b99533c - <unknown>
  20:     0x55719b9016da - <unknown>
  21:     0x55719b9b1245 - <unknown>
  22:     0x55719b9c9b12 - <unknown>
  23:     0x55719b957ec3 - <unknown>
  24:     0x55719b9c62b4 - <unknown>
  25:     0x7f7e8a4c5290 - <unknown>
  26:     0x7f7e8a4c534a - __libc_start_main
  27:     0x55719b8c00b5 - <unknown>
  28:                0x0 - <unknown>
[wayland-client error] A handler for wl_keyboard panicked.
[1]    20807 IOT instruction (core dumped)  RUST_BACKTRACE=full alacritty -vv
```
The entire log is attached here
[alacritty-log.txt](https://github.com/alacritty/alacritty/files/9995695/alacritty-log.txt)

**Comment by kchibisov** [comment]
If you build alacritty from source and before that run `cargo update -p calloop` does it happen?

**Comment by Duckonaut** [comment]
Thanks for the fast fix, should I checkout at 0.11.0 or just do it on the latest source?

**Comment by kchibisov** [comment]
I'm not sure whether it's a fix or not. I'm just curios if one of the patch versions fix it.

There's a 'fix' but not released.

You can checkout on v0.11.0.

**Comment by kchibisov** [comment]
Be sure that `calloop` will be the version `0.10.3` when testing. You'll that in `cargo update -p calloop` output.

**Comment by Duckonaut** [comment]
Alright, I was using the custom built alacritty for the past couple days. Admittedly a bit less than usual so that's the reason for the delay, but there's change. It doesn't visually crash, the window stays open, but it freezes. I managed to catch one log (happened to me 4 times), and it panicked like this

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/duckonaut/.cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.10.3/src/loop_logic.rs:377:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by kchibisov** [comment]
@Duckonaut could you try applying this patch. 

```patch
diff --git a/Cargo.lock b/Cargo.lock
index 25471d1a..fd02da2d 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -156,9 +156,8 @@ checksum = "2f5715e491b5a1598fc2bef5a606847b5dc1d48ea625bd3c02c00de8285591da"
 
 [[package]]
 name = "calloop"
-version = "0.10.1"
-source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "a22a6a8f622f797120d452c630b0ab12e1331a1a753e2039ce7868d4ac77b4ee"
+version = "0.10.2"
+source = "git+https://github.com/kchibisov/calloop?branch=try-handle-source-remove#1eb880e9af3f1ad44fb88af5038bd7dc802741e6"
 dependencies = [
  "log",
  "nix",
diff --git a/Cargo.toml b/Cargo.toml
index aad21557..6e367582 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -10,3 +10,6 @@ members = [
 lto = true
 debug = 1
 incremental = false
+
+[patch.crates-io]
+calloop = { git = "https://github.com/kchibisov/calloop", branch = "try-handle-source-remove" }
```

I hope it should fix your issue.

**Comment by MarijnS95** [comment]
@Duckonaut what you see is perhaps similar to https://github.com/Smithay/calloop/pull/115#discussion_r1039485195?

**Comment by kchibisov** [comment]
@MarijnS95 could you try the patch I've posted, it's a different approach to fixing this issue.

**Comment by MarijnS95** [comment]
@kchibisov Thanks, I'll try that; looks much closer to how I expected https://github.com/Smithay/calloop/pull/110 / https://github.com/Smithay/calloop/pull/115 to be implemented...

**Comment by kchibisov** [comment]
I mean the issue is that one source decided to delete another source from the hook... So we need to clone them otherwise one will be removed in-between.

**Comment by MarijnS95** [comment]
Yes cloning is fine... But that obviously doesn't work when only cloning the keys and then still expecting every key to remain in the map when later iterating over them...

**Comment by Duckonaut** [comment]
Sorry for the delay again, the alternative fix did work and my problem seems to be gone
