### ISSUE TITLE
Focused alacritty windows crash when restarting i3

### ISSUE THREAD

**Issue by hv-something** [alacritty/alacritty#6538]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Debian 11 stable
Version: 0.12.0-dev (2d619850)
Linux/BSD: X11, i3 and picom

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: 

```
Created log file at "/tmp/Alacritty-68231.log"
[0.000011548s] [INFO ] [alacritty] Welcome to Alacritty
[0.000192596s] [INFO ] [alacritty] Version 0.12.0-dev (2d619850)
[0.000234186s] [INFO ] [alacritty] Running on X11
[0.000527993s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.006203612s] [INFO ] [alacritty] Using GLX 1.4
[0.113863181s] [INFO ] [alacritty] Window scale factor: 1
[0.115189900s] [DEBUG] [alacritty] Loading "monospace" font
[0.124206036s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.125783913s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.127487960s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.129240457s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.134742738s] [INFO ] [alacritty] Running on NVE7
[0.134768184s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.143704161s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.177438838s] [INFO ] [alacritty] Cell size: 9 x 18
[0.177514079s] [INFO ] [alacritty] Padding: 0 x 0
[0.177538802s] [INFO ] [alacritty] Width: 800, Height: 600
[0.189248977s] [INFO ] [alacritty] PTY dimensions: 33 x 88
[0.192290824s] [INFO ] [alacritty] Initialisation complete
[0.213466719s] [DEBUG] [alacritty_terminal] New num_cols is 73 and num_lines is 19
[0.229562548s] [INFO ] [alacritty] Padding: 0 x 0
[0.229620166s] [INFO ] [alacritty] Width: 658, Height: 346
[0.300711358s] [DEBUG] [alacritty_terminal] unknown device status query: 1337
[2.334171186s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-68231.log"
```

Keyboard and bindings: `alacritty --print-events`

So I recently cloned the repo and after i set everything up, it works until I restart i3. After that, it just blacked out like in this picture:
![Screenshot_2022-11-30_23-10-49](https://user-images.githubusercontent.com/118409646/204857719-32c72bed-3161-4fed-9683-33cbd2d59b82.png)
This only happen with the focused windows, unfocused windows work just fine
when I restart, the terminal session I opened it from gives me this message:
`thread 'main' panicked at 'failed to swap buffers.: Error { raw_code: Some(3), raw_os_message: Some("BadWindow (invalid Window parameter)"), kind: BadNativeWindow }', alacritty/src/display/mod.rs:557:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

That's all I have for now. I am willing to provide more info, just tell me how to actually get the extra info that you need

**Comment by kchibisov** [comment]
Does it work with 0.11 release?

**Comment by hv-something** [comment]
@kchibisov Yes that release works fine

**Comment by hv-something** [comment]
@kchibisov I'm not sure what you want to ask but from what I can infer, the 0.11.0 release works fine without any major error (there is this 'Xlib: sequence lost (0x10087 > 0x89) in reply type 0x0!' error but it hasn't affected me so far)

**Comment by kchibisov** [comment]
Does this commit works 578e08486dfcdee0b2cd0e7a66752ff50edc46b8 ?

**Comment by hv-something** [comment]
@kchibisov wait wdym? I dont know much about git and github (at least not yet) so please explain to me what you mean and show me how to do it

**Comment by kchibisov** [comment]
I mean if you've cloned the repo, you can `git checkout 578e084` in it and do a `cargo run --release` from it. I'd assume you've built a git version somehow.

**Comment by hv-something** [comment]
@kchibisov Yes I have built a git version but I just copied and paste the commands so I don't know much more than how to build the software. Anyways, I have school now so I'll test it when I get home and tell you about the result

**Comment by kchibisov** [comment]
We've investigated with @chrisduerr the issue and it's pretty trivial to fix it (could just ignore the swap buffers error). Though, I wonder what will be the right fix for this issue.

I have a suspicion that the window is unmapped and we shouldn't draw into the unmapped window. For that winit integration must be established somehow, so we can get the state of map/unmapped window.

**Comment by Keony1** [comment]
Does this commit fix the issue? I've tried to update, but seems not work

I could get this error message executing `alacritty` and then refreshing i3

````
thread 'main' panicked at 'failed to swap buffers.: Error { raw_code: Some(3), raw_os_message: Some("BadWindow (invalid Window parameter)"), kind: BadNativeWindow }', alacritty/src/display/mod.rs:557:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Deleted log file at "/tmp/Alacritty-59210.log"
````
my alacritty version: `alacritty 0.12.0-dev (2d619850)`
