### ISSUE TITLE
SEGFAULT at startup when run on different X Server.

### ISSUE THREAD

**Issue by eemanuele** [alacritty/alacritty#6595]
alacritty SEGFAULT's when I try to run it on a different X Server.

```
# From :2
$ DISPLAY=:0 alacritty
[1]    45949 segmentation fault (core dumped)  DISPLAY=:0 alacritty
```

### Possible steps to reproduce:

* Open a VT (eg. CTRL + ALT + F4), run `startx`.
* Open another VT (eg. CTRL + ALT + F5), run `startx`.

You should now have two X Servers running:

```bash
$ w
emanuel  tty4      16:05   58.00s  0.56s  0.00s xinit /home/emanuel/.xinitrc -- /etc/X11/xinit/xserverrc :0 vt4 -keeptty -auth /tmp/serverauth.reLCCDVntw
emanuel  tty5      16:05   50.00s  0.54s  0.00s xinit /home/emanuel/.xinitrc -- /etc/X11/xinit/xserverrc :2 vt5 -keeptty -auth /tmp/serverauth.AXKYp5RyLy
...
``` 
* Start `alacritty` on one, but displaying it on the other:
```
# From :2
$ DISPLAY=:0 alacritty
[1]    45949 segmentation fault (core dumped)  DISPLAY=:0 alacritty
```

Notes:
- Other applications, like `xterm`, do not segfault when attempting the same.
- `alacritty` does **not** SEGFAULT if I use `Xephyr` to start the second X Server.

### System

OS: Linux
Version: alacritty 0.12.0-dev (a49bd742), alacritty 0.11.0 (8dbaa0bb)
Display Server: X11
Window Manager: Tested with i3 and tinywm.

### Logs

Version: `alacritty 0.12.0-dev (a49bd742)`

Backtrace:

```
#0  0x00007fffee4b8225 in ?? () from /usr/lib/libnvidia-glcore.so.525.60.11
[Current thread is 1 (Thread 0x7ffff7798c80 (LWP 24833))]
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /home/emanuel/git/alacritty/target/debug/alacritty.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) bt
#0  0x00007fffee4b8225 in ?? () from /usr/lib/libnvidia-glcore.so.525.60.11
#1  0x00007fffee762068 in ?? () from /usr/lib/libnvidia-glcore.so.525.60.11
#2  0x00007fffee63dc51 in ?? () from /usr/lib/libnvidia-glcore.so.525.60.11
#3  0x00007fffee63ea10 in ?? () from /usr/lib/libnvidia-glcore.so.525.60.11
#4  0x00007fffee63fd47 in ?? () from /usr/lib/libnvidia-glcore.so.525.60.11
#5  0x00007fffee6502e6 in ?? () from /usr/lib/libnvidia-glcore.so.525.60.11
#6  0x00005555557e94ea in alacritty::gl::DrawElementsInstanced (mode=4, count=6, type_=5125, indices=0x0, instancecount=1) at target/debug/build/alacritty-9ac38616c6b113b5/out/gl_bindings.rs:1170
#7  0x00005555557db623 in alacritty::renderer::text::glsl3::{impl#3}::render_batch (self=0x7fffffff3e00) at alacritty/src/renderer/text/glsl3.rs:243
#8  0x00005555558ac13c in alacritty::renderer::text::glsl3::{impl#5}::drop (self=0x7fffffff3e00) at alacritty/src/renderer/text/glsl3.rs:277
#9  0x000055555589f56a in core::ptr::drop_in_place<alacritty::renderer::text::glsl3::RenderApi> () at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/ptr/mod.rs:490
#10 0x0000555555754b43 in alacritty::renderer::text::TextRenderer::draw_cells::{closure#0}<alacritty::renderer::text::glsl3::Glsl3Renderer, core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<alacritty::display::content::RenderableCell, alloc::alloc::Global>, alacritty::display::{impl#12}::draw::{closure_env#0}<alacritty::event::EventProxy>>> (api=...) at alacritty/src/renderer/text/mod.rs:67
#11 0x00005555556f1aa8 in alacritty::renderer::text::glsl3::{impl#1}::with_api<alacritty::renderer::text::TextRenderer::draw_cells::{closure_env#0}<alacritty::renderer::text::glsl3::Glsl3Renderer, core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<alacritty::display::content::RenderableCell, alloc::alloc::Global>, alacritty::display::{impl#12}::draw::{closure_env#0}<alacritty::event::EventProxy>>>, ()> (self=0x5555570439e0, size_info=0x7fffffff46e0, func=...) at alacritty/src/renderer/text/glsl3.rs:167
#12 0x00005555556f1b9d in alacritty::renderer::text::TextRenderer::draw_cells<alacritty::renderer::text::glsl3::Glsl3Renderer, core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<alacritty::display::content::RenderableCell, alloc::alloc::Global>, alacritty::display::{impl#12}::draw::{closure_env#0}<alacritty::event::EventProxy>>> (self=0x5555570439e0, size_info=0x7fffffff46e0, glyph_cache=0x555557043aa0, cells=...) at alacritty/src/renderer/text/mod.rs:63
#13 0x00005555556f426c in alacritty::renderer::Renderer::draw_cells<core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<alacritty::display::content::RenderableCell, alloc::alloc::Global>, alacritty::display::{impl#12}::draw::{closure_env#0}<alacritty::event::EventProxy>>> (self=0x555557043880, size_info=0x7fffffff46e0, glyph_cache=0x555557043aa0, cells=...) at alacritty/src/renderer/mod.rs:145
#14 0x00005555556811f1 in alacritty::display::Display::draw<alacritty::event::EventProxy> (self=0x555557043840, terminal=..., message_buffer=0x555557043218, config=0x555556752ab0, search_state=0x555557043238) at alacritty/src/display/mod.rs:807
#15 0x00005555556bec39 in alacritty::window_context::WindowContext::handle_event (self=0x555557043218, event_loop=0x55555674bb90, event_proxy=0x7fffffffb810, clipboard=0x7fffffffb7f0, scheduler=0x7fffffffb7b0, event=...) at alacritty/src/window_context.rs:499
#16 0x000055555588c822 in alacritty::event::{impl#10}::run::{closure#0} (event=..., event_loop=0x55555674bb90, control_flow=0x7fffffffb450) at alacritty/src/event.rs:1469
#17 0x0000555555789feb in winit::platform_impl::platform::sticky_exit_callback<alacritty::event::Event, alacritty::event::{impl#10}::run::{closure_env#0}> (evt=..., target=0x55555674bb90, control_flow=0x7fffffffb450, callback=0x7fffffffb730)
    at /home/emanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/mod.rs:849
#18 0x00005555556edc6d in winit::platform_impl::platform::x11::{impl#2}::run_return::single_iteration<alacritty::event::Event, alacritty::event::{impl#10}::run::{closure_env#0}> (this=0x7fffffffd170, control_flow=0x7fffffffb450, cause=0x7fffffffb478,
    callback=0x7fffffffb730) at /home/emanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/mod.rs:390
#19 0x00005555556ee11d in winit::platform_impl::platform::x11::EventLoop<alacritty::event::Event>::run_return<alacritty::event::Event, alacritty::event::{impl#10}::run::{closure_env#0}> (self=0x7fffffffd170, callback=...)
    at /home/emanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/mod.rs:448
#20 0x00005555557892c4 in winit::platform_impl::platform::EventLoop<alacritty::event::Event>::run_return<alacritty::event::Event, alacritty::event::{impl#10}::run::{closure_env#0}> (self=0x7fffffffd170, callback=...)
    at /home/emanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/mod.rs:748
#21 0x000055555568ca90 in winit::platform::run_return::{impl#0}::run_return<alacritty::event::Event, alacritty::event::{impl#10}::run::{closure_env#0}> (self=0x7fffffffd170, event_handler=...)
    at /home/emanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform/run_return.rs:62
#22 0x00005555556fa40b in alacritty::event::Processor::run (self=0x7fffffffc958, event_loop=..., initial_window_options=...) at alacritty/src/event.rs:1394
#23 0x0000555555820403 in alacritty::alacritty (options=...) at alacritty/src/main.rs:189
#24 0x000055555581f53c in alacritty::main () at alacritty/src/main.rs:83
(gdb)
```

**Comment by kchibisov** [comment]
>/usr/lib/libnvidia-glcore.so.525.60.11

Provide a stacktrace when using mesa/llvmpipe. For now it seems like nvidia bug.

**Comment by eemanuele** [comment]
Indeed it doesn't crash when I run the latest version using mesa:
```
__GLX_VENDOR_LIBRARY_NAME=mesa DISPLAY=:2 alacritty
```

Many thanks for your time!
