### ISSUE TITLE
[Bug] Crashes on launch (Windows 10)

### ISSUE THREAD

**Issue by smol-loli** [alacritty/alacritty#6686]
### Expected behavior:
Open Alacritty opens a new Alacritty terminal

### Current behavior:
panicks at opening

### System

OS: Windows
Version: 0.11.0 (d23330a)

### Logs
Error:

[0.000002800s] [INFO ] [alacritty] Welcome to Alacritty
[0.000571500s] [INFO ] [alacritty] Version 0.11.0 (d23330a)
[0.002398600s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.003621600s] [INFO ] [alacritty] glutin event: NewEvents(Init)
[0.003773100s] [INFO ] [alacritty] glutin event: Resumed
[0.092011300s] [INFO ] [alacritty] Running on NVIDIA GeForce RTX 3070/PCIe/SSE2
[0.092210400s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.098373700s] [INFO ] [alacritty] Display scale factor: 1
[0.099379700s] [INFO ] [alacritty] Cell size: 8 x 17
[0.099514200s] [INFO ] [alacritty] Padding: 0 x 0
[0.099999800s] [INFO ] [alacritty] Width: 800, Height: 600
[0.111151700s] [INFO ] [alacritty] PTY dimensions: 35 x 100
panicked at 'Unable to spawn shell: The system cannot find the specified file. (os error 2)', alacritty_terminal\src\tty\windows\conpty.rs:168:5

---------------------------
Alacritty: Runtime Error
---------------------------
panicked at 'Unable to spawn shell: The system cannot find the specified file. (os error 2)', alacritty_terminal\src\tty\windows\conpty.rs:168:5
---------------------------

**Comment by smol-loli** [comment]
It is a fresh install of Alacritty and re-installing did NOT resolve the issue.

**Comment by chrisduerr** [comment]
You need powershell in your path.

**Comment by smol-loli** [comment]
I already have powershell in my path so that cannot be the cause of this error.

Maybe it's a stupid mistake on my side 😄  - but I'm rather sure it isn't.

**Comment by kchibisov** [comment]
@smol-loli Hm, but it clearly says that it can't find shell. You might try to point to the shell with `-e` command. `alacritty -e cmd.exe` or `pwsh.exe`.

**Comment by smol-loli** [comment]
using -e **_full-path-to-cmd.exe_** resolved the issue
