### ISSUE TITLE
changing windows display scale causes a crash

### ISSUE THREAD

**Issue by pinjeff** [alacritty/alacritty#6949]
steps to reproduce:
1. start alacritty
2. minimize alacritty
3. change windows display scale
4. bringing alacritty back will cause the crash

### System

OS: Windows
Version: `alacritty 0.12.1 (5fdfd47)`

### Logs
[0.000003700s] [INFO ] [alacritty] Welcome to Alacritty
[0.000408900s] [INFO ] [alacritty] Version 0.12.1 (5fdfd47)
[0.002749700s] [INFO ] [alacritty] Configuration files loaded from:
                                     "C:\\Users\\jeff\\AppData\\Roaming\\alacritty\\alacritty.yml"
[0.012407700s] [INFO ] [alacritty] Window scale factor: 1
[0.068666100s] [INFO ] [alacritty] Using WGL
[0.080416300s] [DEBUG] [alacritty] Loading "Iosevka Curly" font
[0.099698200s] [INFO ] [alacritty] Running on AMD Radeon(TM) Graphics
[0.099952300s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.142406400s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.174504900s] [INFO ] [alacritty] Cell size: 9 x 25
[0.174729800s] [INFO ] [alacritty] Padding: 0 x 0
[0.174869300s] [INFO ] [alacritty] Width: 800, Height: 600
[0.198863600s] [INFO ] [alacritty] PTY dimensions: 24 x 88
[0.250253900s] [INFO ] [alacritty] Initialisation complete
[0.250894100s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[13.804558900s] [INFO ] [alacritty] Font size changed to Size(30) with scale factor of 1.25
[13.804808800s] [INFO ] [alacritty] Cell size: 12 x 31
[13.804960000s] [DEBUG] [alacritty_terminal] New num_cols is 2 and num_lines is 1
panicked at 'called `Option::unwrap()` on a `None` value', alacritty\src\display\mod.rs:681:72

**Comment by kchibisov** [comment]
Could you provide the `--print-events` log for me just so I can ensure that I understand the root cause correctly?

**Comment by pinjeff** [comment]
[0.000003400s] [INFO ] [alacritty] Welcome to Alacritty
[0.000358500s] [INFO ] [alacritty] Version 0.12.1 (5fdfd47)
[0.002561400s] [INFO ] [alacritty] Configuration files loaded from:
                                     "C:\\Users\\jeff\\AppData\\Roaming\\alacritty\\alacritty.yml"
[0.003313600s] [INFO ] [alacritty] winit event: NewEvents(Init)
[0.003441600s] [INFO ] [alacritty] winit event: Resumed
[0.011434700s] [INFO ] [alacritty] Window scale factor: 1
[0.066196800s] [INFO ] [alacritty] Using WGL
[0.095522600s] [INFO ] [alacritty] Running on AMD Radeon(TM) Graphics
[0.095797600s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.164801500s] [INFO ] [alacritty] Cell size: 9 x 25
[0.165095800s] [INFO ] [alacritty] Padding: 0 x 0
[0.165345700s] [INFO ] [alacritty] Width: 800, Height: 600
[0.185708400s] [INFO ] [alacritty] PTY dimensions: 24 x 88
[0.232075900s] [INFO ] [alacritty] Initialisation complete
[0.232395400s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(1377806)), event: Resized(PhysicalSize { width: 800, height: 600 }) }
[0.232628600s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(1377806)), event: KeyboardInput { device_id: DeviceId(DeviceId(0)), input: KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: (empty) }, is_synthetic: true } }
[0.232798700s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(1377806)), event: Focused(true) }
[0.232937600s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(1377806)), event: Resized(PhysicalSize { width: 800, height: 600 }) }
[0.233213600s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(DeviceId(11273351)), event: Added }
[0.233371400s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(DeviceId(1312125)), event: Added }
[0.233511000s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(DeviceId(131136)), event: Added }
[0.233628700s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(DeviceId(7275565)), event: Added }
[0.233740600s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(DeviceId(8258859)), event: Added }
[0.233869900s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(DeviceId(12583985)), event: Added }
[0.234011900s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(DeviceId(1705245)), event: Added }
[0.234162800s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(DeviceId(65599)), event: Added }
[0.234351000s] [INFO ] [alacritty] winit event: MainEventsCleared
[0.234539100s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[0.246762900s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { t: 2855.0007987s }, requested_resume: Some(Instant { t: 2855.0077352s }) })
[0.247003400s] [INFO ] [alacritty] winit event: MainEventsCleared
[0.247116900s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[0.247313800s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { t: 2855.007969s }, requested_resume: None })
[0.247433700s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(1377806))), payload: Frame })
[0.247563100s] [INFO ] [alacritty] winit event: MainEventsCleared
[0.247674000s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[0.263498400s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { t: 2855.008515s }, requested_resume: None })
[0.263722400s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(1377806))), payload: Terminal(Title(Ubuntu)) })
[0.263868300s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(1377806))), payload: Terminal(Wakeup) })
[0.264046400s] [INFO ] [alacritty] winit event: MainEventsCleared
[0.264163500s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[0.264868400s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { t: 2855.0252734s }, requested_resume: None })
[0.265123600s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(1377806))), payload: Frame })
[0.265327400s] [INFO ] [alacritty] winit event: MainEventsCleared
[0.265460600s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[0.638487800s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { t: 2855.026311s }, requested_resume: None })
[0.638783200s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(1377806))), payload: Terminal(Title(jeff@aero: ~)) })
[0.638924000s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(1377806))), payload: Terminal(Wakeup) })
[0.639105000s] [INFO ] [alacritty] winit event: MainEventsCleared
[0.639258500s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[0.639868000s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { t: 2855.4004048s }, requested_resume: None })
[0.640050500s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(1377806))), payload: Frame })
[0.640434900s] [INFO ] [alacritty] winit event: MainEventsCleared
[0.640568000s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[1.650769100s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { t: 2855.4014118s }, requested_resume: None })
[1.651139100s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(1377806)), event: ModifiersChanged((empty)) }
[1.651319600s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(1377806)), event: Focused(false) }
[1.653462000s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(1377806)), event: Moved(PhysicalPosition { x: -32000, y: -32000 }) }
[1.653698700s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(1377806)), event: Resized(PhysicalSize { width: 0, height: 0 }) }
[1.658497600s] [INFO ] [alacritty] winit event: MainEventsCleared
[1.658742300s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[1.663074700s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { t: 2856.4233478s }, requested_resume: None })
[1.663449600s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(1377806))), payload: Frame })
[1.663814000s] [INFO ] [alacritty] winit event: MainEventsCleared
[1.664001900s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[5.778268800s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { t: 2856.4249819s }, requested_resume: None })
[5.778735300s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(1377806)), event: ScaleFactorChanged { scale_factor: 1.25, new_inner_size: PhysicalSize { width: 0, height: 0 } } }
[5.781601100s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(1377806)), event: Moved(PhysicalPosition { x: 181, y: 182 }) }
[5.783963500s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(1377806)), event: Resized(PhysicalSize { width: 0, height: 0 }) }
[5.785656900s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(1377806)), event: Focused(true) }
[5.786581900s] [INFO ] [alacritty] winit event: MainEventsCleared
[5.786772400s] [INFO ] [alacritty] winit event: RedrawRequested(WindowId(WindowId(1377806)))
[5.786957500s] [INFO ] [alacritty] winit event: RedrawEventsCleared
[5.787429400s] [INFO ] [alacritty] Font size changed to Size(30) with scale factor of 1.25
[5.787596400s] [INFO ] [alacritty] Cell size: 12 x 31
panicked at 'called `Option::unwrap()` on a `None` value', alacritty\src\display\mod.rs:681:72
