### ISSUE TITLE
Alacritty crashes on startup after updating to the latest available version

### ISSUE THREAD

**Issue by vladkosarev** [alacritty/alacritty#7091]
Just ran an update on my Void Linux under WSL2/X410 and it looks like I might have gotten a new version of Alacritty which refuses to start up. Other terminals still work fine.

Happy to provide any other information.

### System

OS: WSL2 running Void Linux
Version: alacritty 0.12.2
Linux/BSD: X11/i3/x410

### Logs
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: XcbConnect(DisplayParsingError)', alacritty/src/clipboard.rs:56:57
stack backtrace:
   0:     0x55fa36e5156c - <unknown>
   1:     0x55fa36d169ae - <unknown>
   2:     0x55fa36e24714 - <unknown>
   3:     0x55fa36e53f2f - <unknown>
   4:     0x55fa36e53b2f - <unknown>
   5:     0x55fa36e54bc8 - <unknown>
   6:     0x55fa36e54684 - <unknown>
   7:     0x55fa36e545e6 - <unknown>
   8:     0x55fa36e545d1 - <unknown>
   9:     0x55fa36b02c82 - <unknown>
  10:     0x55fa36b03012 - <unknown>
  11:     0x55fa36c0625b - <unknown>
  12:     0x55fa36b38da8 - <unknown>
  13:     0x55fa36c1fba3 - <unknown>
  14:     0x55fa36b431d7 - <unknown>
  15:     0x7f06bd14820c - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  16:     0x7f06bd1482bc - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:381:3
  17:     0x55fa36b1a8a1 - <unknown>
  18:                0x0 - <unknown>
```

**Comment by kchibisov** [comment]
Well, we can't connect to X11 display, looks like a wsl specific issue.

**Comment by vladkosarev** [comment]
Downgraded to Alacritty 0.11.0 and everything is fine again.
This is something in the new version.

**Comment by kchibisov** [comment]
The error is coming from the https://github.com/quininer/x11-clipboard from what I can say. Could you try examples from this crate, if they don't work then it'll probably be simpler to address that?

That's the only thing that have changed in 0.12.0 wrt the issue you're getting.

cc @quininer maybe they know what could cause it from the update

**Comment by vladkosarev** [comment]
Yeap, examples are panicking
```
[16:45:15 vlad@jane-xps]$ cargo run --example paste
   Compiling x11-clipboard v0.8.0 (/home/vlad/x11-clipboard)
    Finished dev [unoptimized + debuginfo] target(s) in 0.70s
     Running `target/debug/examples/paste`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: XcbConnect(DisplayParsingError)', examples/paste.rs:8:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
~/x11-clipboard (master)
```

**Comment by kchibisov** [comment]
Will suggest to bring it upstream then.
