### ISSUE TITLE
Alacritty crashes on pressing Cmd + any number

### ISSUE THREAD

**Issue by huyvohcmc** [alacritty/alacritty#7249]
### System

OS: macOS Sonoma 14.0
Version: alacritty 0.13.0-dev (47d500770a7f)

### Logs

```
Created log file at "/var/folders/cs/t_nzsd0j67n1wv2b8mdfgmkw0000gn/T/Alacritty-33419.log"
[0.000003125s] [INFO ] [alacritty] Welcome to Alacritty
[0.000167750s] [INFO ] [alacritty] Version 0.13.0-dev (47d500770a7f)
[0.000610125s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/huyvo/.config/alacritty/alacritty.toml"
2023-09-28 19:03:40.198 alacritty[33419:172596] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
[0.015906791s] [INFO ] [alacritty] winit event: NewEvents(Init)
[0.015935958s] [INFO ] [alacritty] winit event: Resumed
[0.015956916s] [INFO ] [alacritty] Using Apple CGL
[0.049525500s] [INFO ] [alacritty] Window scale factor: 2
[0.096308291s] [INFO ] [alacritty] Running on Apple M2 Pro
[0.096336958s] [INFO ] [alacritty] OpenGL version 4.1 Metal - 86, shader_version 4.10
[0.096350458s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.111304791s] [INFO ] [alacritty] Cell size: 14 x 31
[0.111338750s] [INFO ] [alacritty] Padding: 0 x 14
[0.111352750s] [INFO ] [alacritty] Width: 3024, Height: 1888
[0.176936833s] [INFO ] [alacritty] PTY dimensions: 60 x 216
[0.179927750s] [INFO ] [alacritty] Initialisation complete
[0.182219208s] [INFO ] [alacritty] winit event: RedrawRequested(WindowId(WindowId(5233697712)))
[0.221970500s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5233697712)), event: Resized(PhysicalSize { width: 4294967295, height: 4294967295 }) }
[0.222038333s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5233697712)), event: Focused(false) }
[0.222054750s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5233697712)), event: Moved(PhysicalPosition { x: 712, y: 192 }) }
[0.222067250s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5233697712)), event: Moved(PhysicalPosition { x: 712, y: 248 }) }
[0.222076333s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5233697712)), event: Resized(PhysicalSize { width: 3024, height: 1888 }) }
[0.222088250s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5233697712)), event: Moved(PhysicalPosition { x: 0, y: 76 }) }
[0.222099916s] [INFO ] [alacritty] winit event: RedrawRequested(WindowId(WindowId(5233697712)))
[0.232136500s] [INFO ] [alacritty] winit event: AboutToWait
[0.232210041s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 132734416 }, requested_resume: None })
[0.266869541s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5233697712))), payload: Frame })
[0.266923000s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5233697712))), payload: Frame })
[0.266938583s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5233697712))), payload: Terminal(Wakeup) })
[0.266953875s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5233697712)), event: Focused(true) }
[0.266966166s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5233697712)), event: CursorEntered { device_id: DeviceId(DeviceId) } }
[0.266978000s] [INFO ] [alacritty] winit event: RedrawRequested(WindowId(WindowId(5233697712)))
[0.267985791s] [INFO ] [alacritty] winit event: AboutToWait
[0.268030000s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 168562875 }, requested_resume: None })
[0.268089208s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5233697712))), payload: Frame })
[0.268105583s] [INFO ] [alacritty] winit event: AboutToWait
[0.268119708s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 168659166 }, requested_resume: None })
[0.268604166s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5233697712)), event: Occluded(false) }
[0.268668916s] [INFO ] [alacritty] winit event: AboutToWait
[0.268704666s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 169232458 }, requested_resume: None })
[0.268827250s] [INFO ] [alacritty] winit event: AboutToWait
[0.268885166s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 169415625 }, requested_resume: None })
[0.268932125s] [INFO ] [alacritty] winit event: AboutToWait
[0.268954958s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 169488750 }, requested_resume: None })
[0.268983000s] [INFO ] [alacritty] winit event: AboutToWait
[0.269006000s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 169539958 }, requested_resume: None })
[0.269072291s] [INFO ] [alacritty] winit event: AboutToWait
[0.269090708s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 169626250 }, requested_resume: None })
[0.269116666s] [INFO ] [alacritty] winit event: AboutToWait
[0.269132833s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 169671833 }, requested_resume: None })
[0.269162375s] [INFO ] [alacritty] winit event: AboutToWait
[0.269217291s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 169718083 }, requested_resume: None })
[0.269268708s] [INFO ] [alacritty] winit event: AboutToWait
[0.269291791s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 169825208 }, requested_resume: None })
[0.269322583s] [INFO ] [alacritty] winit event: AboutToWait
[0.269344291s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 169877250 }, requested_resume: None })
[0.269369958s] [INFO ] [alacritty] winit event: AboutToWait
[0.269441000s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 169921666 }, requested_resume: None })
[0.269485625s] [INFO ] [alacritty] winit event: AboutToWait
[0.269543833s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 170041375 }, requested_resume: None })
[0.269592375s] [INFO ] [alacritty] winit event: AboutToWait
[0.269616625s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 170151000 }, requested_resume: None })
[0.269647541s] [INFO ] [alacritty] winit event: AboutToWait
[0.269699500s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 170203958 }, requested_resume: None })
[0.272197000s] [INFO ] [alacritty] winit event: AboutToWait
[0.272225666s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 172759208 }, requested_resume: None })
[0.272241916s] [INFO ] [alacritty] winit event: AboutToWait
[0.272256458s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 172792125 }, requested_resume: None })
[0.272287000s] [INFO ] [alacritty] winit event: AboutToWait
[0.272366916s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 172837750 }, requested_resume: None })
[0.272400833s] [INFO ] [alacritty] winit event: AboutToWait
[0.272414791s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 172954541 }, requested_resume: None })
[0.272435083s] [INFO ] [alacritty] winit event: AboutToWait
[0.272452625s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 172986208 }, requested_resume: None })
[0.272610500s] [INFO ] [alacritty] winit event: AboutToWait
[0.272624166s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 173163916 }, requested_resume: None })
[0.272636125s] [INFO ] [alacritty] winit event: AboutToWait
[0.272680916s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 173186791 }, requested_resume: None })
[0.272756041s] [INFO ] [alacritty] winit event: AboutToWait
[0.275495791s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 173312458 }, requested_resume: None })
[0.275563500s] [INFO ] [alacritty] winit event: AboutToWait
[0.275576125s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 176116458 }, requested_resume: None })
[0.275590750s] [INFO ] [alacritty] winit event: AboutToWait
[0.276176666s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 176141333 }, requested_resume: None })
[0.276216000s] [INFO ] [alacritty] winit event: AboutToWait
[0.276553708s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 176769083 }, requested_resume: None })
[0.276604291s] [INFO ] [alacritty] winit event: AboutToWait
[0.277885666s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 177158958 }, requested_resume: None })
[0.278313083s] [INFO ] [alacritty] winit event: AboutToWait
[0.278332625s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 178871416 }, requested_resume: None })
[0.278346208s] [INFO ] [alacritty] winit event: AboutToWait
[0.278485750s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 178896458 }, requested_resume: None })
[0.278521166s] [INFO ] [alacritty] winit event: AboutToWait
[0.278534000s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 179074041 }, requested_resume: None })
[0.279557541s] [INFO ] [alacritty] winit event: AboutToWait
[0.279588416s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 180126416 }, requested_resume: None })
[0.279607500s] [INFO ] [alacritty] winit event: AboutToWait
[0.279620583s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 180160291 }, requested_resume: None })
[0.279644333s] [INFO ] [alacritty] winit event: AboutToWait
[0.279659000s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 180198291 }, requested_resume: None })
[0.279673875s] [INFO ] [alacritty] winit event: AboutToWait
[0.282392125s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 180224958 }, requested_resume: None })
[0.282425500s] [INFO ] [alacritty] winit event: AboutToWait
[0.283672000s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 182978750 }, requested_resume: None })
[0.283715833s] [INFO ] [alacritty] winit event: AboutToWait
[0.283728291s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 184267625 }, requested_resume: None })
[0.283740916s] [INFO ] [alacritty] winit event: AboutToWait
[0.287574041s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 184291416 }, requested_resume: None })
[0.287625791s] [INFO ] [alacritty] winit event: AboutToWait
[0.287641291s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 188179916 }, requested_resume: None })
[0.287656083s] [INFO ] [alacritty] winit event: AboutToWait
[0.290773958s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 188206291 }, requested_resume: None })
[0.290802041s] [INFO ] [alacritty] winit event: AboutToWait
[0.290814583s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 191354500 }, requested_resume: None })
[0.290828666s] [INFO ] [alacritty] winit event: AboutToWait
[0.294195166s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 191379333 }, requested_resume: None })
[0.294236291s] [INFO ] [alacritty] winit event: AboutToWait
[0.294249958s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 194789583 }, requested_resume: None })
[0.294276083s] [INFO ] [alacritty] winit event: AboutToWait
[0.298256208s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 194827000 }, requested_resume: None })
[0.298291958s] [INFO ] [alacritty] winit event: AboutToWait
[0.298308291s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 198847375 }, requested_resume: None })
[0.298324583s] [INFO ] [alacritty] winit event: AboutToWait
[0.302327375s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 198875375 }, requested_resume: None })
[0.302353250s] [INFO ] [alacritty] winit event: AboutToWait
[0.302366791s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 202906666 }, requested_resume: None })
[0.302384833s] [INFO ] [alacritty] winit event: AboutToWait
[0.306379708s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 202937000 }, requested_resume: None })
[0.306411333s] [INFO ] [alacritty] winit event: AboutToWait
[0.306425041s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 206964958 }, requested_resume: None })
[0.306439166s] [INFO ] [alacritty] winit event: AboutToWait
[0.308191500s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 206990208 }, requested_resume: None })
[0.308232250s] [INFO ] [alacritty] winit event: AboutToWait
[0.308247041s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 208787125 }, requested_resume: None })
[0.308778666s] [INFO ] [alacritty] winit event: AboutToWait
[0.310451291s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 209336166 }, requested_resume: None })
[0.310498583s] [INFO ] [alacritty] winit event: AboutToWait
[0.310513000s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 211052833 }, requested_resume: None })
[0.310525500s] [INFO ] [alacritty] winit event: AboutToWait
[0.311409458s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 211076250 }, requested_resume: None })
[0.311431833s] [INFO ] [alacritty] winit event: AboutToWait
[0.359131000s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 211985833 }, requested_resume: None })
[0.360338000s] [INFO ] [alacritty] winit event: AboutToWait
[0.370461958s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 260898041 }, requested_resume: None })
[0.370628708s] [INFO ] [alacritty] winit event: AboutToWait
[0.382464500s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 271188166 }, requested_resume: None })
[0.382764416s] [INFO ] [alacritty] winit event: AboutToWait
[0.382791541s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 283330041 }, requested_resume: None })
[0.382811625s] [INFO ] [alacritty] winit event: AboutToWait
[0.421159250s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 283367333 }, requested_resume: None })
[0.421191083s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5233697712))), payload: Terminal(Wakeup) })
[0.421210416s] [INFO ] [alacritty] winit event: RedrawRequested(WindowId(WindowId(5233697712)))
[0.421996750s] [INFO ] [alacritty] winit event: AboutToWait
[0.422017041s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 322556166 }, requested_resume: None })
[0.422031375s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5233697712))), payload: Terminal(Wakeup) })
[0.422040666s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5233697712))), payload: Terminal(Wakeup) })
[0.422064000s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5233697712))), payload: Terminal(Wakeup) })
[0.422071416s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5233697712))), payload: Terminal(Wakeup) })
[0.422079166s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5233697712))), payload: Frame })
[0.422089625s] [INFO ] [alacritty] winit event: RedrawRequested(WindowId(WindowId(5233697712)))
[0.424825500s] [INFO ] [alacritty] winit event: AboutToWait
[0.424871125s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 325396708 }, requested_resume: Some(Instant { tv_sec: 5563, tv_nsec: 327494042 }) })
[0.424891625s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5233697712))), payload: Terminal(Wakeup) })
[0.424910000s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5233697712))), payload: Terminal(Wakeup) })
[0.424922625s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5233697712))), payload: Terminal(Wakeup) })
[0.424930833s] [INFO ] [alacritty] winit event: AboutToWait
[0.427236083s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 5563, tv_nsec: 325481208 }, requested_resume: Instant { tv_sec: 5563, tv_nsec: 327494042 } })
[0.427273083s] [INFO ] [alacritty] winit event: AboutToWait
[0.427293041s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 327827833 }, requested_resume: None })
[0.427309541s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5233697712))), payload: Frame })
[0.427326541s] [INFO ] [alacritty] winit event: RedrawRequested(WindowId(WindowId(5233697712)))
[0.427875500s] [INFO ] [alacritty] winit event: AboutToWait
[0.427900583s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 328432875 }, requested_resume: Some(Instant { tv_sec: 5563, tv_nsec: 335826916 }) })
[0.427914583s] [INFO ] [alacritty] winit event: AboutToWait
[0.435610625s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 5563, tv_nsec: 328464375 }, requested_resume: Instant { tv_sec: 5563, tv_nsec: 335826916 } })
[0.435659041s] [INFO ] [alacritty] winit event: AboutToWait
[0.435679291s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 336213375 }, requested_resume: None })
[0.435693458s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5233697712))), payload: Frame })
[0.435703583s] [INFO ] [alacritty] winit event: AboutToWait
[0.435712958s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 336253166 }, requested_resume: None })
[0.435722750s] [INFO ] [alacritty] winit event: AboutToWait
[0.777726666s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 336271750 }, requested_resume: None })
[0.778505250s] [INFO ] [alacritty] winit event: AboutToWait
[1.363561541s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5563, tv_nsec: 679121041 }, requested_resume: None })
[1.363941875s] [INFO ] [alacritty] winit event: AboutToWait
[2.275506166s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5564, tv_nsec: 264565750 }, requested_resume: None })
[2.276019166s] [INFO ] [alacritty] winit event: AboutToWait
[2.276095375s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5565, tv_nsec: 176619125 }, requested_resume: None })
[2.276189583s] [INFO ] [alacritty] winit event: AboutToWait
[3.239411333s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5565, tv_nsec: 176766708 }, requested_resume: None })
[3.241299833s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5233697712)), event: KeyboardInput { device_id: DeviceId(DeviceId), event: KeyEvent { physical_key: SuperLeft, logical_key: Super, text: None, location: Left, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: None, key_without_modifiers: Super } }, is_synthetic: false } }
[3.241406208s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5233697712)), event: ModifiersChanged(Modifiers { state: ModifiersState(SUPER), pressed_mods: ModifiersKeys(LSUPER) }) }
[3.241444125s] [INFO ] [alacritty] winit event: AboutToWait
[3.264258500s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5566, tv_nsec: 142050916 }, requested_resume: None })
[3.268951208s] [INFO ] [alacritty] winit event: AboutToWait
[3.269017666s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5566, tv_nsec: 169545708 }, requested_resume: None })
[3.269095833s] [INFO ] [alacritty] winit event: AboutToWait
[3.269227416s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5566, tv_nsec: 169663625 }, requested_resume: None })
[3.269410791s] [INFO ] [alacritty] winit event: AboutToWait
[3.289928416s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 5566, tv_nsec: 169983000 }, requested_resume: None })
[3.295811833s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5233697712)), event: KeyboardInput { device_id: DeviceId(DeviceId), event: KeyEvent { physical_key: Digit1, logical_key: Character("1"), text: Some("1"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("1"), key_without_modifiers: Character("1") } }, is_synthetic: false } }
[3.295869750s] [INFO ] [alacritty] winit event: AboutToWait
thread 'main' panicked at 'unexpected NULL returned from -[WinitWindow tabGroup]', /Users/huyvo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.1-beta/src/platform_impl/macos/appkit/window.rs:34:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/huyvo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.1-beta/src/platform_impl/macos/app_state.rs:398:33
```

**Comment by kchibisov** [comment]
Was it happening on previous macOS version or you don't remember that thing?

**Comment by huyvohcmc** [comment]
@kchibisov It happened on macOS Ventura too

**Comment by kchibisov** [comment]
Should be fixed now.
