### ISSUE TITLE
Crashing on startup on MacOS

### ISSUE THREAD

**Issue by dchatterjee172** [alacritty/alacritty#7272]
### System

OS: macOS
Version: `c2f8abecfbaf6b6388e7746b733b7f22cbb7a750`

### Logs

```
alacritty on  c2f8abecfbaf6b6388e7746b733b7f22cbb7a750 [?] via 🦀 v1.71.1 took 15s 
❯ RUST_BACKTRACE=full target/release/alacritty -vv
Created log file at "/var/folders/6y/1ckh4sh56fs481gyj5hlq_zr0000gn/T/Alacritty-56857.log"
[0.000002500s] [INFO ] [alacritty] Welcome to Alacritty
[0.000201250s] [INFO ] [alacritty] Version 0.13.0-dev (59c63d37)
[0.000505875s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/OMMITED/.config/alacritty/alacritty.toml"
[0.000667125s] [DEBUG] [alacritty] Using environment locale: C/UTF-8/C/C/C/C
[0.011097834s] [INFO ] [alacritty] Using Apple CGL
[0.021115625s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: OPENGL
                                     srgb_capable: true
[0.041768375s] [INFO ] [alacritty] Window scale factor: 2
[0.042767209s] [DEBUG] [alacritty] Loading "JetBrainsMono Nerd Font" font
[0.058573542s] [INFO ] [alacritty] Running on Apple M1 Pro
[0.058627834s] [INFO ] [alacritty] OpenGL version 4.1 Metal - 83.1, shader_version 4.10
[0.058642250s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.062941167s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.065001667s] [INFO ] [alacritty] Cell size: 13 x 29
[0.065025917s] [INFO ] [alacritty] Padding: 0 x 0
[0.065037959s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.070390625s] [INFO ] [alacritty] PTY dimensions: 41 x 123
[0.072527750s] [INFO ] [alacritty] Initialisation complete
thread 'PTY reader' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', /Users/OMMITED/alacritty/alacritty_terminal/src/event_loop.rs:215:68
stack backtrace:
   0:        0x1028a2a44 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb005c7b0db18e81c
   1:        0x1027e2448 - core::fmt::write::hd5dc98bbb37df0ea
   2:        0x1028820ec - std::io::Write::write_fmt::h042e9f2909d3f218
   3:        0x1028a2858 - std::sys_common::backtrace::print::h6f40cdd50ebad80c
   4:        0x102882b18 - std::panicking::default_hook::{{closure}}::hf87eed59167f92bd
   5:        0x1028828b0 - std::panicking::default_hook::h8fd4653aa15f3663
   6:        0x1028830bc - std::panicking::rust_panic_with_hook::h35d52c7b2c1a812e
   7:        0x1028a2ccc - std::panicking::begin_panic_handler::{{closure}}::h0b6f57be552c83ee
   8:        0x1028a2b30 - std::sys_common::backtrace::__rust_end_short_backtrace::hccd979d3efaf26cb
   9:        0x102882cdc - _rust_begin_unwind
  10:        0x1029212a4 - core::panicking::panic_fmt::h8c741ce671c330d0
  11:        0x102921100 - core::result::unwrap_failed::h4840784c52597da0
  12:        0x102753398 - core::result::Result<T,E>::unwrap::h20c97d826f86ccd8
                               at /opt/local/libexec/rust/src/rustc-1.71.1-src/library/core/src/result.rs:1076:23
  13:        0x102753398 - alacritty_terminal::event_loop::EventLoop<T,U>::spawn::{{closure}}::h864a332c3e884888
                               at /Users/OMMITED/alacritty/alacritty_terminal/src/event_loop.rs:215:17
  14:        0x102753398 - std::sys_common::backtrace::__rust_begin_short_backtrace::he7340b68a604fd60
                               at /opt/local/libexec/rust/src/rustc-1.71.1-src/library/std/src/sys_common/backtrace.rs:135:18
  15:        0x102671be4 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::heb41fb4faccb9289
                               at /opt/local/libexec/rust/src/rustc-1.71.1-src/library/std/src/thread/mod.rs:529:17
  16:        0x102671be4 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he0219bc6ee4b4f12
                               at /opt/local/libexec/rust/src/rustc-1.71.1-src/library/core/src/panic/unwind_safe.rs:271:9
  17:        0x102671be4 - std::panicking::try::do_call::hb5191f1c7c482cc2
                               at /opt/local/libexec/rust/src/rustc-1.71.1-src/library/std/src/panicking.rs:500:40
  18:        0x102671be4 - std::panicking::try::hcb825ecde170ddea
                               at /opt/local/libexec/rust/src/rustc-1.71.1-src/library/std/src/panicking.rs:464:19
  19:        0x102671be4 - std::panic::catch_unwind::hb63335f1082a4c5c
                               at /opt/local/libexec/rust/src/rustc-1.71.1-src/library/std/src/panic.rs:142:14
  20:        0x102671be4 - std::thread::Builder::spawn_unchecked_::{{closure}}::hd888e7df5f4c9a2d
                               at /opt/local/libexec/rust/src/rustc-1.71.1-src/library/std/src/thread/mod.rs:528:30
  21:        0x102671be4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h65c1302d4ae8604b
                               at /opt/local/libexec/rust/src/rustc-1.71.1-src/library/core/src/ops/function.rs:250:5
  22:        0x10287d6d0 - std::sys::unix::thread::Thread::new::thread_start::hb5367a09daffc493
  23:        0x19b0affa8 - __pthread_joiner_wake
[0.114828959s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
2023-10-08 09:45:24.290 alacritty[56857:2794279] *** Assertion failure in -[NSEvent charactersIgnoringModifiers], NSEvent.m:2699
```

<img width="915" alt="image" src="https://github.com/alacritty/alacritty/assets/10482742/8c96a208-e5fc-40e7-ac99-e9a880a75c97">

**Comment by dchatterjee172** [comment]
`ace987f343649ae98e5fb63cf825414855ccd86e` works for me.

**Comment by kchibisov** [comment]
fixed on master.

**Comment by kchibisov** [comment]
>Version: c2f8abecfbaf6b6388e7746b733b7f22cbb7a750

Version 0.13.0-dev (59c63d37)

Nah, can't trick me like that :p

**Comment by dchatterjee172** [comment]
> fixed on master.

It is working now. Thanks.

**Comment by dchatterjee172** [comment]
> > Version: [c2f8abe](https://github.com/alacritty/alacritty/commit/c2f8abecfbaf6b6388e7746b733b7f22cbb7a750)
> 
> Version 0.13.0-dev ([59c63d3](https://github.com/alacritty/alacritty/commit/59c63d373804fe9d00d92d2dd47174d4e1637333))
> 
> Nah, can't trick me like that :p

I thought I built c2f8abecfbaf6b6388e7746b733b7f22cbb7a750. 🙈 

Thanks for your quick response and fix.
