### ISSUE TITLE
macOS Sonoma blank screen

### ISSUE THREAD

**Issue by dseum** [alacritty/alacritty#7273]
Alacritty only shows the cursor, and I cannot input anything. I've confirmed 0.12.3 works correctly.

I saw #7259, and this issue is similar in that after a few seconds, Alacritty suddenly shows >50GB memory in the activity monitor. But since 0.13.0-dev is using `winit` 0.29.1-beta, maybe there was a problem there?

<img width="805" alt="image" src="https://github.com/alacritty/alacritty/assets/42305363/a0d8cced-69a0-4ec8-868d-2c319716c968">

### System

OS: macOS Sonoma
Version: 0.13.0-dev

### Logs

```
thread 'PTY reader' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', /alacritty/alacritty_terminal/src/event_loop.rs:215:68
stack backtrace:
   0:        0x100d0dc6c - std::backtrace_rs::backtrace::libunwind::trace::h0a647ce7e8dc2fab
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x100d0dc6c - std::backtrace_rs::backtrace::trace_unsynchronized::hea920694a2a8ac80
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x100d0dc6c - std::sys_common::backtrace::_print_fmt::h7b4e20c1da2ebb61
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x100d0dc6c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h819e9cbdf1a9e730
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x100d2a3bc - core::fmt::write::ha5e9bf3131ecb7c0
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:        0x100d0a494 - std::io::Write::write_fmt::h414ce9994bf17404
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:        0x100d0da80 - std::sys_common::backtrace::_print::h28d98f2094da6d1d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x100d0da80 - std::sys_common::backtrace::print::h8072db0bbd5bcc3d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x100d0f248 - std::panicking::default_hook::{{closure}}::h2c85c5b0c2ede151
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:        0x100d0f008 - std::panicking::default_hook::hcf2f70992d02f6fe
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:        0x100d0f720 - std::panicking::rust_panic_with_hook::h023af7f90b47eb8b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
  11:        0x100d0f654 - std::panicking::begin_panic_handler::{{closure}}::h14283519edc1d634
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
  12:        0x100d0e08c - std::sys_common::backtrace::__rust_end_short_backtrace::hc366c0b0cef5b747
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  13:        0x100d0f3e8 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  14:        0x100d44e70 - core::panicking::panic_fmt::h324f50b29db90195
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  15:        0x100d45238 - core::result::unwrap_failed::hf783e6a14bbaf60b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
  16:        0x10078e550 - core::result::Result<T,E>::unwrap::h65639104b7b4378f
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1089:23
  17:        0x1006db63c - alacritty_terminal::event_loop::EventLoop<T,U>::spawn::{{closure}}::hcc4a73334c65f35f
                               at /Users/denniseum/Projects/general/alacritty/alacritty_terminal/src/event_loop.rs:215:17
  18:        0x1007d5dac - std::sys_common::backtrace::__rust_begin_short_backtrace::hf43389282d6d1bef
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:134:18
  19:        0x1006a1008 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hd6fd16f69e1fbc52
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/mod.rs:526:17
  20:        0x100691a7c - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h5361bd0e4c9ebf8d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:271:9
  21:        0x1007c1b9c - std::panicking::try::do_call::h5a59a313aede3041
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  22:        0x1007c1fb0 - ___rust_try
  23:        0x1007c19e0 - std::panicking::try::hda38917e9cfda6f3
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  24:        0x10076fc88 - std::panic::catch_unwind::hfc4b92b5bfef3871
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  25:        0x1006a0e24 - std::thread::Builder::spawn_unchecked_::{{closure}}::hf3170255c44acd66
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/mod.rs:525:30
  26:        0x1005ee6ec - core::ops::function::FnOnce::call_once{{vtable.shim}}::h60cf2bc1516b908c
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  27:        0x100d13688 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd96d02f907263858
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  28:        0x100d13688 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfd80494da4543cfb
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  29:        0x100d13688 - std::sys::unix::thread::Thread::new::thread_start::h7f56b35fafcfec87
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
  30:        0x18c8fb034 - __pthread_joiner_wake
```

**Comment by kchibisov** [comment]
pull the latest master.

**Comment by dseum** [comment]
I just pulled, and it gives me the following (the memory issue persists):
```
thread 'PTY reader' panicked at 'attempt to multiply with overflow', alacritty_terminal/src/tty/unix.rs:418:25
```

**Comment by kchibisov** [comment]
just build release, but you need  #7220 + latest master patches.

Or you can use the `0.12.3` which works fine on macOS.

**Comment by dseum** [comment]
Oh, I didn't see #7220, thank you!
