### ISSUE TITLE
Misaligned address error with mesa 23.2.1

### ISSUE THREAD

**Issue by Gian-Laager** [alacritty/alacritty#7280]
I've just updated alacritty and now it immediately crashes with the error
```
fish: Job 1, 'alacritty --print-events' terminated by signal SIGBUS (Misaligned address error)
```
This only happens with mesa 23.2.1 when I downgrade to mesa 23.1.8 every thing works normally.

This is the log with mesa 23.1.8
```
[0.000002445s] [INFO ] [alacritty] Welcome to Alacritty
[0.000026680s] [INFO ] [alacritty] Version 0.12.3 (5efb0690)
[0.000032477s] [INFO ] [alacritty] Running on X11
[0.000405504s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/gianl/.config/alacritty/alacritty.yml"
[0.003626063s] [INFO ] [alacritty] Using GLX 1.4
[0.045170803s] [INFO ] [alacritty] Window scale factor: 1.4166666666666667
[0.046184561s] [DEBUG] [alacritty] Loading "FantasqueSansMNerdFont" font
[0.055147887s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.057592920s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.060151795s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.062711648s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.066391140s] [INFO ] [alacritty] Running on AMD Radeon Graphics (renoir, LLVM 16.0.6, DRM 3.54, 6.5.6-zen2-1-zen)
[0.066404130s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.072308722s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.083642978s] [INFO ] [alacritty] Cell size: 10 x 21
[0.083673360s] [INFO ] [alacritty] Padding: 0 x 6
[0.083679017s] [INFO ] [alacritty] Width: 800, Height: 600
[0.088915359s] [INFO ] [alacritty] PTY dimensions: 28 x 80
[0.092775812s] [INFO ] [alacritty] Initialisation complete
[0.095267289s] [DEBUG] [alacritty_terminal] New num_cols is 80 and num_lines is 41
[0.097253459s] [INFO ] [alacritty] Padding: 2 x 9
[0.097270989s] [INFO ] [alacritty] Width: 804, Height: 880
```

I don't really know if this is a general problem or if this is only on my machine. 

Here's the backtrace when I run it with gdb: 

```
#0  std::sys::unix::stack_overflow::imp::signal_handler (signum=7, info=0x7ffff7fc35b0, _data=<optimized out>) at library/std/src/sys/unix/stack_overflow.rs:81
#1  <signal handler called>
#2  disk_cache_has_key () at ../mesa-23.2.1/src/util/disk_cache.c:667
#3  can_skip_compile () at ../mesa-23.2.1/src/compiler/glsl/glsl_parser_extras.cpp:2220
#4  0x00007ffff5564763 in _mesa_glsl_compile_shader.constprop.0 () at ../mesa-23.2.1/src/compiler/glsl/glsl_parser_extras.cpp:2285
#5  0x00007ffff45ac7ba in _mesa_compile_shader () at ../mesa-23.2.1/src/mesa/main/shaderapi.c:1234
#6  0x00007ffff4457b04 in _mesa_unmarshal_CompileShader () at src/mapi/glapi/gen/marshal_generated2.c:1605
#7  0x00007ffff43230d2 in glthread_unmarshal_batch () at ../mesa-23.2.1/src/mesa/main/glthread.c:139
#8  0x00007ffff432e032 in _mesa_glthread_finish () at ../mesa-23.2.1/src/mesa/main/glthread.c:399
#9  _mesa_glthread_finish () at ../mesa-23.2.1/src/mesa/main/glthread.c:364
#10 0x00007ffff4469058 in _mesa_glthread_finish_before () at ../mesa-23.2.1/src/mesa/main/glthread.c:415
#11 _mesa_marshal_GetShaderiv () at src/mapi/glapi/gen/marshal_generated2.c:1832
#12 0x00005555556036e3 in alacritty::gl::GetShaderiv (shader=14, params=0x7ffffffee6b8)
    at target/release/build/alacritty-e16884b6acd5239b/out/gl_bindings.rs:1353
#13 alacritty::renderer::shader::Shader::new (shader_version=<optimized out>, shader_header=..., kind=35632, source=...) at alacritty/src/renderer/shader.rs:117
#14 0x0000555555603265 in alacritty::renderer::shader::ShaderProgram::new (shader_version=alacritty::renderer::shader::ShaderVersion::Glsl3, shader_header=...,
    vertex_shader=..., fragment_shader=...) at alacritty/src/renderer/shader.rs:40
#15 0x000055555576064d in alacritty::renderer::rects::RectShaderProgram::new (shader_version=<optimized out>, kind=<optimized out>)
    at alacritty/src/renderer/rects.rs:436
#16 0x00005555557602fc in alacritty::renderer::rects::RectRenderer::new (shader_version=<optimized out>) at alacritty/src/renderer/rects.rs:264
#17 0x00005555555f5db8 in alacritty::renderer::Renderer::new (context=<optimized out>,
    renderer_prefernce=<error reading variable: Cannot access memory at address 0x0>) at alacritty/src/renderer/mod.rs:125
#18 alacritty::display::Display::new (window=..., gl_context=..., config=0x555555c14fd0) at alacritty/src/display/mod.rs:427
#19 0x00005555557699bc in alacritty::window_context::WindowContext::new (window=..., context=..., config=..., options=..., proxy=...)
    at alacritty/src/window_context.rs:180
#20 0x0000555555768e09 in alacritty::window_context::WindowContext::initial (event_loop=0x555555be2a20, proxy=..., config=..., options=...,
    wayland_event_queue=...) at alacritty/src/window_context.rs:121
#21 0x00005555556e4158 in alacritty::event::Processor::create_initial_window (self=0x7fffffffd070, event_loop=0x7ffffffee258, proxy=...,
    options=<error reading variable: Cannot access memory at address 0x7fffd7bb02c4>) at alacritty/src/event.rs:1445
#22 0x000055555575281f in alacritty::event::{impl#12}::run::{closure#0} (event=..., event_loop=0x555555be2a20, control_flow=0x7fffffff9b40)
    at alacritty/src/event.rs:1522
#23 0x0000555555622c63 in winit::platform_impl::platform::sticky_exit_callback<alacritty::event::Event, alacritty::event::{impl#12}::run::{closure_env#0}> (
    evt=..., target=0x555555be2a20, control_flow=0x7fffffff9b40, callback=0x7fffffff9cc0)
    at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/mod.rs:884
#24 winit::platform_impl::platform::x11::{impl#2}::run_return::single_iteration<alacritty::event::Event, alacritty::event::{impl#12}::run::{closure_env#0}> (
    this=0x7fffffffc600, control_flow=0x7fffffff9b40, cause=0x7fffffff9c98, callback=0x7fffffff9cc0)
    at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:334
#25 0x00005555556e68b3 in winit::platform_impl::platform::x11::EventLoop<alacritty::event::Event>::run_return<alacritty::event::Event, alacritty::event::{impl#12}::run::{closure_env#0}> (self=0x7fffffffc600, callback=...)
    at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:443
#26 winit::platform_impl::platform::EventLoop<alacritty::event::Event>::run_return<alacritty::event::Event, alacritty::event::{impl#12}::run::{closure_env#0}> (
    self=0x7fffffffc600, callback=...) at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/mod.rs:785
#27 winit::platform::run_return::{impl#0}::run_return<alacritty::event::Event, alacritty::event::{impl#12}::run::{closure_env#0}> (self=0x7fffffffc600,
    event_handler=...) at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform/run_return.rs:51
#28 alacritty::event::Processor::run (self=0x7fffffffd070, event_loop=..., initial_window_options=...) at alacritty/src/event.rs:1501
#29 0x000055555566db85 in alacritty::alacritty (options=...) at alacritty/src/main.rs:189
#30 alacritty::main () at alacritty/src/main.rs:83
```

### System

OS: Garuda Linux
Version: alacritty 0.12.3 (5efb0690)
Linux: X11 Xmonad

### Logs

Crashes: SIGBUS (Misaligned address error)
Font/Terminal size: `alacritty -vv`
```
[0.000006216s] [INFO ] [alacritty] Welcome to Alacritty
[0.000043792s] [INFO ] [alacritty] Version 0.12.3 (5efb0690)
[0.000052871s] [INFO ] [alacritty] Running on X11
[0.000545260s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/gianl/.config/alacritty/alacritty.yml"
[0.006348882s] [INFO ] [alacritty] Using GLX 1.4
[0.045758424s] [INFO ] [alacritty] Window scale factor: 1.4166666666666667
[0.047403422s] [DEBUG] [alacritty] Loading "FantasqueSansMNerdFont" font
[0.057692392s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.060105237s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.062634090s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.065017671s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.068279939s] [INFO ] [alacritty] Running on AMD Radeon Graphics (renoir, LLVM 16.0.6, DRM 3.54, 6.5.6-zen2-1-zen)
[0.068291742s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
fish: Job 1, 'alacritty -vv' terminated by signal SIGBUS (Misaligned address error)
```

**Comment by chrisduerr** [comment]
> This only happens with mesa 23.2.1 when I downgrade to mesa 23.1.8 every thing works normally.

So why report this to Alacritty, not Mesa?

**Comment by kchibisov** [comment]
Not tracking mesa issue here.
