### ISSUE TITLE
Freezes on quitting IME

### ISSUE THREAD

**Issue by bczhc** [alacritty/alacritty#7456]
Alacritty will freeze when I do ctrl-c on [`fcitx5`](https://github.com/fcitx/fcitx5).

Screenrecord:

[a.webm](https://github.com/alacritty/alacritty/assets/49330580/8907ae3e-426d-4fdd-8362-f32c2ba1edef)

A seemingly 100% method to reproduce:
1. Start Alacritty with [IME integration envs](https://wiki.archlinux.org/title/Fcitx5#Integration) configured.
2. Run fcitx5 in the terminal.
3. After fcitx5 launched and loaded, do some interaction with the terminal (like scrolling up and down using the mouse or resizing the terminal window).
4. Send Ctrl-C.
5. Alacritty freezes.

Without `XMODIFIERS` env, it won't freeze. (also the input method will be unusable in Alacritty)

### System

OS: `Linux bczhc-arch 6.7.0-rc4-modified-dirty #72 SMP PREEMPT_DYNAMIC Mon Dec  4 20:09:41 CST 2023 x86_64 GNU/Linux`
Version: `alacritty 0.12.3 (5efb0690)` and `alacritty 0.14.0-dev (caf8c7fc)`
Linux/BSD: X11, i3, picom (the issue is reproducible without picom compositor)

### Logs

`alacritty -vv`

```
Created log file at "/tmp/Alacritty-3663442.log"
[0.000016195s] [INFO ] [alacritty] Welcome to Alacritty
[0.000072636s] [INFO ] [alacritty] Version 0.14.0-dev (caf8c7fc)
[0.000080239s] [INFO ] [alacritty] Running on X11
[0.000156355s] [WARN ] [alacritty] YAML config "/home/bczhc/.config/alacritty/alacritty.yml" is deprecated, please migrate to TOML using `alacritty migrate`
[0.001955519s] [WARN ] [alacritty_config_derive] Config warning: draw_bold_text_with_bright_colors has been deprecated; use colors.draw_bold_text_with_bright_colors instead
[0.002049449s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/bczhc/.config/alacritty/alacritty.yml"
[0.014224016s] [INFO ] [alacritty] Using GLX 1.4
[0.014448262s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL | GLES1 | GLES2)
                                     srgb_capable: true
[0.064353827s] [INFO ] [alacritty] Window scale factor: 1.6666666666666667
[0.083090138s] [DEBUG] [alacritty] Loading "monospace" font
[0.091868735s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.094486115s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.097486458s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.100196683s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.122484288s] [INFO ] [alacritty] Running on NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
[0.122527087s] [INFO ] [alacritty] OpenGL version 3.3.0 NVIDIA 545.29.06, shader_version 3.30 NVIDIA via Cg compiler
[0.122532874s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.124502297s] [DEBUG] [alacritty] Enabled debug logging for OpenGL
[0.124526107s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.129157823s] [INFO ] [alacritty] Cell size: 17 x 40
[0.129192283s] [INFO ] [alacritty] Padding: 8 x 8
[0.129201063s] [INFO ] [alacritty] Width: 800, Height: 600
[0.136022385s] [INFO ] [alacritty] PTY dimensions: 14 x 46
[0.138401128s] [INFO ] [alacritty] Initialisation complete
[0.177709666s] [DEBUG] [alacritty_terminal] New num_cols is 72 and num_lines is 30
[0.185446842s] [INFO ] [alacritty] Padding: 8 x 8
[0.185489481s] [INFO ] [alacritty] Width: 1252, Height: 1373
[0.186131531s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.186549120s] [DEBUG] [alacritty] [gl_render] Buffer detailed info: Buffer object 2 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (1), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (2), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (3), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (4), and GL_ARRAY_BUFFER_ARB, usage hint is GL_STREAM_DRAW) will use VIDEO memory as the source for buffer object operations.
[0.193219198s] [DEBUG] [alacritty] [gl_render] Buffer detailed info: Buffer object 3 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (1), and GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.
[4.842852879s] [DEBUG] [alacritty] [gl_render] Buffer detailed info: Buffer object 3 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (1), and GL_ARRAY_BUFFER_ARB, usage hint is GL_STREAM_DRAW) will use VIDEO memory as the source for buffer object operations.
[4.852663647s] [DEBUG] [alacritty] [gl_render] Buffer detailed info: Buffer object 3 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (1), and GL_ARRAY_BUFFER_ARB, usage hint is GL_STREAM_DRAW) will use VIDEO memory as the source for buffer object operations.
```

**`alacritty -vv` will have no further output after it freezes, as the screenrecord above shows.**

Keyboard and bindings: `alacritty --print-events`
https://gist.github.com/bczhc/6e3159d3c39cb794157f28f7e15a3bf8

**Comment by bczhc** [comment]
Apps inside Alacritty won't suspend. Thus in this case after alacritty freezes, IME is still usable otherwhere.

**Comment by chrisduerr** [comment]
>  Version: alacritty 0.12.3 (5efb0690) and alacritty 0.14.0-dev (caf8c7fc)

Just to be clear since there's currently a release candidate out: This was already broken in 0.12.3?

**Comment by bczhc** [comment]
Yes, broken in both 0.12.3 release and the latest branch commit.

**Comment by chrisduerr** [comment]
Have you run any previous Alacritty versions? If so were they unaffected?

**Comment by bczhc** [comment]
No, yet. I can have a try now.

**Comment by bczhc** [comment]
Seems this is always broken since I started using Alacritty...

Furthermore I've done some tests for old versions:

v0.11.0: panic
```
thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x2 but is 0x7fffbeada77b', /home/bczhc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xcb-1.1.1/src/base.rs:253:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:126:5
stack backtrace:
...
thread caused non-unwinding panic. aborting.
[1]    1363749 IOT instruction (core dumped)  target/debug/alacritty
```

v0.10.1, v0.9.0, v0.8.0, v0.5.0: defect

v0.3.0, v0.1.1: panic
```
thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState<'_>` uninitialized, which is invalid', library/core/src/panicking.rs:126:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
```

**Comment by bczhc** [comment]
Simply a "pkill" causes it:

[b.webm](https://github.com/user-attachments/assets/1f5a2a43-4623-45c5-8f6c-1c429f337da3)

Note this is unstably reproducible - sometimes a "pkill" freezes one or two Alacritty windows, sometimes all, sometimes none. ~~The instability may be related to the underlying mouse events/x11 events or something else; I don't know and didn't dig into it further.~~ (purely my own guess)

**Comment by kchibisov** [comment]
Could be just that the state gets messed up or something or maybe it's just a _xim_ feature. It's really hard to debug X11 IME given that it's generally very unstable unless dbus is used, and I'm not sure we're going to switch over to dbus.

**Comment by wengxt** [comment]
@kchibisov right now winit uses libX11, and libX11's xim implementation is really buggy and easy to block when IME quits (e.g. libX11 code wait for XIM messages in sync fashion without timeout and certain error handling). Using libX11's xim may be unavoidable since winit is using libX11.

If winit will move to pure xcb in the future, and thus use the rust binding https://github.com/H-M-H/xcb-imdkit-rs of my pure xcb implementation of xim https://github.com/fcitx/xcb-imdkit/ .

I'm not sure if it's possible to use xlib-xcb with xcb-imdkit. But it definitely requires some non-trivial change in winit if it can be made to work, since it only talks with the on-wire xkeyevent, instead of "XKeyEvent" struct in X.

**Comment by chrisduerr** [comment]
@kchibisov I have no intention of making large changes to Winit's X11 backend, unless you think there's something we can do here, I'd be happy to just close this as "no plans to fix".

**Comment by kchibisov** [comment]
We already have PR for xcb's xim stuff around, it's just wasn't really tested. Though, we have other lib for xim.
