### ISSUE TITLE
Windows: runtime error: Unable to spawn shell: The system cannot find the file specified

### ISSUE THREAD

**Issue by distrair** [alacritty/alacritty#7988]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Windows 11 22H2 22621.3447
Version: `alacritty 0.13.2 (bb8ea18)` 

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: 
```
[0.000012400s] [INFO ] [alacritty] Welcome to Alacritty
[0.001103400s] [INFO ] [alacritty] Version 0.13.2 (bb8ea18)
[0.004645400s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.045520500s] [INFO ] [alacritty] Window scale factor: 1
[0.344545700s] [INFO ] [alacritty] Using WGL
[0.639287900s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(false)
                                     config_api: Api(OPENGL | GLES1 | GLES2)
                                     srgb_capable: true
[0.647639400s] [DEBUG] [alacritty] Loading "Consolas" font
[0.660607900s] [INFO ] [alacritty] Running on NVIDIA GeForce GTX 1070/PCIe/SSE2
[0.660861200s] [INFO ] [alacritty] OpenGL version 3.3.0 NVIDIA 551.61, shader_version 3.30 NVIDIA via Cg compiler
[0.661021800s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.950497500s] [DEBUG] [alacritty] Enabled debug logging for OpenGL
[0.950983900s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.952832400s] [INFO ] [alacritty] Cell size: 8 x 17
[0.953267500s] [INFO ] [alacritty] Padding: 0 x 0
[0.953533200s] [INFO ] [alacritty] Width: 800, Height: 600
[1.065526000s] [INFO ] [alacritty] PTY dimensions: 35 x 100
[1.074750300s] [INFO ] [alacritty_terminal] Using Windows API for pseudoconsole
panicked at alacritty_terminal\src\tty\windows\conpty.rs:305:5:
Unable to spawn shell: The system cannot find the file specified. (os error 2)
```
Keyboard and bindings: 
```
[0.000025000s] [INFO ] [alacritty] Welcome to Alacritty
[0.001139200s] [INFO ] [alacritty] Version 0.13.2 (bb8ea18)
[0.005196100s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.006385100s] [INFO ] [alacritty] winit event: NewEvents(Init)
[0.006606900s] [INFO ] [alacritty] winit event: Resumed
[0.053406100s] [INFO ] [alacritty] Window scale factor: 1
[0.412051600s] [INFO ] [alacritty] Using WGL
[0.863645700s] [INFO ] [alacritty] Running on NVIDIA GeForce GTX 1070/PCIe/SSE2
[0.864004100s] [INFO ] [alacritty] OpenGL version 3.3.0 NVIDIA 551.61, shader_version 3.30 NVIDIA via Cg compiler
[0.866457400s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[1.059118600s] [INFO ] [alacritty] Cell size: 8 x 17
[1.059491000s] [INFO ] [alacritty] Padding: 0 x 0
[1.060233000s] [INFO ] [alacritty] Width: 800, Height: 600
[1.210055900s] [INFO ] [alacritty] PTY dimensions: 35 x 100
[1.211849500s] [INFO ] [alacritty_terminal] Using Windows API for pseudoconsole
panicked at alacritty_terminal\src\tty\windows\conpty.rs:305:5:
Unable to spawn shell: The system cannot find the file specified. (os error 2)
```

**Comment by chrisduerr** [comment]
Sounds like your system's `PATH` is broken. I'd assume this works when you pass the full path as shell?

**Comment by t5k6** [comment]
You can specify the shell in the configuration file:
https://github.com/alacritty/alacritty#Configuration
```toml
[shell]
program = "cmd"
```
