### ISSUE TITLE
Docker segfault after a build from an alacritty terminal on macOS m1

### ISSUE THREAD

**Issue by daisukixci** [alacritty/alacritty#8095]
Hi,

Docker segfault after a docker build (note that the actual build works, it something after that fails) from an alacritty terminal on macOS m1. I tried on other terminal like default macos one and iterm2 and I confirmed it works there

### System

OS: macOS 14.5
Version: alacritty 0.13.2 (bb8ea18)
Docker version: 4.32.0

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: 
<details>
<summary>alacritty -vv</summary>

```
Created log file at "/var/folders/d4/lv_35l157w50tjjgzfj4svwm0000gp/T/com.apple.shortcuts.mac-helper//Alacritty-51381.log"
[0.000001917s] [INFO ] [alacritty] Welcome to Alacritty
[0.000213709s] [INFO ] [alacritty] Version 0.13.2 (bb8ea18)
[0.000486250s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/gaetan.piquenot/.config/alacritty/alacritty.toml"
                                     "/Users/gaetan.piquenot/.config/alacritty/theme.toml"
[0.000805709s] [DEBUG] [alacritty] Using environment locale: en_US.UTF-8/UTF-8/en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/en_US.UTF-8
[0.025271250s] [INFO ] [alacritty] Using Apple CGL
[0.036943459s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL)
                                     srgb_capable: true
[0.053873750s] [INFO ] [alacritty] Window scale factor: 2
[0.054818500s] [DEBUG] [alacritty] Loading "UbuntuMono Nerd Font" font
[0.080589334s] [INFO ] [alacritty] Running on Apple M1 Max
[0.080637625s] [INFO ] [alacritty] OpenGL version 4.1 Metal - 88.1, shader_version 4.10
[0.080647709s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.084153542s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.093455167s] [INFO ] [alacritty] Cell size: 13 x 26
[0.093504167s] [INFO ] [alacritty] Padding: 0 x 0
[0.093515500s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.145029042s] [INFO ] [alacritty] PTY dimensions: 46 x 123
[0.146881042s] [INFO ] [alacritty] Initialisation complete
[0.245091250s] [DEBUG] [alacritty_terminal] New num_cols is 138 and num_lines is 74
[0.247074125s] [INFO ] [alacritty] Padding: 0 x 0
[0.247130167s] [INFO ] [alacritty] Width: 1800, Height: 1944
[0.256522375s] [DEBUG] [alacritty_terminal] New num_cols is 138 and num_lines is 84
[0.261642042s] [INFO ] [alacritty] Padding: 0 x 0
[0.261687209s] [INFO ] [alacritty] Width: 1800, Height: 2194
```
</details>
Keyboard and bindings: `alacritty --print-events`

<details>
<summary>Dockerfile to reproduce</summary>

```
FROM ubuntu:24.04
RUN echo foo
```
</details>

<details>
<summary>Output of docker build</summary>

```
docker build .
[+] Building 0.4s (6/6) FINISHED                                                                                                 docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                             0.0s
 => => transferring dockerfile: 105B                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/ubuntu:24.04                                                                                  0.4s
 => [internal] load .dockerignore                                                                                                                0.0s
 => => transferring context: 2B                                                                                                                  0.0s
 => [1/2] FROM docker.io/library/ubuntu:24.04@sha256:2e863c44b718727c860746568e1d54afd13b2fa71b160f5cd9058fc436217b30                            0.0s
 => => resolve docker.io/library/ubuntu:24.04@sha256:2e863c44b718727c860746568e1d54afd13b2fa71b160f5cd9058fc436217b30                            0.0s
 => CACHED [2/2] RUN echo foo                                                                                                                    0.0s
 => exporting to image                                                                                                                           0.0s
 => => exporting layers                                                                                                                          0.0s
 => => exporting manifest sha256:2a4235bf458a777f5a48ea59764464a4f6abf6bca060b491e7878d605ac73ffa                                                0.0s
 => => exporting config sha256:d0b7c43723727c5247aef49f0f401080c7df9375c8334ec2d2e40fee1785ec7d                                                  0.0s
 => => exporting attestation manifest sha256:831d665b618cc78e5efc1dc4169a67de6139399934d7c397cee25b0812288a98                                    0.0s
 => => exporting manifest list sha256:f479f0b1a127627953dc388b9a779ceadc55f20861865ea99dcdff446b5d22f2                                           0.0s
 => => naming to moby-dangling@sha256:f479f0b1a127627953dc388b9a779ceadc55f20861865ea99dcdff446b5d22f2                                           0.0s
 => => unpacking to moby-dangling@sha256:f479f0b1a127627953dc388b9a779ceadc55f20861865ea99dcdff446b5d22f2                                        0.0s

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/af9x92u90x9666eoafu4jrhny
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104739860]

goroutine 1 [running]:
github.com/docker/cli/cli-plugins/socket.(*PluginServer).closeAllConns(0x0?)
	/go/src/github.com/docker/cli/cli-plugins/socket/socket.go:111 +0x20
github.com/docker/cli/cli-plugins/socket.(*PluginServer).Close(0x0)
	/go/src/github.com/docker/cli/cli-plugins/socket/socket.go:101 +0x60
main.tryPluginRun.func1()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:252 +0x20
main.tryPluginRun({0x104f69f98?, 0x14000343240}, {0x104f74bb8?, 0x1400039e000}, 0x2?, {0x104ac071b?, 0x1400003a210?}, {0x1400011eb10, 0x1, 0x1?})
	/go/src/github.com/docker/cli/cmd/docker/docker.go:326 +0x3e8
main.runDocker({0x104f69f98?, 0x14000343240}, 0x1400039e000)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:391 +0x61c
main.dockerMain()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:50 +0x1d0
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:32 +0x1c
```
</details>

**Comment by chrisduerr** [comment]
Well you should report that to docker then.
