### ISSUE TITLE
Alacritty crashes on startup (Windows 7)

### ISSUE THREAD

**Issue by mrtuxa** [alacritty/alacritty#8124]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Windows 7 
Version: 
```
$ ./Alacritty.exe --version
alacritty 0.2.1
```
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`

```
$ RUST_BACKTRACE=1 ./Alacritty.exe -vvv
Welcome to Alacritty.
Configuration loaded from C:\Users\twinkpad\alacritty.yml
device_pixel_ratio: 1
width: 1024, height: 753
Initializing glyph cache
Finished initializing glyph cache in 0.154906774
width: 644, height: 412
Cell Size: (8 x 17)
PTY Dimensions: Line(24) x Column(80)
Scaling RGB by 0.66 from Rgb { r: 234, g: 234, b: 234 } to Rgb { r: 154, g: 154, b: 154 }
Using config-provided dim colors
Scaling RGB by 0.66 from Rgb { r: 234, g: 234, b: 234 } to Rgb { r: 154, g: 154, b: 154 }
Using config-provided dim colors
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Err { ptr: winpty_error_s { _unused: [] }, code: 4, message: "agent executable does not exist: \'C:\\Users\\twinkpad\\Downloads\\winpty-agent.exe\'" }', libcore\result.rs:1009:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: winpty_spawn_config_new
  11: BaseThreadInitThunk
  12: RtlUserThreadStart
```

Keyboard and bindings: `alacritty --print-events`

```
$ RUST_BACKTRACE=1 ./Alacritty.exe --print-events
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Err { ptr: winpty_error_s { _unused: [] }, code: 4, message: "agent executable does not exist: \'C:\\Users\\twinkpad\\Downloads\\winpty-agent.exe\'" }', libcore\result.rs:1009:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: winpty_spawn_config_new
  11: BaseThreadInitThunk
  12: RtlUserThreadStart
```

**Comment by kchibisov** [comment]
the version of alacritty/windows you've used are not supported.
