### ISSUE TITLE
thread 'main' panicked at alacritty/src/display/damage.rs:198:26: index out of bounds: the len is 25 but the index is 33

### ISSUE THREAD

**Issue by nevdelap** [alacritty/alacritty#8354]
### System

OS: **Linux**
Version: **alacritty 0.14.0**
Linux/BSD: **X11**, **i3**

### Logs

```
12:09:46 zen ~ 2 alacritty -vv
Created log file at "/tmp/Alacritty-4153734.log"
[0.000004588s] [INFO ] [alacritty] Welcome to Alacritty
[0.000075611s] [INFO ] [alacritty] Version 0.14.0 (22a44757)
[0.000082234s] [INFO ] [alacritty] Running on X11
[0.000489627s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/nevd/.config/alacritty/alacritty.toml"
                                     "/home/nevd/.config/alacritty/alacritty-theme/themes/github_light.toml"
[0.016628449s] [INFO ] [alacritty] Using GLX 1.4
[0.072741553s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL | GLES1 | GLES2)
                                     srgb_capable: false
[0.075799962s] [INFO ] [alacritty] Window scale factor: 1
[0.086039263s] [DEBUG] [alacritty] Loading "Fira Code" font
[0.100525019s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: LoadFlag(TARGET_LIGHT), render_mode: "Lcd", lcd_filter: 1 }
[0.103616720s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: LoadFlag(TARGET_LIGHT), render_mode: "Lcd", lcd_filter: 1 }
[0.106443105s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: LoadFlag(NO_BITMAP | TARGET_LIGHT), render_mode: "Lcd", lcd_filter: 1 }
[0.109289597s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: LoadFlag(NO_BITMAP | TARGET_LIGHT), render_mode: "Lcd", lcd_filter: 1 }
[0.115191663s] [INFO ] [alacritty] Running on AMD Radeon Graphics (radeonsi, renoir, LLVM 18.1.8, DRM 3.59, 6.11.10-2-MANJARO)
[0.115223423s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 24.2.8-arch1.1, shader_version 4.60
[0.115229314s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.123477795s] [DEBUG] [alacritty] Enabled debug logging for OpenGL
[0.123654957s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.136040048s] [INFO ] [alacritty] Cell size: 7 x 16
[0.136071056s] [INFO ] [alacritty] Padding: 0 x 0
[0.136076025s] [INFO ] [alacritty] Width: 800, Height: 600
[0.148753042s] [INFO ] [alacritty] PTY dimensions: 37 x 114
[0.154853510s] [INFO ] [alacritty] Initialisation complete
[0.158325915s] [DEBUG] [alacritty_terminal] New num_cols is 182 and num_lines is 25
[0.159404305s] [INFO ] [alacritty] Padding: 0 x 0
[0.159431746s] [INFO ] [alacritty] Width: 1279, Height: 400
thread 'main' panicked at alacritty/src/display/damage.rs:198:26:
index out of bounds: the len is 25 but the index is 35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Deleted log file at "/tmp/Alacritty-4153734.log"
12:09:52 zen ~ 101
```

### Steps To Reproduce

[doop.txt](https://github.com/user-attachments/files/18119778/doop.txt)

1. `alacritty -vv`
2. `cat doop.txt`  (It `cat`s fine.)
3. Scroll up with the mouse wheel.
4. Alacritty panics/closes.

I created this file talking to api.radio-browser.info and printing debug output. Either that station has its stream url all messed up like that, or my code talking to the api has done it, but printing terminal output while debugging I discovered the issue.

Since the file is a single 6321 line, I tried doing it with a file with with that many `a`s, but it didn't have the same effect.

**Comment by chrisduerr** [comment]
Seem related to the recent URL damage changes.

**Comment by chrisduerr** [comment]
While I don't remember intentionally fixing this, it seems fixed on the latest master. Could you confirm this @nevdelap?

**Comment by nevdelap** [comment]
Hi @chrisduerr. It is indeed! Good stuff! Thank you.
